#pragma once
#include "ramstream32_gpu_direct_atomicfree_multigpu_phasegrid.cuh"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <vector>

// v1.5: phase-local blockDim.x + grid selection. Measured phase work/ms is
// normalized to an intrinsic rate before EMA so samples from different launch
// shapes can be combined. Orbit and LOW p==1 retain the base launch geometry.
struct GdptLimits{int sms=1,max_threads_block=1024,max_threads_sm=2048,warp_size=32;};
struct GdptExec{GdpgShape grid{};int threads=256;};
static bool operator==(const GdptExec&a,const GdptExec&b){return a.grid==b.grid&&a.threads==b.threads;}
static bool operator!=(const GdptExec&a,const GdptExec&b){return !(a==b);}
struct GdptExecPlan{std::vector<GdptExec>high,low;};
struct GdptIntrinsicModel{std::array<std::array<double,GDM_MAX_GPU>,GDVW_PHASES>work_per_ms{};std::array<bool,GDVW_PHASES>valid{};};
struct GdptJointReplan{GdvwPlan wave;GdptExecPlan exec;double baseline_ms=0,candidate_ms=0;unsigned retuned_phases=0,wave_count_changes=0,grid_shape_changes=0,thread_changes=0;};

static GdptExecPlan gdpt_initial_exec(int gx,int gy,int t){GdptExecPlan p;p.high.assign(HIGH_LUT_K,{{gx,gy},t});p.low.assign(LOW_LUT_K,{{gx,gy},t});return p;}
static std::vector<int> gdpt_thread_candidates(int base,int cur,const GdptLimits&l){std::vector<int>v;auto add=[&](int t){if(t>0&&t<=l.max_threads_block&&std::find(v.begin(),v.end(),t)==v.end())v.push_back(t);};add(128);add(256);add(512);add(base);add(cur);std::sort(v.begin(),v.end());return v;}
static std::vector<GdptExec> gdpt_exec_candidates(int bx,int by,int bt,GdptExec cur,const GdptLimits&l){std::vector<GdptExec>o;for(int t:gdpt_thread_candidates(bt,cur.threads,l))for(auto s:gdpg_shape_candidates(bx,by,cur.grid))o.push_back({s,t});return o;}

static double gdpt_efficiency_factor(bool high,std::uint32_t pi,int d,const GdvwPhase&ph,GdptExec e,const GdptLimits&l,const StorageLayout&layout,const GdmShardHost&shard,const GpuDirectGatherHost&ordinary,const GpuDirectCrossGatherHost&cross){
    if(e.threads<=0||e.threads>l.max_threads_block)return 1e9;double launched=0,useful=0;
    for(std::uint32_t b=0;b<layout.block_blocks.size();++b){const auto&sb=layout.block_blocks[b];if(!sb.valid||!sb.rows||!sb.cols||shard.block_blocks[b].owner!=d)continue;
        if(high){std::size_t oi=std::size_t(pi)*ordinary.high_pitch+b;std::uint32_t nl=ordinary.high_off[oi+1]-ordinary.high_off[oi];oi=std::size_t(pi)*cross.high_pitch+b;std::uint32_t nc=cross.high_off[oi+1]-cross.high_off[oi];auto add=[&](std::uint32_t n){if(!n)return;launched+=double(e.grid.x)*e.grid.y*e.threads;useful+=std::min(double(e.grid.x)*e.threads,double(sb.cols))*std::min(double(e.grid.y),double(n));};add(nl);add(nc);}
        else{std::size_t oi=std::size_t(pi)*ordinary.low_pitch+b;std::uint32_t nl=ordinary.low_off[oi+1]-ordinary.low_off[oi];oi=std::size_t(pi)*cross.low_pitch+b;std::uint32_t nc=cross.low_off[oi+1]-cross.low_off[oi];auto add=[&](std::uint32_t n){if(!n)return;launched+=double(e.grid.x)*e.grid.y*e.threads;useful+=std::min(double(e.grid.x)*e.threads,double(n))*std::min(double(e.grid.y),double(sb.rows));};add(nl);add(nc);}}
    double waste=useful>0?std::min(12.0,launched/useful):1.0,target=double(std::max(1,2*l.sms)),us=0,ws=0;
    for(int w=0;w<ph.waves;++w){unsigned nz=unsigned(ph.wave[w].dbids[d].size());if(!nz)continue;double cta=double(e.grid.x)*e.grid.y*nz,pen=std::max(1.0,target/std::max(1.0,cta)),wt=std::max(1.0,double(ph.wave[w].work[d]));us+=pen*wt;ws+=wt;}
    double under=ws>0?std::min(8.0,us/ws):1.0;int warp=std::max(1,l.warp_size);double warp_pen=double(((e.threads+warp-1)/warp)*warp)/e.threads;int resident=std::max(1,l.max_threads_sm/std::max(1,e.threads));double res=resident>=2?1.0:2.0/resident;return .50*waste+.30*under+.10*warp_pen+.10*res;
}

static void gdpt_update_intrinsic(GdptIntrinsicModel&m,const GdpgPhaseCalibration&s,const GdvwPlan&w,const GdptExecPlan&e,unsigned ui,const GdptLimits&l,const StorageLayout&layout,const GdmShardHost&shard,const GpuDirectGatherHost&o,const GpuDirectCrossGatherHost&c,int ng){double a=ui?.35:.65;auto one=[&](bool hi,std::uint32_t pi,int ph,const GdvwPhase&p,GdptExec x){bool any=false;for(int d=0;d<ng;++d){double r=s.work_per_ms[ph][d];if(r<=0)continue;double v=r*gdpt_efficiency_factor(hi,pi,d,p,x,l,layout,shard,o,c);double&z=m.work_per_ms[ph][d];z=z>0?(1-a)*z+a*v:v;any=true;}m.valid[ph]=m.valid[ph]||any;};for(int pi=0;pi<HIGH_LUT_K;++pi)one(true,std::uint32_t(pi),pi,w.high[pi],e.high[pi]);for(int q=LOW_LUT_K;q>=2;--q){int pi=LOW_LUT_K-q,ph=HIGH_LUT_K+pi;one(false,std::uint32_t(pi),ph,w.low[pi],e.low[pi]);}}

static double gdpt_device_phase_score(bool hi,std::uint32_t pi,int ph,int d,const GdvwPhase&p,GdptExec e,const GdptIntrinsicModel&m,const GdorOnlineModel&g,const GdptLimits&l,const StorageLayout&layout,const GdmShardHost&shard,const GpuDirectGatherHost&o,const GpuDirectCrossGatherHost&c){auto items=hi?gdaw_high_items(pi,d,layout,shard,o,c):gdaw_low_items(pi,d,layout,shard,o,c);if(items.empty())return 0.0;double ir=m.work_per_ms[ph][d];if(ir<=0)return 1e300;double rate=ir/std::max(1e-9,gdpt_efficiency_factor(hi,pi,d,p,e,l,layout,shard,o,c));auto bins=gdvw_bins_from_phase(p,d,items);return gdvw_score_bins(bins,layout,shard,g.topology,d,rate,gdvw_wave_group_ms());}
static double gdpt_phase_score(bool hi,std::uint32_t pi,int ph,const GdvwPhase&p,GdptExec e,const GdptIntrinsicModel&m,const GdorOnlineModel&g,const GdptLimits&l,const StorageLayout&layout,const GdmShardHost&shard,const GpuDirectGatherHost&o,const GpuDirectCrossGatherHost&c,int ng){double z=0;for(int d=0;d<ng;++d)z=std::max(z,gdpt_device_phase_score(hi,pi,ph,d,p,e,m,g,l,layout,shard,o,c));return z;}

static GdvwPhase gdpt_build_wave_candidate(bool hi,std::uint32_t pi,int ph,int k,const GdvwPhase&ref,GdptExec re,const GdptIntrinsicModel&m,const GdorOnlineModel&g,const GdptLimits&l,const StorageLayout&layout,const GdmShardHost&shard,const GpuDirectGatherHost&o,const GpuDirectCrossGatherHost&c,int ng){GdvwPhase out;out.waves=k;for(int d=0;d<ng;++d){auto items=hi?gdaw_high_items(pi,d,layout,shard,o,c):gdaw_low_items(pi,d,layout,shard,o,c);if(items.empty())continue;double ir=m.work_per_ms[ph][d],f=gdpt_efficiency_factor(hi,pi,d,ref,re,l,layout,shard,o,c),rate=ir>0?ir/std::max(1e-9,f):g.compute.work_per_ms[d],ignored=0;auto bins=gdvw_optimize_k(std::move(items),k,layout,shard,g.topology,d,std::max(rate,1e-9),gdvw_wave_group_ms(),&ignored);gdvw_emit_device(out,d,bins,layout);}return out;}

static GdptJointReplan gdpt_joint_replan(const GdvwPlan&cw,const GdptExecPlan&ce,const GdptIntrinsicModel&m,const GdorOnlineModel&g,int bx,int by,int bt,const GdptLimits&l,const StorageLayout&layout,const GdmShardHost&shard,const GpuDirectGatherHost&o,const GpuDirectCrossGatherHost&c,const GdmsStagePlan&exact,int ng){GdptJointReplan out;out.wave=cw;out.exec=ce;if(!g.topology.custom)return out;auto tune=[&](bool hi,std::uint32_t pi,int ph,const GdvwPhase&old,GdptExec oe){double base=gdpt_phase_score(hi,pi,ph,old,oe,m,g,l,layout,shard,o,c,ng),best=base;GdvwPhase bw=old;GdptExec be=oe;auto es=gdpt_exec_candidates(bx,by,bt,oe,l);for(int k=GDVW_MIN_WAVES;k<=GDVW_MAX_WAVES;++k){auto cand=gdpt_build_wave_candidate(hi,pi,ph,k,old,oe,m,g,l,layout,shard,o,c,ng);for(auto e:es){double z=gdpt_phase_score(hi,pi,ph,cand,e,m,g,l,layout,shard,o,c,ng);if(z+1e-6<best){best=z;bw=cand;be=e;}}}out.baseline_ms+=base;double gain=base>0?100*(base-best)/base:0;if(gain>=GDOR_MIN_REPLAN_GAIN_PCT){out.candidate_ms+=best;++out.retuned_phases;if(bw.waves!=old.waves)++out.wave_count_changes;if(be.grid!=oe.grid)++out.grid_shape_changes;if(be.threads!=oe.threads)++out.thread_changes;return std::pair<GdvwPhase,GdptExec>{std::move(bw),be};}out.candidate_ms+=base;return std::pair<GdvwPhase,GdptExec>{old,oe};};for(int p=TARGET_W-1;p>=LOW_LUT_K+1;--p){std::uint32_t pi=std::uint32_t((TARGET_W-1)-p);auto r=tune(true,pi,int(pi),cw.high[pi],ce.high[pi]);out.wave.high[pi]=std::move(r.first);out.exec.high[pi]=r.second;}for(int p=LOW_LUT_K;p>=2;--p){std::uint32_t pi=std::uint32_t(LOW_LUT_K-p);int ph=HIGH_LUT_K+int(pi);auto r=tune(false,pi,ph,cw.low[pi],ce.low[pi]);out.wave.low[pi]=std::move(r.first);out.exec.low[pi]=r.second;}gdvw_recount(out.wave,exact,ng);return out;}
static double gdpt_gain_pct(const GdptJointReplan&r){return r.baseline_ms>0?100*(r.baseline_ms-r.candidate_ms)/r.baseline_ms:0;}

static void gdpt_enqueue_row_ready(GdvwPipeline&pipe,const GdowOrbitPlan&op,const GdmsStagePlan&gp,const GdvwPlan&wp,const GdptExecPlan&ep,const StorageLayout&layout,const GdmShardHost&shard,Count*const*mp,Count*const*bp,int bt,int bx,int by,int&slot,bool measure){dim3 ob(bt);int phase=0,ready=-1;for(int p=TARGET_W-1;p>=LOW_LUT_K+1;--p,++phase){std::uint32_t pi=std::uint32_t((TARGET_W-1)-p);const auto&x=op.high[pi];gdpo_stage_orbit(pipe,phase,ready,x.deps,layout,shard,mp,bp);for(int d=0;d<pipe.ngpu;++d){ck(cudaSetDevice(d),"gdpt high orbit device");dim3 gg(bx,by,unsigned(layout.main_blocks.size()));gdow_high_orbit_kernel<<<gg,ob,0,pipe.compute[d]>>>(p,x.active_source_mask[d]);ck(cudaGetLastError(),"gdpt high orbit");}int od=slot;pipe.fence(slot++);auto e=ep.high[pi];gdvw_gather_high(pipe,wp.high[pi],phase,od,layout,shard,mp,p,e.threads,e.grid.x,e.grid.y,measure);ready=slot;pipe.fence(slot++);}for(int p=LOW_LUT_K;p>=1;--p,++phase){std::uint32_t pi=std::uint32_t(LOW_LUT_K-p);const auto&x=op.low[pi];gdpo_stage_orbit(pipe,phase,ready,x.deps,layout,shard,mp,bp);for(int d=0;d<pipe.ngpu;++d){ck(cudaSetDevice(d),"gdpt low orbit device");dim3 gg(bx,by,unsigned(layout.main_blocks.size()));gdow_low_orbit_kernel<<<gg,ob,0,pipe.compute[d]>>>(p,x.active_source_mask[d]);ck(cudaGetLastError(),"gdpt low orbit");}int od=slot;pipe.fence(slot++);if(p>1){auto e=ep.low[pi];gdvw_gather_low(pipe,wp.low[pi],phase,od,layout,shard,mp,p,e.threads,e.grid.x,e.grid.y,measure);}else{gdmp_stage_sources(pipe,od,gp.low[pi].source,layout,shard,mp);unsigned nt=unsigned(layout.main_blocks.size());for(int d=0;d<pipe.ngpu;++d){ck(cudaSetDevice(d),"gdpt p1 local device");dim3 gg(bx,by,nt);gdms_low_local_gather_kernel<<<gg,ob,0,pipe.compute[d]>>>(p);ck(cudaGetLastError(),"gdpt p1 local");}int ld=slot;pipe.fence(slot++);gdmp_stage_sources(pipe,ld,gp.low[pi].cross_refresh,layout,shard,mp);for(int d=0;d<pipe.ngpu;++d){ck(cudaSetDevice(d),"gdpt p1 cross device");dim3 gg(bx,by,nt);gdms_low_cross_gather_kernel<<<gg,ob,0,pipe.compute[d]>>>(p);ck(cudaGetLastError(),"gdpt p1 cross");}}ready=slot;pipe.fence(slot++);}}
