#pragma once

#include "ramstream32_bucket_reverse_split18.hpp"

#include <cstdint>
#include <cstdlib>
#include <iostream>

__constant__ BucketOrbitOp *D_RS18_LOW_NN,*D_RS18_LOW_NR,*D_RS18_LOW_NL,*D_RS18_HIGH_NN,*D_RS18_HIGH_NR,*D_RS18_HIGH_NL;
__constant__ uint8_t *D_RS18_LOW_NN_HI,*D_RS18_LOW_NR_HI,*D_RS18_LOW_NL_HI,*D_RS18_HIGH_NN_HI,*D_RS18_HIGH_NR_HI,*D_RS18_HIGH_NL_HI;
__constant__ uint32_t *D_RS18_LOW_NN_OFF,*D_RS18_LOW_NR_OFF,*D_RS18_LOW_NL_OFF,*D_RS18_HIGH_NN_OFF,*D_RS18_HIGH_NR_OFF,*D_RS18_HIGH_NL_OFF;
__constant__ uint32_t D_RS18_PITCH;

struct ReverseSplit18DeviceTables{
    BucketOrbitOp *low_nn=nullptr,*low_nr=nullptr,*low_nl=nullptr,*high_nn=nullptr,*high_nr=nullptr,*high_nl=nullptr;
    uint8_t *low_nn_hi=nullptr,*low_nr_hi=nullptr,*low_nl_hi=nullptr,*high_nn_hi=nullptr,*high_nr_hi=nullptr,*high_nl_hi=nullptr;
    uint32_t *low_nn_off=nullptr,*low_nr_off=nullptr,*low_nl_off=nullptr,*high_nn_off=nullptr,*high_nr_off=nullptr,*high_nl_off=nullptr;
    template<class T>static void cp(T*&d,const std::vector<T>&s,const char*w){if(s.empty())return;ck(cudaMalloc(&d,s.size()*sizeof(T)),w);ck(cudaMemcpy(d,s.data(),s.size()*sizeof(T),cudaMemcpyHostToDevice),w);}
    void install(const ReverseSplit18Host&h){cp(low_nn,h.low.nn,"rs18 low nn");cp(low_nr,h.low.nr,"rs18 low nr");cp(low_nl,h.low.nl,"rs18 low nl");cp(high_nn,h.high.nn,"rs18 high nn");cp(high_nr,h.high.nr,"rs18 high nr");cp(high_nl,h.high.nl,"rs18 high nl");cp(low_nn_hi,h.low.nn_hi,"rs18 low nn hi");cp(low_nr_hi,h.low.nr_hi,"rs18 low nr hi");cp(low_nl_hi,h.low.nl_hi,"rs18 low nl hi");cp(high_nn_hi,h.high.nn_hi,"rs18 high nn hi");cp(high_nr_hi,h.high.nr_hi,"rs18 high nr hi");cp(high_nl_hi,h.high.nl_hi,"rs18 high nl hi");cp(low_nn_off,h.low.nn_off,"rs18 low nn off");cp(low_nr_off,h.low.nr_off,"rs18 low nr off");cp(low_nl_off,h.low.nl_off,"rs18 low nl off");cp(high_nn_off,h.high.nn_off,"rs18 high nn off");cp(high_nr_off,h.high.nr_off,"rs18 high nr off");cp(high_nl_off,h.high.nl_off,"rs18 high nl off");
#define RS18_SYM(sym,ptr,msg) ck(cudaMemcpyToSymbol(sym,&ptr,sizeof(ptr)),msg)
        RS18_SYM(D_RS18_LOW_NN,low_nn,"rs18 low nn ptr");RS18_SYM(D_RS18_LOW_NR,low_nr,"rs18 low nr ptr");RS18_SYM(D_RS18_LOW_NL,low_nl,"rs18 low nl ptr");RS18_SYM(D_RS18_HIGH_NN,high_nn,"rs18 high nn ptr");RS18_SYM(D_RS18_HIGH_NR,high_nr,"rs18 high nr ptr");RS18_SYM(D_RS18_HIGH_NL,high_nl,"rs18 high nl ptr");RS18_SYM(D_RS18_LOW_NN_HI,low_nn_hi,"rs18 low nn hi ptr");RS18_SYM(D_RS18_LOW_NR_HI,low_nr_hi,"rs18 low nr hi ptr");RS18_SYM(D_RS18_LOW_NL_HI,low_nl_hi,"rs18 low nl hi ptr");RS18_SYM(D_RS18_HIGH_NN_HI,high_nn_hi,"rs18 high nn hi ptr");RS18_SYM(D_RS18_HIGH_NR_HI,high_nr_hi,"rs18 high nr hi ptr");RS18_SYM(D_RS18_HIGH_NL_HI,high_nl_hi,"rs18 high nl hi ptr");RS18_SYM(D_RS18_LOW_NN_OFF,low_nn_off,"rs18 low nn off ptr");RS18_SYM(D_RS18_LOW_NR_OFF,low_nr_off,"rs18 low nr off ptr");RS18_SYM(D_RS18_LOW_NL_OFF,low_nl_off,"rs18 low nl off ptr");RS18_SYM(D_RS18_HIGH_NN_OFF,high_nn_off,"rs18 high nn off ptr");RS18_SYM(D_RS18_HIGH_NR_OFF,high_nr_off,"rs18 high nr off ptr");RS18_SYM(D_RS18_HIGH_NL_OFF,high_nl_off,"rs18 high nl off ptr");
#undef RS18_SYM
        uint32_t pitch=h.nblocks+1;ck(cudaMemcpyToSymbol(D_RS18_PITCH,&pitch,sizeof(pitch)),"rs18 pitch");
    }
    void release(){cudaFree(low_nn);cudaFree(low_nr);cudaFree(low_nl);cudaFree(high_nn);cudaFree(high_nr);cudaFree(high_nl);cudaFree(low_nn_hi);cudaFree(low_nr_hi);cudaFree(low_nl_hi);cudaFree(high_nn_hi);cudaFree(high_nr_hi);cudaFree(high_nl_hi);cudaFree(low_nn_off);cudaFree(low_nr_off);cudaFree(low_nl_off);cudaFree(high_nn_off);cudaFree(high_nr_off);cudaFree(high_nl_off);low_nn=low_nr=low_nl=high_nn=high_nr=high_nl=nullptr;low_nn_hi=low_nr_hi=low_nl_hi=high_nn_hi=high_nr_hi=high_nl_hi=nullptr;low_nn_off=low_nr_off=low_nl_off=high_nn_off=high_nr_off=high_nl_off=nullptr;}
};

struct ReverseBucketFusedClosureOnlyTables{
    ReverseBucketFusedDeviceTables full;
    void install(const ReverseBucketAtomicHost&rb,const ReverseBucketFusedHost&rf){full.install(rb,rf);cudaFree(full.low_orbit);cudaFree(full.high_orbit);cudaFree(full.low_orbit_off);cudaFree(full.high_orbit_off);full.low_orbit=full.high_orbit=nullptr;full.low_orbit_off=full.high_orbit_off=nullptr;}
    void release(){full.release();}
};

__device__ __forceinline__ uint32_t rs18_code(BucketOrbitOp op,uint8_t hi){return (uint32_t(hi)<<10)|uint32_t((op>>54)&0x3ffu);}
__device__ __forceinline__ uint32_t rs18_rid(uint32_t z,const uint32_t*off,size_t oi){return z==BKOC18_NONE?BKOC_NONE:off[oi]+z;}
__device__ __forceinline__ uint32_t rs18_low_jblock(uint32_t bid,const BucketPhysicalBlock&xb,int p,uint32_t kind){if(p!=LOW_LUT_K)return bid;uint32_t center=kind==CPU_ORBIT_NN?uint32_t(::L):uint32_t(N);return 3u*uint32_t(xb.he)+center;}
__device__ __forceinline__ uint32_t rs18_high_jblock(uint32_t bid,const BucketPhysicalBlock&xb,int p,uint32_t kind){if(p!=LOW_LUT_K+1)return bid;uint32_t center=kind==CPU_ORBIT_NR?uint32_t(::L):uint32_t(R);int he=int(xb.hs)+(center==uint32_t(R)?1:-1);return uint32_t(3*he+int(center));}

__global__ void bucket_reverse_low_split18_kernel(int p){uint32_t bid=blockIdx.z;if(bid>=D_BKF_MAIN_NBLOCKS)return;uint32_t pi=uint32_t(p-1);size_t oi=size_t(pi)*D_RS18_PITCH+bid;uint32_t na=D_RS18_LOW_NN_OFF[oi],nb=D_RS18_LOW_NN_OFF[oi+1],ra=D_RS18_LOW_NR_OFF[oi],rb=D_RS18_LOW_NR_OFF[oi+1],la=D_RS18_LOW_NL_OFF[oi],lb=D_RS18_LOW_NL_OFF[oi+1],n0=nb-na,n1=rb-ra,total=n0+n1+(lb-la);if(!total)return;for(uint32_t k=uint32_t(blockIdx.x)*blockDim.x+threadIdx.x;k<total;k+=uint32_t(gridDim.x)*blockDim.x){uint32_t kind,qi;BucketOrbitOp op;uint8_t hi;if(k<n0){kind=CPU_ORBIT_NN;qi=na+k;op=D_RS18_LOW_NN[qi];hi=D_RS18_LOW_NN_HI[qi];}else if(k<n0+n1){kind=CPU_ORBIT_NR;qi=ra+k-n0;op=D_RS18_LOW_NR[qi];hi=D_RS18_LOW_NR_HI[qi];}else{kind=CPU_ORBIT_NL;qi=la+k-n0-n1;op=D_RS18_LOW_NL[qi];hi=D_RS18_LOW_NL_HI[qi];}uint32_t sl=bkf_orbit_src(op),jl=bkf_orbit_partner(op),dl=bkf_orbit_drop(op),ss=bkf_loc_owner(sl),js=bkf_loc_owner(jl),ds=bkf_loc_owner(dl);BucketPhysicalBlock xb=bkf_low_main(ss,bid),jb=bkf_low_main(js,rs18_low_jblock(bid,xb,p,kind)),db=bkf_low_block(ds,uint32_t(xb.he));uint32_t rid=rs18_rid(rs18_code(op,hi),D_RBF_LOW_OFF,size_t(pi)*D_RBF_LOW_PITCH+uint32_t(xb.he));for(uint32_t hr=blockIdx.y;hr<xb.rows;hr+=gridDim.y){Count*ip=bkf_ptr(ss,xb.off+Code(hr)*xb.cols+bkf_loc_rank(sl)),*jp=bkf_ptr(js,jb.off+Code(hr)*jb.cols+bkf_loc_rank(jl)),*dp=bkf_ptr(ds,db.off+Code(hr)*db.cols+bkf_loc_rank(dl));Count c=*ip,old=*dp,extra=bkoc_r_low_extra(rid,db,hr);if(kind==CPU_ORBIT_NN){*jp=gpu_direct_add(*jp,c);*ip=gpu_direct_add(c,old);*dp=extra;}else{Count cc=*jp;*ip=gpu_direct_add(gpu_direct_add(c,cc),old);*dp=gpu_direct_add(c,extra);}}}}
__global__ void bucket_reverse_high_split18_kernel(int p){uint32_t bid=blockIdx.z;if(bid>=D_BKF_MAIN_NBLOCKS)return;uint32_t pi=uint32_t(p-(LOW_LUT_K+1));size_t oi=size_t(pi)*D_RS18_PITCH+bid;uint32_t na=D_RS18_HIGH_NN_OFF[oi],nb=D_RS18_HIGH_NN_OFF[oi+1],ra=D_RS18_HIGH_NR_OFF[oi],rb=D_RS18_HIGH_NR_OFF[oi+1],la=D_RS18_HIGH_NL_OFF[oi],lb=D_RS18_HIGH_NL_OFF[oi+1],n0=nb-na,n1=rb-ra,total=n0+n1+(lb-la);if(!total)return;bool edge=p==TARGET_W-1;for(uint32_t k=blockIdx.y;k<total;k+=gridDim.y){uint32_t kind,qi;BucketOrbitOp op;uint8_t hi;if(k<n0){kind=CPU_ORBIT_NN;qi=na+k;op=D_RS18_HIGH_NN[qi];hi=D_RS18_HIGH_NN_HI[qi];}else if(k<n0+n1){kind=CPU_ORBIT_NR;qi=ra+k-n0;op=D_RS18_HIGH_NR[qi];hi=D_RS18_HIGH_NR_HI[qi];}else{kind=CPU_ORBIT_NL;qi=la+k-n0-n1;op=D_RS18_HIGH_NL[qi];hi=D_RS18_HIGH_NL_HI[qi];}uint32_t sl=bkf_orbit_src(op),jl=bkf_orbit_partner(op),dl=bkf_orbit_drop(op),ss=bkf_loc_owner(sl),js=bkf_loc_owner(jl),ds=bkf_loc_owner(dl);BucketPhysicalBlock xb=bkf_high_main(ss,bid),jb=bkf_high_main(js,rs18_high_jblock(bid,xb,p,kind)),db=bkf_high_block(ds,uint32_t(xb.hs));uint32_t dbid=edge?bid:uint32_t(xb.hs),rid=rs18_rid(rs18_code(op,hi),D_RBF_HIGH_OFF,size_t(pi)*D_RBF_HIGH_PITCH+dbid);for(uint32_t lr=uint32_t(blockIdx.x)*blockDim.x+threadIdx.x;lr<xb.cols;lr+=uint32_t(gridDim.x)*blockDim.x){Count*ip=bkf_ptr(ss,xb.off+Code(bkf_loc_rank(sl))*xb.cols+lr),*jp=bkf_ptr(js,jb.off+Code(bkf_loc_rank(jl))*jb.cols+lr),*dp=bkf_ptr(ds,db.off+Code(bkf_loc_rank(dl))*db.cols+lr);Count c=*ip,old=*dp,extra=bkoc_r_high_extra(rid,edge?xb:db,lr);if(kind==CPU_ORBIT_NN){*jp=gpu_direct_add(*jp,c);*ip=gpu_direct_add(gpu_direct_add(c,old),edge?extra:0);*dp=edge?0:extra;}else{Count cc=*jp;*ip=gpu_direct_add(gpu_direct_add(c,cc),old);if(edge){*jp=gpu_direct_add(c,cc);*dp=0;}else *dp=gpu_direct_add(c,extra);}}}}

static void bucket_launch_reverse_low_split18(const StorageLayout&layout,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=1;p<=LOW_LUT_K;++p){bucket_reverse_low_split18_kernel<<<grid,block>>>(p);ck(cudaGetLastError(),"bucket reverse low split18");}}
static void bucket_launch_reverse_high_split18(const StorageLayout&layout,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=LOW_LUT_K+1;p<TARGET_W;++p){bucket_reverse_high_split18_kernel<<<grid,block>>>(p);ck(cudaGetLastError(),"bucket reverse high split18");}}
