#pragma once

#include "ramstream32_bucket_onepass_inline8.hpp"
#include "ramstream32_bucket_orbit_closure_packed18.cuh"
#include "ramstream32_bucket_reverse_split18.cuh"

#include <cstdint>

__constant__ BucketOnePassInline8Rec *D_OP8I_F_LOW_REC,*D_OP8I_F_HIGH_REC,*D_OP8I_R_LOW_REC,*D_OP8I_R_HIGH_REC;
__constant__ uint32_t *D_OP8I_F_LOW_SRC,*D_OP8I_F_HIGH_SRC,*D_OP8I_R_LOW_SRC,*D_OP8I_R_HIGH_SRC;

struct BucketForwardOnePassInline8DeviceTables{
    BucketOnePassInline8Rec *low_rec=nullptr,*high_rec=nullptr;uint32_t *low_src=nullptr,*high_src=nullptr;
    template<class T>static void cp(T*&d,const std::vector<T>&s,const char*w){if(s.empty())return;ck(cudaMalloc(&d,s.size()*sizeof(T)),w);ck(cudaMemcpy(d,s.data(),s.size()*sizeof(T),cudaMemcpyHostToDevice),w);}
    void install(const BucketForwardOnePassInline8Host&h){cp(low_rec,h.low.rec,"op8i f low rec");cp(high_rec,h.high.rec,"op8i f high rec");cp(low_src,h.low.src,"op8i f low src");cp(high_src,h.high.src,"op8i f high src");ck(cudaMemcpyToSymbol(D_OP8I_F_LOW_REC,&low_rec,sizeof(low_rec)),"op8i f low rec ptr");ck(cudaMemcpyToSymbol(D_OP8I_F_HIGH_REC,&high_rec,sizeof(high_rec)),"op8i f high rec ptr");ck(cudaMemcpyToSymbol(D_OP8I_F_LOW_SRC,&low_src,sizeof(low_src)),"op8i f low src ptr");ck(cudaMemcpyToSymbol(D_OP8I_F_HIGH_SRC,&high_src,sizeof(high_src)),"op8i f high src ptr");}
    void release(){cudaFree(low_rec);cudaFree(high_rec);cudaFree(low_src);cudaFree(high_src);low_rec=high_rec=nullptr;low_src=high_src=nullptr;}
};
struct BucketReverseOnePassInline8DeviceTables{
    BucketOnePassInline8Rec *low_rec=nullptr,*high_rec=nullptr;uint32_t *low_src=nullptr,*high_src=nullptr;
    template<class T>static void cp(T*&d,const std::vector<T>&s,const char*w){if(s.empty())return;ck(cudaMalloc(&d,s.size()*sizeof(T)),w);ck(cudaMemcpy(d,s.data(),s.size()*sizeof(T),cudaMemcpyHostToDevice),w);}
    void install(const BucketReverseOnePassInline8Host&h){cp(low_rec,h.low.rec,"op8i r low rec");cp(high_rec,h.high.rec,"op8i r high rec");cp(low_src,h.low.src,"op8i r low src");cp(high_src,h.high.src,"op8i r high src");ck(cudaMemcpyToSymbol(D_OP8I_R_LOW_REC,&low_rec,sizeof(low_rec)),"op8i r low rec ptr");ck(cudaMemcpyToSymbol(D_OP8I_R_HIGH_REC,&high_rec,sizeof(high_rec)),"op8i r high rec ptr");ck(cudaMemcpyToSymbol(D_OP8I_R_LOW_SRC,&low_src,sizeof(low_src)),"op8i r low src ptr");ck(cudaMemcpyToSymbol(D_OP8I_R_HIGH_SRC,&high_src,sizeof(high_src)),"op8i r high src ptr");}
    void release(){cudaFree(low_rec);cudaFree(high_rec);cudaFree(low_src);cudaFree(high_src);low_rec=high_rec=nullptr;low_src=high_src=nullptr;}
};

__device__ __forceinline__ Count op8i_f_low_extra(uint32_t rid,const BucketPhysicalBlock&db,uint32_t hr){
    if(rid==BKOC_NONE)return 0;BucketOnePassInline8Rec r=D_OP8I_F_LOW_REC[rid];uint32_t lc=op8i_lc(r),cc=op8i_cc(r),begin=op8i_begin(r),inl=op8i_inline(r),lres=lc-(lc!=0),cres=cc-(lc==0);uint32_t dc=0;if(cc)dc=D_BKF_HIGH_CODES[D_BKF_HIGH_CODE_OFF[size_t(D_BKF_FIXED_OWNER)*D_BKF_CODE_PITCH+db.he]+hr];
#if GPU_DIRECT_PM_ACCUM
    uint64_t sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_low_main(ss,bkf_src_block(x));sum+=uint64_t(bkf_ptr(ss,sb.off+Code(hr)*sb.cols+bkf_loc_rank(sl))[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_low_main(bkf_loc_owner(sl),bkf_src_block(x));sum+=bkf_sum_high_preimages_u64(dc,bkf_cross_depth(x),sb.he,bkf_src_block(x),sl);};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_F_LOW_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_F_LOW_SRC[begin+lres+i]);return gpu_direct_pm_reduce_u64(sum);
#else
    Count sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_low_main(ss,bkf_src_block(x));sum=gpu_direct_add(sum,bkf_ptr(ss,sb.off+Code(hr)*sb.cols+bkf_loc_rank(sl))[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_low_main(bkf_loc_owner(sl),bkf_src_block(x));sum=gpu_direct_add(sum,bkf_sum_high_preimages(dc,bkf_cross_depth(x),sb.he,bkf_src_block(x),sl));};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_F_LOW_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_F_LOW_SRC[begin+lres+i]);return sum;
#endif
}
__device__ __forceinline__ Count op8i_f_high_extra(uint32_t rid,const BucketPhysicalBlock&db,uint32_t lr){
    if(rid==BKOC_NONE)return 0;BucketOnePassInline8Rec r=D_OP8I_F_HIGH_REC[rid];uint32_t lc=op8i_lc(r),cc=op8i_cc(r),begin=op8i_begin(r),inl=op8i_inline(r),lres=lc-(lc!=0),cres=cc-(lc==0);uint32_t dc=0;if(cc)dc=D_BKF_LOW_CODES[D_BKF_LOW_CODE_OFF[size_t(D_BKF_FIXED_OWNER)*D_BKF_CODE_PITCH+db.hs]+lr];
#if GPU_DIRECT_PM_ACCUM
    uint64_t sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_high_main(ss,bkf_src_block(x));sum+=uint64_t(bkf_ptr(ss,sb.off+Code(bkf_loc_rank(sl))*sb.cols+lr)[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_high_main(bkf_loc_owner(sl),bkf_src_block(x));sum+=bkf_sum_low_preimages_u64(dc,bkf_cross_depth(x),sb.hs,bkf_src_block(x),sl);};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_F_HIGH_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_F_HIGH_SRC[begin+lres+i]);return gpu_direct_pm_reduce_u64(sum);
#else
    Count sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_high_main(ss,bkf_src_block(x));sum=gpu_direct_add(sum,bkf_ptr(ss,sb.off+Code(bkf_loc_rank(sl))*sb.cols+lr)[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_high_main(bkf_loc_owner(sl),bkf_src_block(x));sum=gpu_direct_add(sum,bkf_sum_low_preimages(dc,bkf_cross_depth(x),sb.hs,bkf_src_block(x),sl));};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_F_HIGH_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_F_HIGH_SRC[begin+lres+i]);return sum;
#endif
}
__device__ __forceinline__ Count op8i_r_low_extra(uint32_t rid,const BucketPhysicalBlock&db,uint32_t hr){
    if(rid==BKOC_NONE)return 0;BucketOnePassInline8Rec r=D_OP8I_R_LOW_REC[rid];uint32_t lc=op8i_lc(r),cc=op8i_cc(r),begin=op8i_begin(r),inl=op8i_inline(r),lres=lc-(lc!=0),cres=cc-(lc==0);uint32_t dc=0;if(cc)dc=D_BKF_HIGH_CODES[D_BKF_HIGH_CODE_OFF[size_t(D_BKF_FIXED_OWNER)*D_BKF_CODE_PITCH+db.he]+hr];
#if GPU_DIRECT_PM_ACCUM
    uint64_t sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_low_main(ss,bkf_src_block(x));sum+=uint64_t(bkf_ptr(ss,sb.off+Code(hr)*sb.cols+bkf_loc_rank(sl))[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_low_main(bkf_loc_owner(sl),bkf_src_block(x));sum+=bkf_sum_high_preimages_u64(dc,bkf_cross_depth(x),sb.he,bkf_src_block(x),sl);};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_R_LOW_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_R_LOW_SRC[begin+lres+i]);return gpu_direct_pm_reduce_u64(sum);
#else
    Count sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_low_main(ss,bkf_src_block(x));sum=gpu_direct_add(sum,bkf_ptr(ss,sb.off+Code(hr)*sb.cols+bkf_loc_rank(sl))[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_low_main(bkf_loc_owner(sl),bkf_src_block(x));sum=gpu_direct_add(sum,bkf_sum_high_preimages(dc,bkf_cross_depth(x),sb.he,bkf_src_block(x),sl));};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_R_LOW_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_R_LOW_SRC[begin+lres+i]);return sum;
#endif
}
__device__ __forceinline__ Count op8i_r_high_extra(uint32_t rid,const BucketPhysicalBlock&db,uint32_t lr){
    if(rid==BKOC_NONE)return 0;BucketOnePassInline8Rec r=D_OP8I_R_HIGH_REC[rid];uint32_t lc=op8i_lc(r),cc=op8i_cc(r),begin=op8i_begin(r),inl=op8i_inline(r),lres=lc-(lc!=0),cres=cc-(lc==0);uint32_t dc=0;if(cc)dc=D_BKF_LOW_CODES[D_BKF_LOW_CODE_OFF[size_t(D_BKF_FIXED_OWNER)*D_BKF_CODE_PITCH+db.hs]+lr];
#if GPU_DIRECT_PM_ACCUM
    uint64_t sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_high_main(ss,bkf_src_block(x));sum+=uint64_t(bkf_ptr(ss,sb.off+Code(bkf_loc_rank(sl))*sb.cols+lr)[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_high_main(bkf_loc_owner(sl),bkf_src_block(x));sum+=bkf_sum_low_preimages_u64(dc,bkf_cross_depth(x),sb.hs,bkf_src_block(x),sl);};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_R_HIGH_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_R_HIGH_SRC[begin+lres+i]);return gpu_direct_pm_reduce_u64(sum);
#else
    Count sum=0;auto addl=[&](uint32_t x){uint32_t sl=bkf_src_locator(x),ss=bkf_loc_owner(sl);BucketPhysicalBlock sb=bkf_high_main(ss,bkf_src_block(x));sum=gpu_direct_add(sum,bkf_ptr(ss,sb.off+Code(bkf_loc_rank(sl))*sb.cols+lr)[0]);};auto addx=[&](uint32_t x){uint32_t sl=bkf_src_locator(x);BucketPhysicalBlock sb=bkf_high_main(bkf_loc_owner(sl),bkf_src_block(x));sum=gpu_direct_add(sum,bkf_sum_low_preimages(dc,bkf_cross_depth(x),sb.hs,bkf_src_block(x),sl));};if(lc)addl(inl);else addx(inl);for(uint32_t i=0;i<lres;++i)addl(D_OP8I_R_HIGH_SRC[begin+i]);for(uint32_t i=0;i<cres;++i)addx(D_OP8I_R_HIGH_SRC[begin+lres+i]);return sum;
#endif
}

__global__ void bucket_low_orbit_closure18_inline8_kernel(int p){uint32_t bid=blockIdx.z;if(bid>=D_BKF_MAIN_NBLOCKS)return;uint32_t pi=uint32_t(LOW_LUT_K-p);size_t oi=size_t(pi)*D_BKF_LOW_PITCH+bid;uint32_t na=D_BKF_LOW_NN_OFF[oi],nb=D_BKF_LOW_NN_OFF[oi+1],ra=D_BKF_LOW_NR_OFF[oi],rb=D_BKF_LOW_NR_OFF[oi+1],la=D_BKF_LOW_NL_OFF[oi],lb=D_BKF_LOW_NL_OFF[oi+1],n0=nb-na,n1=rb-ra,total=n0+n1+(lb-la);if(!total)return;for(uint32_t k=uint32_t(blockIdx.x)*blockDim.x+threadIdx.x;k<total;k+=uint32_t(gridDim.x)*blockDim.x){uint32_t kind;uint8_t hi;BucketOrbitOp op;if(k<n0){kind=CPU_ORBIT_NN;op=D_BKF_LOW_NN[na+k];hi=D_BKOC18_F_LOW_NN[na+k];}else if(k<n0+n1){kind=CPU_ORBIT_NR;op=D_BKF_LOW_NR[ra+k-n0];hi=D_BKOC18_F_LOW_NR[ra+k-n0];}else{kind=CPU_ORBIT_NL;op=D_BKF_LOW_NL[la+k-n0-n1];hi=D_BKOC18_F_LOW_NL[la+k-n0-n1];}uint32_t sl=bkf_orbit_src(op),jl=bkf_orbit_partner(op),dl=bkf_orbit_drop(op),ss=bkf_loc_owner(sl),js=bkf_loc_owner(jl),ds=bkf_loc_owner(dl);BucketPhysicalBlock xb=bkf_low_main(ss,bid);if(!xb.valid||!xb.rows||!xb.cols)continue;uint32_t jbid=bid;if(p==LOW_LUT_K){uint32_t center=kind==CPU_ORBIT_NR?uint32_t(R):uint32_t(::L);jbid=3u*uint32_t(xb.he)+center;}BucketPhysicalBlock jb=bkf_low_main(js,jbid),db=bkf_low_block(ds,uint32_t(xb.he));uint32_t dbid=p==1?bid:uint32_t(xb.he),rid=bkoc18_rid(bkoc18_forward_code(op,hi),D_BKF_LOW_OFF,size_t(pi)*D_BKF_LOW_FUSED_PITCH+dbid),sr=bkf_loc_rank(sl),jr=bkf_loc_rank(jl),dr=bkf_loc_rank(dl);for(uint32_t hr=blockIdx.y;hr<xb.rows;hr+=gridDim.y){Count*ip=bkf_ptr(ss,xb.off+Code(hr)*xb.cols+sr),*jp=bkf_ptr(js,jb.off+Code(hr)*jb.cols+jr),*dp=bkf_ptr(ds,db.off+Code(hr)*db.cols+dr);Count c=*ip,old=*dp,extra=op8i_f_low_extra(rid,p==1?xb:db,hr);if(kind==CPU_ORBIT_NN){*jp=gpu_direct_add(*jp,c);*ip=gpu_direct_add(gpu_direct_add(c,old),p==1?extra:0);*dp=p==1?0:extra;}else{Count cc=*jp,all=gpu_direct_add(gpu_direct_add(c,cc),old);if(p==1){*ip=all;*jp=gpu_direct_add(c,cc);*dp=0;}else{*ip=all;*dp=gpu_direct_add(c,extra);}}}}}
__global__ void bucket_high_orbit_closure18_inline8_kernel(int p){uint32_t bid=blockIdx.z;if(bid>=D_BKF_MAIN_NBLOCKS)return;uint32_t pi=uint32_t((TARGET_W-1)-p);size_t oi=size_t(pi)*D_BKF_HIGH_PITCH+bid;uint32_t na=D_BKF_HIGH_NN_OFF[oi],nb=D_BKF_HIGH_NN_OFF[oi+1],ra=D_BKF_HIGH_NRNL_OFF[oi],rb=D_BKF_HIGH_NRNL_OFF[oi+1],n0=nb-na,total=n0+(rb-ra);if(!total)return;for(uint32_t k=blockIdx.y;k<total;k+=gridDim.y){bool nn=k<n0;uint32_t qi=nn?na+k:ra+k-n0;BucketOrbitOp op=nn?D_BKF_HIGH_NN[qi]:D_BKF_HIGH_NRNL[qi];uint8_t hi=nn?D_BKOC18_F_HIGH_NN[qi]:D_BKOC18_F_HIGH_NRNL[qi];uint32_t sl=bkf_orbit_src(op),jl=bkf_orbit_partner(op),dl=bkf_orbit_drop(op),ss=bkf_loc_owner(sl),js=bkf_loc_owner(jl),ds=bkf_loc_owner(dl);BucketPhysicalBlock xb=bkf_high_main(ss,bid);if(!xb.valid||!xb.rows||!xb.cols)continue;uint32_t jbid=bid;if(p==LOW_LUT_K+1){uint32_t center=nn?uint32_t(R):uint32_t(N);int he=int(xb.hs)+(center==uint32_t(R)?1:0);jbid=uint32_t(3*he+int(center));}BucketPhysicalBlock jb=bkf_high_main(js,jbid),db=bkf_high_block(ds,uint32_t(xb.hs));uint32_t dbid=uint32_t(xb.hs),rid=bkoc18_rid(bkoc18_forward_code(op,hi),D_BKF_HIGH_OFF,size_t(pi)*D_BKF_HIGH_FUSED_PITCH+dbid),sr=bkf_loc_rank(sl),jr=bkf_loc_rank(jl),dr=bkf_loc_rank(dl);for(uint32_t lr=uint32_t(blockIdx.x)*blockDim.x+threadIdx.x;lr<xb.cols;lr+=uint32_t(gridDim.x)*blockDim.x){Count*ip=bkf_ptr(ss,xb.off+Code(sr)*xb.cols+lr),*jp=bkf_ptr(js,jb.off+Code(jr)*jb.cols+lr),*dp=bkf_ptr(ds,db.off+Code(dr)*db.cols+lr);Count c=*ip,old=*dp,extra=op8i_f_high_extra(rid,db,lr);if(nn){*jp=gpu_direct_add(*jp,c);*ip=gpu_direct_add(c,old);*dp=extra;}else{Count cc=*jp;*ip=gpu_direct_add(gpu_direct_add(c,cc),old);*dp=gpu_direct_add(c,extra);}}}}
__global__ void bucket_reverse_low_split18_inline8_kernel(int p){uint32_t bid=blockIdx.z;if(bid>=D_BKF_MAIN_NBLOCKS)return;uint32_t pi=uint32_t(p-1);size_t oi=size_t(pi)*D_RS18_PITCH+bid;uint32_t na=D_RS18_LOW_NN_OFF[oi],nb=D_RS18_LOW_NN_OFF[oi+1],ra=D_RS18_LOW_NR_OFF[oi],rb=D_RS18_LOW_NR_OFF[oi+1],la=D_RS18_LOW_NL_OFF[oi],lb=D_RS18_LOW_NL_OFF[oi+1],n0=nb-na,n1=rb-ra,total=n0+n1+(lb-la);if(!total)return;for(uint32_t k=uint32_t(blockIdx.x)*blockDim.x+threadIdx.x;k<total;k+=uint32_t(gridDim.x)*blockDim.x){uint32_t kind,qi;BucketOrbitOp op;uint8_t hi;if(k<n0){kind=CPU_ORBIT_NN;qi=na+k;op=D_RS18_LOW_NN[qi];hi=D_RS18_LOW_NN_HI[qi];}else if(k<n0+n1){kind=CPU_ORBIT_NR;qi=ra+k-n0;op=D_RS18_LOW_NR[qi];hi=D_RS18_LOW_NR_HI[qi];}else{kind=CPU_ORBIT_NL;qi=la+k-n0-n1;op=D_RS18_LOW_NL[qi];hi=D_RS18_LOW_NL_HI[qi];}uint32_t sl=bkf_orbit_src(op),jl=bkf_orbit_partner(op),dl=bkf_orbit_drop(op),ss=bkf_loc_owner(sl),js=bkf_loc_owner(jl),ds=bkf_loc_owner(dl);BucketPhysicalBlock xb=bkf_low_main(ss,bid),jb=bkf_low_main(js,rs18_low_jblock(bid,xb,p,kind)),db=bkf_low_block(ds,uint32_t(xb.he));uint32_t rid=rs18_rid(rs18_code(op,hi),D_RBF_LOW_OFF,size_t(pi)*D_RBF_LOW_PITCH+uint32_t(xb.he));for(uint32_t hr=blockIdx.y;hr<xb.rows;hr+=gridDim.y){Count*ip=bkf_ptr(ss,xb.off+Code(hr)*xb.cols+bkf_loc_rank(sl)),*jp=bkf_ptr(js,jb.off+Code(hr)*jb.cols+bkf_loc_rank(jl)),*dp=bkf_ptr(ds,db.off+Code(hr)*db.cols+bkf_loc_rank(dl));Count c=*ip,old=*dp,extra=op8i_r_low_extra(rid,db,hr);if(kind==CPU_ORBIT_NN){*jp=gpu_direct_add(*jp,c);*ip=gpu_direct_add(c,old);*dp=extra;}else{Count cc=*jp;*ip=gpu_direct_add(gpu_direct_add(c,cc),old);*dp=gpu_direct_add(c,extra);}}}}
__global__ void bucket_reverse_high_split18_inline8_kernel(int p){uint32_t bid=blockIdx.z;if(bid>=D_BKF_MAIN_NBLOCKS)return;uint32_t pi=uint32_t(p-(LOW_LUT_K+1));size_t oi=size_t(pi)*D_RS18_PITCH+bid;uint32_t na=D_RS18_HIGH_NN_OFF[oi],nb=D_RS18_HIGH_NN_OFF[oi+1],ra=D_RS18_HIGH_NR_OFF[oi],rb=D_RS18_HIGH_NR_OFF[oi+1],la=D_RS18_HIGH_NL_OFF[oi],lb=D_RS18_HIGH_NL_OFF[oi+1],n0=nb-na,n1=rb-ra,total=n0+n1+(lb-la);if(!total)return;bool edge=p==TARGET_W-1;for(uint32_t k=blockIdx.y;k<total;k+=gridDim.y){uint32_t kind,qi;BucketOrbitOp op;uint8_t hi;if(k<n0){kind=CPU_ORBIT_NN;qi=na+k;op=D_RS18_HIGH_NN[qi];hi=D_RS18_HIGH_NN_HI[qi];}else if(k<n0+n1){kind=CPU_ORBIT_NR;qi=ra+k-n0;op=D_RS18_HIGH_NR[qi];hi=D_RS18_HIGH_NR_HI[qi];}else{kind=CPU_ORBIT_NL;qi=la+k-n0-n1;op=D_RS18_HIGH_NL[qi];hi=D_RS18_HIGH_NL_HI[qi];}uint32_t sl=bkf_orbit_src(op),jl=bkf_orbit_partner(op),dl=bkf_orbit_drop(op),ss=bkf_loc_owner(sl),js=bkf_loc_owner(jl),ds=bkf_loc_owner(dl);BucketPhysicalBlock xb=bkf_high_main(ss,bid),jb=bkf_high_main(js,rs18_high_jblock(bid,xb,p,kind)),db=bkf_high_block(ds,uint32_t(xb.hs));uint32_t dbid=edge?bid:uint32_t(xb.hs),rid=rs18_rid(rs18_code(op,hi),D_RBF_HIGH_OFF,size_t(pi)*D_RBF_HIGH_PITCH+dbid);for(uint32_t lr=uint32_t(blockIdx.x)*blockDim.x+threadIdx.x;lr<xb.cols;lr+=uint32_t(gridDim.x)*blockDim.x){Count*ip=bkf_ptr(ss,xb.off+Code(bkf_loc_rank(sl))*xb.cols+lr),*jp=bkf_ptr(js,jb.off+Code(bkf_loc_rank(jl))*jb.cols+lr),*dp=bkf_ptr(ds,db.off+Code(bkf_loc_rank(dl))*db.cols+lr);Count c=*ip,old=*dp,extra=op8i_r_high_extra(rid,edge?xb:db,lr);if(kind==CPU_ORBIT_NN){*jp=gpu_direct_add(*jp,c);*ip=gpu_direct_add(gpu_direct_add(c,old),edge?extra:0);*dp=edge?0:extra;}else{Count cc=*jp;*ip=gpu_direct_add(gpu_direct_add(c,cc),old);if(edge){*jp=gpu_direct_add(c,cc);*dp=0;}else *dp=gpu_direct_add(c,extra);}}}}

static void bucket_launch_low_orbit_closure18_inline8(const StorageLayout&layout,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=LOW_LUT_K;p>=1;--p){bucket_low_orbit_closure18_inline8_kernel<<<grid,block>>>(p);ck(cudaGetLastError(),"bucket low orbit closure18 inline8");}}
static void bucket_launch_high_orbit_closure18_inline8(const StorageLayout&layout,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=TARGET_W-1;p>=LOW_LUT_K+1;--p){bucket_high_orbit_closure18_inline8_kernel<<<grid,block>>>(p);ck(cudaGetLastError(),"bucket high orbit closure18 inline8");}}
static void bucket_launch_reverse_low_split18_inline8(const StorageLayout&layout,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=1;p<=LOW_LUT_K;++p){bucket_reverse_low_split18_inline8_kernel<<<grid,block>>>(p);ck(cudaGetLastError(),"bucket reverse low split18 inline8");}}
static void bucket_launch_reverse_high_split18_inline8(const StorageLayout&layout,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=LOW_LUT_K+1;p<TARGET_W;++p){bucket_reverse_high_split18_inline8_kernel<<<grid,block>>>(p);ck(cudaGetLastError(),"bucket reverse high split18 inline8");}}
static void bucket_enqueue_low_orbit_closure18_inline8(const StorageLayout&layout,cudaStream_t stream,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=LOW_LUT_K;p>=1;--p){bucket_low_orbit_closure18_inline8_kernel<<<grid,block,0,stream>>>(p);ck(cudaGetLastError(),"bucket low orbit closure18 inline8 stream");}}
static void bucket_enqueue_high_orbit_closure18_inline8(const StorageLayout&layout,cudaStream_t stream,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=TARGET_W-1;p>=LOW_LUT_K+1;--p){bucket_high_orbit_closure18_inline8_kernel<<<grid,block,0,stream>>>(p);ck(cudaGetLastError(),"bucket high orbit closure18 inline8 stream");}}
static void bucket_enqueue_reverse_low_split18_inline8(const StorageLayout&layout,cudaStream_t stream,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=1;p<=LOW_LUT_K;++p){bucket_reverse_low_split18_inline8_kernel<<<grid,block,0,stream>>>(p);ck(cudaGetLastError(),"bucket reverse low split18 inline8 stream");}}
static void bucket_enqueue_reverse_high_split18_inline8(const StorageLayout&layout,cudaStream_t stream,int threads=256,int gx=16,int gy=8){dim3 block(threads),grid(gx,gy,unsigned(layout.main_blocks.size()));for(int p=LOW_LUT_K+1;p<TARGET_W;++p){bucket_reverse_high_split18_inline8_kernel<<<grid,block,0,stream>>>(p);ck(cudaGetLastError(),"bucket reverse high split18 inline8 stream");}}
