#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#ifndef P10DC_SOURCE_KEY4
#define P10DC_SOURCE_KEY4 0
#endif
static_assert(P10DC_SOURCE_KEY4 == 0 || P10DC_SOURCE_KEY4 == 1,
              "P10DC_SOURCE_KEY4 must be 0 or 1");
#if P10DC_SOURCE_KEY4
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depthcode_sourcekey4.cuh"
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depthcode_resolved_graph.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketZeroTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#define BucketFusedDeviceTables BucketFusedZeroClosureTables
#define BucketForwardOrbitClosureAttachHost BucketForwardPattern10DepthCodeHost
#define BucketReverseOrbitClosureAttachHost BucketReversePattern10DepthCodeHost
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardPattern10DepthCodeDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReversePattern10DepthCodeDeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_pattern10_depthcode_placeholder
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_pattern10_depthcode_zero_checked
#define BucketOnePassGraphs BucketPattern10DepthCodeResolvedGraphs
#define bucket_onepass_graph_sync_devices bucket_pattern10_depthcode_resolved_graph_sync_devices

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_graph_batch.cu"
