#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depth8_lut.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketZeroTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#define BucketFusedDeviceTables BucketFusedZeroClosureTables
#define BucketForwardOrbitClosureAttachHost BucketForwardPattern10Depth8LutHost
#define BucketReverseOrbitClosureAttachHost BucketReversePattern10Depth8Host
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardPattern10Depth8LutDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReversePattern10Depth8DeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_pattern10_depth8_lut_zero
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_pattern10_depth8_zero_checked
#define bucket_launch_low_orbit_closure_fused bucket_launch_low_orbit_closure_pattern10_depth8
#define bucket_launch_high_orbit_closure_fused bucket_launch_high_orbit_closure_pattern10_depth8
#define bucket_launch_reverse_low_orbit_closure_fused bucket_launch_reverse_low_pattern10_depth8
#define bucket_launch_reverse_high_orbit_closure_fused bucket_launch_reverse_high_pattern10_depth8

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_batch.cu"
