// v0.56 experiment: v0.55 CUDA Graph + compact ranges with runtime scheduling
// knobs.  This lets one B300 binary sweep LOW CTA granularity without rebuilds:
//   ONEESAN_LOW_TARGET_TASKS_PER_CTA=16384..1048576
//   ONEESAN_LOW_MAX_REPLICAS=1..65535
// Defaults preserve v0.55's 65,536 target / 1024 replica cap.
#define MASKSHARD_LOW_MASKBATCH_RESIDENT_ROWS 1
#define MASKSHARD_LOW_MASKBATCH_CTA_CONFIG_CACHE 1
#define MASKSHARD_LOW_MASKBATCH_REBUILD_DYNAMIC 1
#define MASKSHARD_LOW_MASKBATCH_FAST_REBUILD_SETUP 1
#define MASKSHARD_LOW_MASKBATCH_TARGET_TASKS_PER_CTA 65536
#define MASKSHARD_LOW_MASKBATCH_MAX_REPLICAS 1024
#define MASKSHARD_LOW_MASKBATCH_COMPACT_RANGES 1
#define MASKSHARD_LOW_MASKBATCH_CUDA_GRAPH 1
#define MASKSHARD_LOW_MASKBATCH_RUNTIME_TUNING 1
#include "oneesan_b300_maskshard_v043_lowmaskbatch.cu"
