#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif

#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depthcode_orbitcta_delta_direct_affine_rankformula_nometa4_abstract_graph.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"
#if P10DC_RANKFORMULA_DIRECTGATHER64
#if P10DC_RANKFORMULA_DIRECTGATHER_SPARSE64
#include "../gridfp/ramstream32_bucket_low_rankformula_directgather_sparse64.cuh"
#else
#include "../gridfp/ramstream32_bucket_low_rankformula_directgather64.cuh"
#endif
#else
#include "../gridfp/ramstream32_bucket_low_rankformula_nometa_directmap_depthmajor.cuh"
#endif

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketZeroTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#if P10DC_RANKFORMULA_DIRECTGATHER64
#if P10DC_RANKFORMULA_DIRECTGATHER_SPARSE64
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankFormulaNometa4DirectGatherSparse64Tables
#else
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankFormulaNometa4DirectGather64Tables
#endif
#else
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankFormulaNometa4DirectMapDepthMajorTables
#endif
#define BucketForwardOrbitClosureAttachHost BucketForwardPattern10DepthCodeHost
#define BucketReverseOrbitClosureAttachHost BucketReversePattern10DepthCodeHost
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardPattern10DepthCodeDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReversePattern10DepthCodeDeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_pattern10_depthcode_placeholder
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_pattern10_depthcode_zero_checked
#define BucketOnePassGraphs BucketPattern10DepthCodeOrbitCtaDirectAffineRankFormulaNometa4AbstractGraphs
#define bucket_onepass_graph_sync_devices bucket_pattern10_depthcode_orbitcta_rankformula_nometa4_abstract_graph_sync_devices

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_graph_batch.cu"
