#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_onepass_rec8_hybrid18_alias.cuh"
#include "../gridfp/ramstream32_bucket_orbit_closure_rec8_hybrid18_graph.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketRec8OffsetTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#define BucketFusedDeviceTables BucketFusedHybrid18Rec8Tables
#define BucketForwardOrbitClosureAttachHost BucketForwardHybrid18Rec8Host
#define BucketReverseOrbitClosureAttachHost BucketReverseHybrid18Rec8Host
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardHybrid18Rec8DeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReverseHybrid18Rec8DeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_hybrid18_rec8
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_hybrid18_rec8_checked
#define BucketOnePassGraphs BucketHybrid18Rec8Graphs
#define bucket_onepass_graph_sync_devices bucket_hybrid18_rec8_graph_sync_devices

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_graph_batch.cu"
