#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_onepass_inverse_hybrid18_alias.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketInverseOffsetTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#define BucketFusedDeviceTables BucketFusedHybrid18InverseTables
#define BucketForwardOrbitClosureAttachHost BucketForwardHybrid18InverseHost
#define BucketReverseOrbitClosureAttachHost BucketReverseHybrid18InverseHost
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardHybrid18InverseDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReverseHybrid18InverseDeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_hybrid18_inverse
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_hybrid18_inverse_checked
#define bucket_launch_low_orbit_closure_fused bucket_launch_low_orbit_closure18_inverse
#define bucket_launch_high_orbit_closure_fused bucket_launch_high_orbit_closure18_inverse
#define bucket_launch_reverse_low_orbit_closure_fused bucket_launch_reverse_low_split18_inverse
#define bucket_launch_reverse_high_orbit_closure_fused bucket_launch_reverse_high_split18_inverse

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass.cu"
