#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_compact16_alias.cuh"

#define BucketForwardOrbitClosureAttachHost BucketForwardOrbitClosureAttach16Host
#define BucketReverseOrbitClosureAttachHost BucketReverseOrbitClosureAttach16Host
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardOrbitClosureAttach16DeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReverseOrbitClosureAttach16DeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_orbit_closure_attach16_direct
#define build_bucket_reverse_orbit_closure_attach build_bucket_reverse_orbit_closure_attach16_direct
#define bucket_launch_low_orbit_closure_fused bucket_launch_low_orbit_closure16
#define bucket_launch_high_orbit_closure_fused bucket_launch_high_orbit_closure16
#define bucket_launch_reverse_low_orbit_closure_fused bucket_launch_reverse_low_orbit_closure16
#define bucket_launch_reverse_high_orbit_closure_fused bucket_launch_reverse_high_orbit_closure16

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass.cu"
