#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_onepass_inline8_hybrid18_alias.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketInline8OffsetTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#define BucketFusedDeviceTables BucketFusedHybrid18Inline8Tables
#define BucketForwardOrbitClosureAttachHost BucketForwardHybrid18Inline8Host
#define BucketReverseOrbitClosureAttachHost BucketReverseHybrid18Inline8Host
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardHybrid18Inline8DeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReverseHybrid18Inline8DeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_hybrid18_inline8
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_hybrid18_inline8_checked
#define bucket_launch_low_orbit_closure_fused bucket_launch_low_orbit_closure18_inline8
#define bucket_launch_high_orbit_closure_fused bucket_launch_high_orbit_closure18_inline8
#define bucket_launch_reverse_low_orbit_closure_fused bucket_launch_reverse_low_split18_inline8
#define bucket_launch_reverse_high_orbit_closure_fused bucket_launch_reverse_high_split18_inline8

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_batch.cu"
