#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_packed18.cuh"

#define BucketForwardOrbitClosureAttachHost BucketForwardOrbitClosureAttach18Host
#define BucketReverseOrbitClosureAttachHost BucketReverseOrbitClosureAttach18Host
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardOrbitClosureAttach18DeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReverseOrbitClosureAttach18DeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_orbit_closure_attach18
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_orbit_closure_attach18_checked
#define bucket_launch_low_orbit_closure_fused bucket_launch_low_orbit_closure18
#define bucket_launch_high_orbit_closure_fused bucket_launch_high_orbit_closure18
#define bucket_launch_reverse_low_orbit_closure_fused bucket_launch_reverse_low_orbit_closure18
#define bucket_launch_reverse_high_orbit_closure_fused bucket_launch_reverse_high_orbit_closure18

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_batch.cu"
