#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depth4_lut.cuh"
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depth8_graph.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketZeroTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#define BucketFusedDeviceTables BucketFusedZeroClosureTables
#define BucketForwardOrbitClosureAttachHost BucketForwardPattern10Depth4LutHost
#define BucketReverseOrbitClosureAttachHost BucketReversePattern10Depth4Host
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardPattern10Depth4LutDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReversePattern10Depth4DeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_pattern10_depth4_lut_zero
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_pattern10_depth4_zero_checked
#define BucketOnePassGraphs BucketPattern10Depth8Graphs
#define bucket_onepass_graph_sync_devices bucket_pattern10_depth8_graph_sync_devices

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_graph_batch.cu"
