#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depthcode.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketZeroTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#define BucketFusedDeviceTables BucketFusedZeroClosureTables
#define BucketForwardOrbitClosureAttachHost BucketForwardPattern10DepthCodeHost
#define BucketReverseOrbitClosureAttachHost BucketReversePattern10DepthCodeHost
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardPattern10DepthCodeDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReversePattern10DepthCodeDeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_pattern10_depthcode_placeholder
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_pattern10_depthcode_zero_checked
#define bucket_launch_low_orbit_closure_fused bucket_launch_low_orbit_closure_pattern10_depthcode
#define bucket_launch_high_orbit_closure_fused bucket_launch_high_orbit_closure_pattern10_depthcode
#define bucket_launch_reverse_low_orbit_closure_fused bucket_launch_reverse_low_pattern10_depthcode
#define bucket_launch_reverse_high_orbit_closure_fused bucket_launch_reverse_high_pattern10_depthcode

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_batch.cu"
