#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depthcode_warpstriped_delta_direct_affine_rankformula_nometa4_abstract_graph.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"
#if P10DC_RANKFORMULA_NOMETA_DIRECTMAP
#if P10DC_RANKFORMULA_DIRECTGATHER_DEPTHMAJOR
#include "../gridfp/ramstream32_bucket_low_rankformula_nometa_directmap_depthmajor.cuh"
#else
#include "../gridfp/ramstream32_bucket_low_rankformula_nometa_directmap.cuh"
#endif
#endif

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketZeroTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#if P10DC_RANKFORMULA_NOMETA_DIRECTMAP
#if P10DC_RANKFORMULA_DIRECTGATHER_DEPTHMAJOR
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankFormulaNometa4DirectMapDepthMajorTables
#else
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankFormulaNometa4DirectMapTables
#endif
#else
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankFormulaNometa4Tables
#endif
#define BucketForwardOrbitClosureAttachHost BucketForwardPattern10DepthCodeHost
#define BucketReverseOrbitClosureAttachHost BucketReversePattern10DepthCodeHost
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardPattern10DepthCodeDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReversePattern10DepthCodeDeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_pattern10_depthcode_placeholder
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_pattern10_depthcode_zero_checked
#define BucketOnePassGraphs BucketPattern10DepthCodeWarpStripedDeltaDirectAffineRankFormulaNometa4AbstractGraphs
#define bucket_onepass_graph_sync_devices bucket_pattern10_depthcode_warpstriped_delta_direct_affine_rankformula_nometa4_abstract_graph_sync_devices

#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_graph_batch.cu"
