#ifndef BUCKET_SNAKE_REVERSE_FUSED
#define BUCKET_SNAKE_REVERSE_FUSED 1
#endif
#include "../gridfp/ramstream32_bucket_orbit_closure_pattern10_depthcode_warpstriped_delta_direct_affine_rankchunk32_cross5_graph.cuh"
#include "../gridfp/ramstream32_reverse_build_release.hpp"

#define BSN_REVERSE_FUSED_TABLES_TYPE ReverseBucketZeroTables
#define build_reverse_bucket_atomic build_reverse_bucket_atomic_release_inputs
#if P10DC_RANKCHUNK32_DIRECTMASK
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankChunk32DirectMaskTables
#else
#define BucketFusedDeviceTables BucketFusedDirectHighRowsRankChunk32Tables
#endif
#define BucketForwardOrbitClosureAttachHost BucketForwardPattern10DepthCodeHost
#define BucketReverseOrbitClosureAttachHost BucketReversePattern10DepthCodeHost
#define BucketForwardOrbitClosureAttachDeviceTables BucketForwardPattern10DepthCodeDeviceTables
#define BucketReverseOrbitClosureAttachDeviceTables BucketReversePattern10DepthCodeDeviceTables
#define build_bucket_forward_orbit_closure_attach build_bucket_forward_pattern10_depthcode_placeholder
#define build_bucket_reverse_orbit_closure_attach_checked build_bucket_reverse_pattern10_depthcode_zero_checked
#define BucketOnePassGraphs BucketPattern10DepthCodeWarpStripedDeltaDirectAffineRankChunk32Cross5Graphs
#define bucket_onepass_graph_sync_devices bucket_pattern10_depthcode_warpstriped_delta_direct_affine_rankchunk32_cross5_graph_sync_devices

#if P10DC_RANKCHUNK32_RANKMASK_PROFILE
#define BSN_GRAPH_BATCH_POST_RUN_HOOK() p10dc_rankchunk32_report_rankmask_profile_devices(BUCKET_NGPU)
#endif
#include "oneesan_cuda_gridfp_b300_bucket_snake_onepass_graph_batch.cu"
