#pragma once
#include <cublas_v2.h>
#include <cuda_runtime.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

namespace oneesan::row8tensor {
static constexpr int DIMS[9]={1107,1640,1428,888,420,152,42,8,1};
static constexpr int DELTA[3]={0,-1,1};
struct ModData{std::array<std::array<std::vector<uint32_t>,9>,3> trans;std::vector<uint32_t> alpha,beta;double build_s=0,inv_s=0,trans_s=0;};
struct HostMat{int k=0,n=0;std::vector<uint32_t>a;};
struct DevMat{int k=0,n=0,kp=0,np=0;std::array<int8_t*,4>b{};int32_t*cs=nullptr;};
struct Group{int h=0,rows=0,dim=0;uint32_t*d=nullptr;std::vector<uint32_t>code;};
struct Runtime{uint32_t mod=0;std::array<std::array<HostMat,9>,3>hm;std::array<std::array<DevMat,9>,3>fwd,rev;std::vector<uint32_t>alpha,beta;};
inline void cublas_ck(cublasStatus_t e,const char*w){if(e!=CUBLAS_STATUS_SUCCESS)throw std::runtime_error(std::string("row8 ")+w+" cublas="+std::to_string((int)e));}

inline DevMat upload_mat(const HostMat&m){DevMat d;d.k=m.k;d.n=m.n;d.kp=(m.k+15)&~15;d.np=(m.n+15)&~15;std::array<std::vector<int8_t>,4>b;std::vector<int32_t>cs((size_t)4*d.n);for(auto&x:b)x.assign((size_t)d.kp*d.np,0);for(int j=0;j<m.k;++j)for(int c=0;c<m.n;++c){uint32_t x=m.a[(size_t)j*m.n+c];for(int a=0;a<4;++a){int z=(x>>(8*a))&255;b[a][j+(size_t)d.kp*c]=(int8_t)(z-128);cs[(size_t)a*d.n+c]+=z;}}for(int a=0;a<4;++a){ck(cudaMalloc(&d.b[a],b[a].size()),"row8 mat alloc");ck(cudaMemcpy(d.b[a],b[a].data(),b[a].size(),cudaMemcpyHostToDevice),"row8 mat copy");}ck(cudaMalloc(&d.cs,cs.size()*4),"row8 colsum alloc");ck(cudaMemcpy(d.cs,cs.data(),cs.size()*4,cudaMemcpyHostToDevice),"row8 colsum copy");return d;}
inline HostMat transpose(const HostMat&m){HostMat t;t.k=m.n;t.n=m.k;t.a.resize((size_t)t.k*t.n);for(int i=0;i<m.k;++i)for(int j=0;j<m.n;++j)t.a[(size_t)j*t.n+i]=m.a[(size_t)i*m.n+j];return t;}
inline void free_mat(DevMat&d){for(auto&p:d.b)if(p)cudaFree(p);if(d.cs)cudaFree(d.cs);d={};}
inline Runtime make_runtime(const ModData&md,uint32_t mod){Runtime r;r.mod=mod;r.alpha=md.alpha;r.beta.assign(md.beta.begin(),md.beta.begin()+DIMS[0]);for(int s=0;s<3;++s)for(int h=0;h<9;++h){int h2=h+DELTA[s];if(h2<0||h2>=9)continue;auto&m=r.hm[s][h];m.k=DIMS[h];m.n=DIMS[h2];m.a=md.trans[s][h];r.fwd[s][h]=upload_mat(m);r.rev[s][h]=upload_mat(transpose(m));}return r;}
inline void destroy(Runtime&r){for(int s=0;s<3;++s)for(int h=0;h<9;++h){free_mat(r.fwd[s][h]);free_mat(r.rev[s][h]);}}

__global__ void pack_rows(const uint32_t*x,int m,int k,int kp,int8_t*a0,int8_t*a1,int8_t*a2,int8_t*a3,int32_t*rs){for(int r=blockIdx.x*blockDim.x+threadIdx.x;r<m;r+=gridDim.x*blockDim.x){int s0=0,s1=0,s2=0,s3=0;for(int j=0;j<k;++j){uint32_t v=x[(size_t)r*k+j];int z0=v&255,z1=(v>>8)&255,z2=(v>>16)&255,z3=(v>>24)&255;a0[j+(size_t)kp*r]=(int8_t)(z0-128);a1[j+(size_t)kp*r]=(int8_t)(z1-128);a2[j+(size_t)kp*r]=(int8_t)(z2-128);a3[j+(size_t)kp*r]=(int8_t)(z3-128);s0+=z0;s1+=z1;s2+=z2;s3+=z3;}rs[r]=s0;rs[(size_t)m+r]=s1;rs[(size_t)2*m+r]=s2;rs[(size_t)3*m+r]=s3;}}
__global__ void pack_rows_indexed(const uint32_t*x,const uint32_t*idx,int m,int k,int kp,int8_t*a0,int8_t*a1,int8_t*a2,int8_t*a3,int32_t*rs){for(int r=blockIdx.x*blockDim.x+threadIdx.x;r<m;r+=gridDim.x*blockDim.x){uint32_t rr=idx[r];int s0=0,s1=0,s2=0,s3=0;for(int j=0;j<k;++j){uint32_t v=x[(size_t)rr*k+j];int z0=v&255,z1=(v>>8)&255,z2=(v>>16)&255,z3=(v>>24)&255;a0[j+(size_t)kp*r]=(int8_t)(z0-128);a1[j+(size_t)kp*r]=(int8_t)(z1-128);a2[j+(size_t)kp*r]=(int8_t)(z2-128);a3[j+(size_t)kp*r]=(int8_t)(z3-128);s0+=z0;s1+=z1;s2+=z2;s3+=z3;}rs[r]=s0;rs[(size_t)m+r]=s1;rs[(size_t)2*m+r]=s2;rs[(size_t)3*m+r]=s3;}}
__global__ void accum_level(const int32_t*C,int ldc,int m,int n,const int32_t*rs,const int32_t*cs,unsigned long long*acc,int npairs,int k,int e,int reduce,uint32_t*out,int stride,int base,int write,uint32_t mod){for(unsigned long long q=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,st=(unsigned long long)gridDim.x*blockDim.x;q<(unsigned long long)m*n;q+=st){int r=q%m,c=q/m;long long ar=0,bc=0;for(int a=0;a<4;++a){int b=e-a;if(b>=0&&b<4){ar+=rs[(size_t)a*m+r];bc+=cs[(size_t)b*n+c];}}long long de=(long long)C[r+(size_t)ldc*c]+128LL*(ar+bc)-(long long)npairs*16384LL*k;unsigned long long x=acc[q]*256ULL+(unsigned long long)de;if(reduce)x%=mod;acc[q]=x;if(write)out[(size_t)(base+r)*stride+c]=(uint32_t)x;}}
__global__ void accum_scatter(const int32_t*C,int ldc,int m,int nt,const int32_t*rs,const int32_t*cs,int nfull,int c0,unsigned long long*acc,int npairs,int k,int e,int reduce,const unsigned long long*pb,const unsigned long long*sr,Count*full,int write,uint32_t mod,unsigned long long rankBase,unsigned long long rankLimit){for(unsigned long long q=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,st=(unsigned long long)gridDim.x*blockDim.x;q<(unsigned long long)m*nt;q+=st){int r=q%m,c=q/m;long long ar=0,bc=0;for(int a=0;a<4;++a){int b=e-a;if(b>=0&&b<4){ar+=rs[(size_t)a*m+r];bc+=cs[(size_t)b*nfull+c0+c];}}long long de=(long long)C[r+(size_t)ldc*c]+128LL*(ar+bc)-(long long)npairs*16384LL*k;unsigned long long x=acc[q]*256ULL+(unsigned long long)de;if(reduce)x%=mod;acc[q]=x;if(write){unsigned long long rank=pb[r]+sr[c0+c];if(rank>=rankBase&&rank<rankLimit)full[rank-rankBase]=Count(x);}}}
__global__ void accum_scatter_2d(const int32_t*C,int ldc,int m,int nt,const int32_t*rs,const int32_t*cs,int nfull,int c0,unsigned long long*acc,int npairs,int k,int e,int reduce,const unsigned long long*pb,const unsigned long long*sr,Count*full,int write,uint32_t mod,unsigned long long rankBase,unsigned long long rankLimit){
    int r=blockIdx.x*blockDim.x+threadIdx.x,c=blockIdx.y;if(r>=m||c>=nt)return;long long ar=0,bc=0;for(int a=0;a<4;++a){int b=e-a;if(b>=0&&b<4){ar+=rs[(size_t)a*m+r];bc+=cs[(size_t)b*nfull+c0+c];}}long long de=(long long)C[r+(size_t)ldc*c]+128LL*(ar+bc)-(long long)npairs*16384LL*k;size_t q=(size_t)c*m+r;unsigned long long x=acc[q]*256ULL+(unsigned long long)de;if(reduce)x%=mod;acc[q]=x;if(write){unsigned long long rank=pb[r]+sr[c0+c];if(rank>=rankBase&&rank<rankLimit)full[rank-rankBase]=Count(x);}
}
__global__ void accum_scatter_compare(const int32_t*C,int ldc,int m,int nt,const int32_t*rs,const int32_t*cs,int nfull,int c0,unsigned long long*acc,int npairs,int k,int e,int reduce,const unsigned long long*pb,const unsigned long long*sr,const Count*baseline,int write,uint32_t mod,unsigned long long rankBase,unsigned long long rankLimit,unsigned long long*mismatch){for(unsigned long long q=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,st=(unsigned long long)gridDim.x*blockDim.x;q<(unsigned long long)m*nt;q+=st){int r=q%m,c=q/m;long long ar=0,bc=0;for(int a=0;a<4;++a){int b=e-a;if(b>=0&&b<4){ar+=rs[(size_t)a*m+r];bc+=cs[(size_t)b*nfull+c0+c];}}long long de=(long long)C[r+(size_t)ldc*c]+128LL*(ar+bc)-(long long)npairs*16384LL*k;unsigned long long x=acc[q]*256ULL+(unsigned long long)de;if(reduce)x%=mod;acc[q]=x;if(write){unsigned long long rank=pb[r]+sr[c0+c];if(rank>=rankBase&&rank<rankLimit&&baseline[rank-rankBase]!=Count(x))atomicAdd(mismatch,1ULL);}}}

__global__ void accum_scatter_compare_2d(const int32_t*C,int ldc,int m,int nt,const int32_t*rs,const int32_t*cs,int nfull,int c0,unsigned long long*acc,int npairs,int k,int e,int reduce,const unsigned long long*pb,const unsigned long long*sr,const Count*baseline,int write,uint32_t mod,unsigned long long rankBase,unsigned long long rankLimit,unsigned long long*mismatch){
    int r=blockIdx.x*blockDim.x+threadIdx.x,c=blockIdx.y;if(r>=m||c>=nt)return;long long ar=0,bc=0;for(int a=0;a<4;++a){int b=e-a;if(b>=0&&b<4){ar+=rs[(size_t)a*m+r];bc+=cs[(size_t)b*nfull+c0+c];}}long long de=(long long)C[r+(size_t)ldc*c]+128LL*(ar+bc)-(long long)npairs*16384LL*k;size_t q=(size_t)c*m+r;unsigned long long x=acc[q]*256ULL+(unsigned long long)de;if(reduce)x%=mod;acc[q]=x;if(write){unsigned long long rank=pb[r]+sr[c0+c];if(rank>=rankBase&&rank<rankLimit&&baseline[rank-rankBase]!=Count(x))atomicAdd(mismatch,1ULL);}
}

struct Scratch{std::array<int8_t*,4>a{};size_t acap=0;int32_t*rs=nullptr;size_t rcap=0;int32_t*C=nullptr;size_t ccap=0;unsigned long long*acc=nullptr;size_t acccap=0;uint32_t*idx=nullptr;size_t idxcap=0;~Scratch(){for(auto p:a)if(p)cudaFree(p);if(rs)cudaFree(rs);if(C)cudaFree(C);if(acc)cudaFree(acc);if(idx)cudaFree(idx);}void ensure_a(size_t bytes,size_t rows){if(bytes>acap){for(auto&p:a){if(p)cudaFree(p);ck(cudaMalloc(&p,bytes),"row8 scratch A");}acap=bytes;}if(4*rows>rcap){if(rs)cudaFree(rs);ck(cudaMalloc(&rs,4*rows*4),"row8 scratch sums");rcap=4*rows;}}void ensure_out(size_t cn,size_t an){if(cn>ccap){if(C)cudaFree(C);ck(cudaMalloc(&C,cn*4),"row8 scratch C");ccap=cn;}if(an>acccap){if(acc)cudaFree(acc);ck(cudaMalloc(&acc,an*8),"row8 scratch acc");acccap=an;}}void ensure_idx(size_t n){if(n>idxcap){if(idx)cudaFree(idx);ck(cudaMalloc(&idx,n*sizeof(uint32_t)),"row8 scratch idx");idxcap=n;}}};
inline void prepare_a(Scratch&sc,const Group&g,int kp){int mp=(g.rows+15)&~15;size_t bytes=(size_t)kp*mp;sc.ensure_a(bytes,mp);for(auto p:sc.a)ck(cudaMemset(p,0,bytes),"row8 A zero");int blocks=std::min(65535,(g.rows+127)/128);pack_rows<<<std::max(1,blocks),128>>>(g.d,g.rows,g.dim,kp,sc.a[0],sc.a[1],sc.a[2],sc.a[3],sc.rs);ck(cudaGetLastError(),"row8 pack A");}
inline void prepare_a_indexed(Scratch&sc,const Group&g,const uint32_t*idx,int rows,int kp){int mp=(rows+15)&~15;size_t bytes=(size_t)kp*mp;sc.ensure_a(bytes,mp);for(auto p:sc.a)ck(cudaMemset(p,0,bytes),"row8 indexed A zero");int blocks=std::min(65535,(rows+127)/128);pack_rows_indexed<<<std::max(1,blocks),128>>>(g.d,idx,rows,g.dim,kp,sc.a[0],sc.a[1],sc.a[2],sc.a[3],sc.rs);ck(cudaGetLastError(),"row8 pack indexed A");}
inline void prepare_a_selected(Scratch&sc,const Group&g,const std::vector<uint32_t>&sel,int kp){if(sel.size()==size_t(g.rows)){prepare_a(sc,g,kp);return;}sc.ensure_idx(sel.size());ck(cudaMemcpy(sc.idx,sel.data(),sel.size()*sizeof(uint32_t),cudaMemcpyHostToDevice),"row8 selected idx copy");prepare_a_indexed(sc,g,sc.idx,int(sel.size()),kp);}
inline void gemm_level_rows(cublasHandle_t h,Scratch&sc,int rows,const DevMat&b,uint32_t*out,int base,uint32_t mod){int mp=(rows+15)&~15;sc.ensure_out((size_t)mp*b.np,(size_t)rows*b.n);ck(cudaMemset(sc.acc,0,(size_t)rows*b.n*8),"row8 level acc zero");for(int e=6;e>=0;--e){int pairs=0;bool first=true;int32_t one=1;for(int a=0;a<4;++a){int bb=e-a;if(bb<0||bb>=4)continue;++pairs;int32_t beta=first?0:1;cublas_ck(cublasGemmEx(h,CUBLAS_OP_T,CUBLAS_OP_N,mp,b.np,b.kp,&one,sc.a[a],CUDA_R_8I,b.kp,b.b[bb],CUDA_R_8I,b.kp,&beta,sc.C,CUDA_R_32I,mp,CUBLAS_COMPUTE_32I,CUBLAS_GEMM_DEFAULT_TENSOR_OP),"level gemm");first=false;}int blocks=std::min<unsigned long long>(65535,((unsigned long long)rows*b.n+255)/256);accum_level<<<std::max(1,blocks),256>>>(sc.C,mp,rows,b.n,sc.rs,b.cs,sc.acc,pairs,b.k,e,e==3||e==0,out,b.n,base,e==0,mod);ck(cudaGetLastError(),"row8 level accum");}}
inline void gemm_level(cublasHandle_t h,Scratch&sc,const Group&g,const DevMat&b,uint32_t*out,int base,uint32_t mod){gemm_level_rows(h,sc,g.rows,b,out,base,mod);}
inline Group base_group(const Runtime&r,bool suffix){Group g;g.h=suffix?0:1;g.rows=1;g.dim=DIMS[g.h];g.code={0};auto const&x=suffix?r.beta:r.alpha;ck(cudaMalloc(&g.d,x.size()*4),"row8 base");ck(cudaMemcpy(g.d,x.data(),x.size()*4,cudaMemcpyHostToDevice),"row8 base copy");return g;}
inline void free_groups(std::array<Group,9>&g){for(auto&x:g)if(x.d){cudaFree(x.d);x.d=nullptr;}}
inline std::array<Group,9> build_levels(cublasHandle_t handle,const Runtime&r,int len,bool suffix,double&seconds){std::array<Group,9>cur{};cur[suffix?0:1]=base_group(r,suffix);for(int h=0;h<9;++h){cur[h].h=h;cur[h].dim=DIMS[h];}Scratch sc;seconds=0;uint64_t p3=1;for(int lev=0;lev<len;++lev){auto t0=std::chrono::steady_clock::now();std::array<int,9>nr{};for(int h=0;h<9;++h)if(cur[h].rows)for(int s=0;s<3;++s){int h2=suffix?h-DELTA[s]:h+DELTA[s];if(0<=h2&&h2<9)nr[h2]+=cur[h].rows;}std::array<Group,9>nxt{};for(int h=0;h<9;++h){nxt[h].h=h;nxt[h].rows=nr[h];nxt[h].dim=DIMS[h];if(nr[h]){ck(cudaMalloc(&nxt[h].d,(size_t)nr[h]*DIMS[h]*4),"row8 next");nxt[h].code.reserve(nr[h]);}}std::array<int,9>off{};for(int h=0;h<9;++h)if(cur[h].rows){prepare_a(sc,cur[h],(cur[h].dim+15)&~15);for(int s=0;s<3;++s){int h2=suffix?h-DELTA[s]:h+DELTA[s];if(h2<0||h2>=9)continue;auto const&md=suffix?r.rev[s][h2]:r.fwd[s][h];gemm_level(handle,sc,cur[h],md,nxt[h2].d,off[h2],r.mod);for(uint32_t c:cur[h].code)nxt[h2].code.push_back(suffix?uint32_t(s*p3+c):uint32_t(c*3+s));off[h2]+=cur[h].rows;}}ck(cudaDeviceSynchronize(),"row8 level sync");free_groups(cur);cur=std::move(nxt);seconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();p3*=3;}return cur;}

struct PrefixPrunePlan{int len=0;std::vector<std::vector<uint8_t>>keep;std::vector<size_t>kept;};
inline std::array<Group,9> build_prefix_levels_pruned(cublasHandle_t handle,const Runtime&r,int len,const PrefixPrunePlan&plan,double&seconds){if(plan.len!=len||int(plan.keep.size())!=len+1)throw std::runtime_error("row8 prefix prune plan mismatch");std::array<Group,9>cur{};cur[1]=base_group(r,false);for(int h=0;h<9;++h){cur[h].h=h;cur[h].dim=DIMS[h];}Scratch sc;seconds=0;for(int lev=0;lev<len;++lev){auto t0=std::chrono::steady_clock::now();std::array<std::array<std::vector<uint32_t>,3>,9>sel;std::array<int,9>nr{};for(int h=0;h<9;++h)if(cur[h].rows){for(int i=0;i<cur[h].rows;++i){uint32_t c=cur[h].code[i];for(int sym=0;sym<3;++sym){int h2=h+DELTA[sym];if(h2<0||h2>=9)continue;uint32_t child=c*3u+uint32_t(sym);if(child<plan.keep[lev+1].size()&&plan.keep[lev+1][child]){sel[h][sym].push_back(uint32_t(i));++nr[h2];}}}}std::array<Group,9>nxt{};for(int h=0;h<9;++h){nxt[h].h=h;nxt[h].rows=nr[h];nxt[h].dim=DIMS[h];if(nr[h]){ck(cudaMalloc(&nxt[h].d,(size_t)nr[h]*DIMS[h]*4),"row8 pruned next");nxt[h].code.reserve(nr[h]);}}std::array<int,9>off{};for(int h=0;h<9;++h)if(cur[h].rows)for(int sym=0;sym<3;++sym){auto const&v=sel[h][sym];if(v.empty())continue;int h2=h+DELTA[sym];auto const&md=r.fwd[sym][h];prepare_a_selected(sc,cur[h],v,(cur[h].dim+15)&~15);gemm_level_rows(handle,sc,int(v.size()),md,nxt[h2].d,off[h2],r.mod);for(uint32_t i:v)nxt[h2].code.push_back(cur[h].code[i]*3u+uint32_t(sym));off[h2]+=int(v.size());}ck(cudaDeviceSynchronize(),"row8 pruned level sync");free_groups(cur);cur=std::move(nxt);seconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();if(const char*e=std::getenv("GRIDFP_ROW8_PROFILE_PREFIX_PRUNE");e&&std::atoi(e)){size_t rows=0,bytes=0;for(int h=0;h<9;++h){rows+=cur[h].rows;bytes+=size_t(cur[h].rows)*DIMS[h]*sizeof(Count);}std::cerr<<"row8 pruned prefix level="<<lev+1<<" rows="<<rows<<" mib="<<double(bytes)/(1<<20)<<" sec="<<std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count()<<"\n";}}return cur;}

inline unsigned long long prefix_base(uint32_t code,int len,int width){int d[32];for(int i=len-1;i>=0;--i){d[i]=code%3;code/=3;}Code rank=0;int h=1;for(int i=0;i<len;++i){int pos=width-1-i,v=d[i];if(v>0)rank+=H_DP[pos][h];if(v>1&&h>0)rank+=H_DP[pos][h-1];if(v==1)--h;else if(v==2)++h;}return rank;}
inline unsigned long long suffix_rank(uint32_t code,int len,int start_h){int d[32];for(int i=len-1;i>=0;--i){d[i]=code%3;code/=3;}Code rank=0;int h=start_h;for(int i=0;i<len;++i){int pos=len-1-i,v=d[i];if(v>0)rank+=H_DP[pos][h];if(v>1&&h>0)rank+=H_DP[pos][h-1];if(v==1)--h;else if(v==2)++h;}return rank;}

struct PrefixPlanSet{int W=0,plen=0,slen=0,ng=0;Code chunk=0;std::vector<Code>lens;std::vector<PrefixPrunePlan>plans;double build_s=0;};
inline PrefixPlanSet build_prefix_plan_set(int W,int plen,int slen,Code chunk,const std::vector<Code>&lens,int ng){auto t0=std::chrono::steady_clock::now();PrefixPlanSet z;z.W=W;z.plen=plen;z.slen=slen;z.ng=ng;z.chunk=chunk;z.lens=lens;z.plans.resize(ng);std::vector<uint32_t>p3(plen+1,1);for(int i=1;i<=plen;++i)p3[i]=p3[i-1]*3u;for(auto&p:z.plans){p.len=plen;p.keep.resize(plen+1);p.kept.assign(plen+1,0);for(int lev=0;lev<=plen;++lev)p.keep[lev].assign(p3[lev],0);}
    std::array<std::vector<uint32_t>,9>scur{};scur[0].push_back(0);uint32_t sp3=1;for(int lev=0;lev<slen;++lev){std::array<std::vector<uint32_t>,9>nxt{};for(int hd=0;hd<9;++hd)for(uint32_t c:scur[hd])for(int sym=0;sym<3;++sym){int hs=hd-DELTA[sym];if(0<=hs&&hs<9)nxt[hs].push_back(uint32_t(sym)*sp3+c);}scur=std::move(nxt);sp3*=3u;}
    std::array<Code,9>srlo{},srhi{};for(int h=0;h<9;++h){if(scur[h].empty())throw std::runtime_error("row8 empty suffix height in prune planner");srlo[h]=~Code(0);srhi[h]=0;for(uint32_t c:scur[h]){Code q=suffix_rank(c,slen,h);srlo[h]=std::min(srlo[h],q);srhi[h]=std::max(srhi[h],q);}}
    std::array<std::vector<uint32_t>,9>pcur{};pcur[1].push_back(0);for(int lev=0;lev<plen;++lev){std::array<std::vector<uint32_t>,9>nxt{};for(int h=0;h<9;++h)for(uint32_t c:pcur[h])for(int sym=0;sym<3;++sym){int h2=h+DELTA[sym];if(0<=h2&&h2<9)nxt[h2].push_back(c*3u+uint32_t(sym));}pcur=std::move(nxt);}
    for(int h=0;h<9;++h)for(uint32_t c:pcur[h]){Code b=prefix_base(c,plen,W),lo=b+srlo[h],hi=b+srhi[h];for(int d=0;d<ng;++d){Code rb=Code(d)*chunk,rl=rb+lens[d];if(hi>=rb&&lo<rl)z.plans[d].keep[plen][c]=1;}}
    for(auto&p:z.plans){for(int lev=plen;lev>0;--lev){size_t n=0;for(uint32_t c=0;c<p.keep[lev].size();++c)if(p.keep[lev][c]){++n;p.keep[lev-1][c/3u]=1;}p.kept[lev]=n;}p.kept[0]=p.keep[0][0]!=0;}
    z.build_s=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();return z;}
inline const PrefixPlanSet& prefix_plan_set_cached(int W,int plen,int slen,Code chunk,const std::vector<Code>&lens,int ng){static std::unique_ptr<PrefixPlanSet>cache;bool same=cache&&cache->W==W&&cache->plen==plen&&cache->slen==slen&&cache->ng==ng&&cache->chunk==chunk&&cache->lens==lens;if(!same){cache=std::make_unique<PrefixPlanSet>(build_prefix_plan_set(W,plen,slen,chunk,lens,ng));std::cerr<<"row8 prefix prune plan gpus="<<ng<<" build_s="<<cache->build_s;for(int d=0;d<ng;++d)std::cerr<<" shard"<<d<<"="<<cache->plans[d].kept[plen];std::cerr<<"\n";}return *cache;}

inline double scatter_height(cublasHandle_t handle,const Runtime&r,const Group&pg,const Group&sg,int h,int plen,int slen,Count*full,Code rankBase,Code rankLimit){
    const int n=sg.rows,k=DIMS[h],kp=(k+15)&~15,np=(n+15)&~15;
    std::vector<unsigned long long> sr(n);
    for(int i=0;i<n;++i)sr[i]=suffix_rank(sg.code[i],slen,h);
    auto [srloIt,srhiIt]=std::minmax_element(sr.begin(),sr.end());
    const unsigned long long srlo=*srloIt,srhi=*srhiIt;
    std::vector<uint32_t> sel; sel.reserve(pg.rows);
    std::vector<unsigned long long> pb; pb.reserve(pg.rows);
    for(int i=0;i<pg.rows;++i){
        unsigned long long b=prefix_base(pg.code[i],plen,plen+slen);
        if(b+srhi>=rankBase && b+srlo<rankLimit){sel.push_back(uint32_t(i));pb.push_back(b);}
    }
    const int m=int(sel.size());
    if(!m)return 0.0;
    const int mp=(m+15)&~15;
    Scratch sc;auto t0=std::chrono::steady_clock::now();
    uint32_t*dSel=nullptr;if(m==pg.rows)prepare_a(sc,pg,kp);else{ck(cudaMalloc(&dSel,size_t(m)*sizeof(uint32_t)),"row8 selected rows");ck(cudaMemcpy(dSel,sel.data(),size_t(m)*sizeof(uint32_t),cudaMemcpyHostToDevice),"row8 selected rows copy");prepare_a_indexed(sc,pg,dSel,m,kp);}
    std::array<int8_t*,4>b{};size_t bbytes=(size_t)kp*np;
    for(auto&q:b){ck(cudaMalloc(&q,bbytes),"row8 join B");ck(cudaMemset(q,0,bbytes),"row8 join B zero");}
    int32_t*cs=nullptr;ck(cudaMalloc(&cs,(size_t)4*n*4),"row8 join sums");int blocks=std::min(65535,(n+127)/128);pack_rows<<<std::max(1,blocks),128>>>(sg.d,n,k,kp,b[0],b[1],b[2],b[3],cs);
    unsigned long long*dPB=nullptr,*dSR=nullptr;ck(cudaMalloc(&dPB,(size_t)m*8),"row8 pbase");ck(cudaMalloc(&dSR,(size_t)n*8),"row8 srank");ck(cudaMemcpy(dPB,pb.data(),(size_t)m*8,cudaMemcpyHostToDevice),"row8 pbase copy");ck(cudaMemcpy(dSR,sr.data(),(size_t)n*8,cudaMemcpyHostToDevice),"row8 srank copy");
    int tile=1024;if(const char*e=std::getenv("GRIDFP_ROW8_JOIN_TILE_COLS"))tile=std::max(16,std::atoi(e));tile=std::max(16,(tile/16)*16);
    for(int c0=0;c0<n;c0+=tile){int nt=std::min(tile,n-c0),ntp=(nt+15)&~15;sc.ensure_out((size_t)mp*ntp,(size_t)m*nt);ck(cudaMemset(sc.acc,0,(size_t)m*nt*8),"row8 join acc zero");for(int e=6;e>=0;--e){int pairs=0;bool first=true;int32_t one=1;for(int a=0;a<4;++a){int bb=e-a;if(bb<0||bb>=4)continue;++pairs;int32_t beta=first?0:1;cublas_ck(cublasGemmEx(handle,CUBLAS_OP_T,CUBLAS_OP_N,mp,ntp,kp,&one,sc.a[a],CUDA_R_8I,kp,b[bb]+(size_t)kp*c0,CUDA_R_8I,kp,&beta,sc.C,CUDA_R_32I,mp,CUBLAS_COMPUTE_32I,CUBLAS_GEMM_DEFAULT_TENSOR_OP),"join gemm");first=false;}bool join2d=false;if(const char*je=std::getenv("GRIDFP_ROW8_JOIN_2D_ACCUM"))join2d=std::atoi(je)!=0;if(join2d){dim3 gd((unsigned(m)+255)/256,unsigned(nt));accum_scatter_2d<<<gd,256>>>(sc.C,mp,m,nt,sc.rs,cs,n,c0,sc.acc,pairs,k,e,e==3||e==0,dPB,dSR,full,e==0,r.mod,rankBase,rankLimit);}else{int nb=std::min<unsigned long long>(65535,((unsigned long long)m*nt+255)/256);accum_scatter<<<std::max(1,nb),256>>>(sc.C,mp,m,nt,sc.rs,cs,n,c0,sc.acc,pairs,k,e,e==3||e==0,dPB,dSR,full,e==0,r.mod,rankBase,rankLimit);}ck(cudaGetLastError(),"row8 join accum");}}
    ck(cudaDeviceSynchronize(),"row8 join sync");double sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();
    if(const char*e=std::getenv("GRIDFP_ROW8_PROFILE_SHARDS");e&&std::atoi(e))std::cerr<<"row8 shard h="<<h<<" selected_rows="<<m<<"/"<<pg.rows<<" cols="<<n<<" rank=["<<rankBase<<","<<rankLimit<<") sec="<<sec<<"\n";
    if(dSel)cudaFree(dSel);cudaFree(dPB);cudaFree(dSR);cudaFree(cs);for(auto q:b)cudaFree(q);return sec;
}
inline double scatter_all(cublasHandle_t handle,const Runtime&r,const std::array<Group,9>&pg,const std::array<Group,9>&sg,int plen,int slen,Count*full,Code rankBase,Code rankLimit){double s=0;for(int h=0;h<9;++h)if(pg[h].rows&&sg[h].rows)s+=scatter_height(handle,r,pg[h],sg[h],h,plen,slen,full,rankBase,rankLimit);return s;}
inline double scatter_height_compare(cublasHandle_t handle,const Runtime&r,const Group&pg,const Group&sg,int h,int plen,int slen,const Count*baseline,Code rankBase,Code rankLimit,unsigned long long*dMismatch){
    const int n=sg.rows,k=DIMS[h],kp=(k+15)&~15,np=(n+15)&~15;
    std::vector<unsigned long long> sr(n);
    for(int i=0;i<n;++i)sr[i]=suffix_rank(sg.code[i],slen,h);
    auto [srloIt,srhiIt]=std::minmax_element(sr.begin(),sr.end());
    const unsigned long long srlo=*srloIt,srhi=*srhiIt;
    std::vector<uint32_t> sel; sel.reserve(pg.rows);
    std::vector<unsigned long long> pb; pb.reserve(pg.rows);
    for(int i=0;i<pg.rows;++i){unsigned long long b=prefix_base(pg.code[i],plen,plen+slen);if(b+srhi>=rankBase&&b+srlo<rankLimit){sel.push_back(uint32_t(i));pb.push_back(b);}}
    const int m=int(sel.size());if(!m)return 0.0;const int mp=(m+15)&~15;
    Scratch sc;auto t0=std::chrono::steady_clock::now();uint32_t*dSel=nullptr;if(m==pg.rows)prepare_a(sc,pg,kp);else{ck(cudaMalloc(&dSel,size_t(m)*sizeof(uint32_t)),"row8 compare selected rows");ck(cudaMemcpy(dSel,sel.data(),size_t(m)*sizeof(uint32_t),cudaMemcpyHostToDevice),"row8 compare selected rows copy");prepare_a_indexed(sc,pg,dSel,m,kp);}
    std::array<int8_t*,4>b{};size_t bbytes=(size_t)kp*np;for(auto&q:b){ck(cudaMalloc(&q,bbytes),"row8 compare B");ck(cudaMemset(q,0,bbytes),"row8 compare B zero");}
    int32_t*cs=nullptr;ck(cudaMalloc(&cs,(size_t)4*n*4),"row8 compare sums");int blocks=std::min(65535,(n+127)/128);pack_rows<<<std::max(1,blocks),128>>>(sg.d,n,k,kp,b[0],b[1],b[2],b[3],cs);
    unsigned long long*dPB=nullptr,*dSR=nullptr;ck(cudaMalloc(&dPB,(size_t)m*8),"row8 compare pbase");ck(cudaMalloc(&dSR,(size_t)n*8),"row8 compare srank");ck(cudaMemcpy(dPB,pb.data(),(size_t)m*8,cudaMemcpyHostToDevice),"row8 compare pbase copy");ck(cudaMemcpy(dSR,sr.data(),(size_t)n*8,cudaMemcpyHostToDevice),"row8 compare srank copy");
    int tile=1024;if(const char*e=std::getenv("GRIDFP_ROW8_JOIN_TILE_COLS"))tile=std::max(16,std::atoi(e));tile=std::max(16,(tile/16)*16);
    for(int c0=0;c0<n;c0+=tile){int nt=std::min(tile,n-c0),ntp=(nt+15)&~15;sc.ensure_out((size_t)mp*ntp,(size_t)m*nt);ck(cudaMemset(sc.acc,0,(size_t)m*nt*8),"row8 compare acc zero");for(int e=6;e>=0;--e){int pairs=0;bool first=true;int32_t one=1;for(int a=0;a<4;++a){int bb=e-a;if(bb<0||bb>=4)continue;++pairs;int32_t beta=first?0:1;cublas_ck(cublasGemmEx(handle,CUBLAS_OP_T,CUBLAS_OP_N,mp,ntp,kp,&one,sc.a[a],CUDA_R_8I,kp,b[bb]+(size_t)kp*c0,CUDA_R_8I,kp,&beta,sc.C,CUDA_R_32I,mp,CUBLAS_COMPUTE_32I,CUBLAS_GEMM_DEFAULT_TENSOR_OP),"join compare gemm");first=false;}bool join2d=false;if(const char*je=std::getenv("GRIDFP_ROW8_JOIN_2D_ACCUM"))join2d=std::atoi(je)!=0;if(join2d){dim3 gd((unsigned(m)+255)/256,unsigned(nt));accum_scatter_compare_2d<<<gd,256>>>(sc.C,mp,m,nt,sc.rs,cs,n,c0,sc.acc,pairs,k,e,e==3||e==0,dPB,dSR,baseline,e==0,r.mod,rankBase,rankLimit,dMismatch);}else{int nb=std::min<unsigned long long>(65535,((unsigned long long)m*nt+255)/256);accum_scatter_compare<<<std::max(1,nb),256>>>(sc.C,mp,m,nt,sc.rs,cs,n,c0,sc.acc,pairs,k,e,e==3||e==0,dPB,dSR,baseline,e==0,r.mod,rankBase,rankLimit,dMismatch);}ck(cudaGetLastError(),"row8 join compare accum");}}
    ck(cudaDeviceSynchronize(),"row8 join compare sync");double sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();if(dSel)cudaFree(dSel);cudaFree(dPB);cudaFree(dSR);cudaFree(cs);for(auto q:b)cudaFree(q);return sec;
}
inline double scatter_all_compare(cublasHandle_t handle,const Runtime&r,const std::array<Group,9>&pg,const std::array<Group,9>&sg,int plen,int slen,const Count*baseline,Code rankBase,Code rankLimit,unsigned long long*dMismatch){double s=0;for(int h=0;h<9;++h)if(pg[h].rows&&sg[h].rows)s+=scatter_height_compare(handle,r,pg[h],sg[h],h,plen,slen,baseline,rankBase,rankLimit,dMismatch);return s;}

struct InitStats{double prefix_s=0,suffix_s=0,join_s=0,gpu_init_s=0;};
inline InitStats init_gpu_shard_prebuilt(int W,Count mod,Count*fullMain,const ModData&md,int dev,Code rankBase,Code rankLimit,const PrefixPrunePlan*plan=nullptr){if(W!=TARGET_W)throw std::runtime_error("row8 tensor width mismatch");ck(cudaSetDevice(dev),"row8 set device");auto t0=std::chrono::steady_clock::now();Runtime rt=make_runtime(md,mod);cublasHandle_t handle=nullptr;cublas_ck(cublasCreate(&handle),"create");cublas_ck(cublasSetMathMode(handle,CUBLAS_TENSOR_OP_MATH),"math mode");int lo=TARGET_W/2,hi=W-lo;InitStats st;auto pg=plan?build_prefix_levels_pruned(handle,rt,hi,*plan,st.prefix_s):build_levels(handle,rt,hi,false,st.prefix_s);auto sg=build_levels(handle,rt,lo,true,st.suffix_s);st.join_s=scatter_all(handle,rt,pg,sg,hi,lo,fullMain,rankBase,rankLimit);free_groups(pg);free_groups(sg);cublasDestroy(handle);destroy(rt);st.gpu_init_s=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();return st;}
inline void init_single_gpu_prebuilt(int W,Count mod,Count*fullMain,const ModData&md){auto st=init_gpu_shard_prebuilt(W,mod,fullMain,md,0,0,H_DP[W][1]);std::cerr<<"direct row8 tensor mod="<<mod<<" mod_build_s="<<md.build_s<<" inv_s="<<md.inv_s<<" trans_build_s="<<md.trans_s<<" prefix_s="<<st.prefix_s<<" suffix_s="<<st.suffix_s<<" join_s="<<st.join_s<<" gpu_init_s="<<st.gpu_init_s<<"\n";}
inline void init_multi_gpu_prebuilt(int W,Count mod,Count**fullMain,const std::vector<Code>&mainLen,Code mainChunk,int ng,const ModData&md){
    int fake=0;if(ng==1)if(const char*e=std::getenv("GRIDFP_ROW8_FAKE_SHARDS"))fake=std::max(0,std::atoi(e));
    bool prune=(fake>1||ng>1);if(const char*e=std::getenv("GRIDFP_ROW8_PREFIX_PRUNE"))prune=std::atoi(e)!=0;
    const int lo=TARGET_W/2,hi=W-lo;
    if(fake>1){Code total=H_DP[W][1],chunk=(total+fake-1)/fake;std::vector<Code>lens(fake);for(int d=0;d<fake;++d){Code base=Code(d)*chunk;lens[d]=base<total?std::min<Code>(chunk,total-base):0;}const PrefixPlanSet*pps=prune?&prefix_plan_set_cached(W,hi,lo,chunk,lens,fake):nullptr;auto wall0=std::chrono::steady_clock::now();double gm=0;for(int d=0;d<fake;++d){Code base=Code(d)*chunk;if(base>=total)break;Code lim=base+lens[d];auto st=init_gpu_shard_prebuilt(W,mod,fullMain[0]+base,md,0,base,lim,pps?&pps->plans[d]:nullptr);gm=std::max(gm,st.gpu_init_s);}double wall=std::chrono::duration<double>(std::chrono::steady_clock::now()-wall0).count();std::cerr<<"direct row8 tensor fake-shards="<<fake<<" mod="<<mod<<" prefix_prune="<<prune<<" gpu_max_s="<<gm<<" wall_s="<<wall<<"\n";return;}
    const PrefixPlanSet*pps=prune?&prefix_plan_set_cached(W,hi,lo,mainChunk,mainLen,ng):nullptr;
    std::vector<InitStats>stats(ng);std::vector<std::thread>ths;ths.reserve(ng);auto wall0=std::chrono::steady_clock::now();for(int d=0;d<ng;++d)ths.emplace_back([&,d]{Code base=Code(d)*mainChunk,lim=base+mainLen[d];stats[d]=init_gpu_shard_prebuilt(W,mod,fullMain[d],md,d,base,lim,pps?&pps->plans[d]:nullptr);});for(auto&t:ths)t.join();double wall=std::chrono::duration<double>(std::chrono::steady_clock::now()-wall0).count(),pm=0,sm=0,jm=0,gm=0;for(auto const&st:stats){pm=std::max(pm,st.prefix_s);sm=std::max(sm,st.suffix_s);jm=std::max(jm,st.join_s);gm=std::max(gm,st.gpu_init_s);}std::cerr<<"direct row8 tensor multi mod="<<mod<<" gpus="<<ng<<" prefix_prune="<<prune<<" mod_build_s="<<md.build_s<<" prefix_max_s="<<pm<<" suffix_max_s="<<sm<<" join_max_s="<<jm<<" gpu_max_s="<<gm<<" wall_s="<<wall<<"\n";
}
} // namespace oneesan::row8tensor
