#pragma once
#include <cublas_v2.h>
#include <cuda_runtime.h>
#include <algorithm>
#include <array>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>
namespace modgpu_runtime {
inline void mck(cudaError_t e,const char*w){if(e!=cudaSuccess)throw std::runtime_error(std::string(w)+": "+cudaGetErrorString(e));}
inline void mcb(cublasStatus_t e,const char*w){if(e!=CUBLAS_STATUS_SUCCESS)throw std::runtime_error(std::string(w)+" cublas="+std::to_string((int)e));}
inline uint32_t mpow(uint32_t a,uint64_t e,uint32_t mod){uint64_t r=1,x=a;while(e){if(e&1)r=(__uint128_t)r*x%mod;x=(__uint128_t)x*x%mod;e>>=1;}return uint32_t(r);}
__global__ void find_pivot(const uint32_t*A,int rows,int cols,int r0,int col,int*out){for(int r=r0+blockIdx.x*blockDim.x+threadIdx.x;r<rows;r+=gridDim.x*blockDim.x)if(A[(size_t)r*cols+col])atomicMin(out,r);}
__global__ void swap_rows(uint32_t*A,int cols,int a,int b){for(int j=blockIdx.x*blockDim.x+threadIdx.x;j<cols;j+=gridDim.x*blockDim.x){uint32_t z=A[(size_t)a*cols+j];A[(size_t)a*cols+j]=A[(size_t)b*cols+j];A[(size_t)b*cols+j]=z;}}
__global__ void scale_row(uint32_t*A,int cols,int r,int c,uint32_t inv,uint32_t mod){for(int j=c+blockIdx.x*blockDim.x+threadIdx.x;j<cols;j+=gridDim.x*blockDim.x)A[(size_t)r*cols+j]=uint64_t(A[(size_t)r*cols+j])*inv%mod;}
__global__ void eliminate_all(uint32_t*A,int rows,int cols,int piv,int c,uint32_t mod){size_t width=cols-c-1,total=size_t(rows-1)*width;if(!width)return;for(size_t q=size_t(blockIdx.x)*blockDim.x+threadIdx.x;q<total;q+=size_t(gridDim.x)*blockDim.x){int rr=int(q/width);if(rr>=piv)++rr;int j=c+1+int(q%width);uint32_t scale=A[(size_t)rr*cols+c];if(!scale)continue;uint32_t sub=uint64_t(scale)*A[(size_t)piv*cols+j]%mod;uint32_t&x=A[(size_t)rr*cols+j];x=x>=sub?x-sub:x+mod-sub;}}
__global__ void zero_col_except(uint32_t*A,int rows,int cols,int piv,int c){for(int r=blockIdx.x*blockDim.x+threadIdx.x;r<rows;r+=gridDim.x*blockDim.x)if(r!=piv)A[(size_t)r*cols+c]=0;}
inline std::vector<uint32_t> invert(const std::vector<uint32_t>&B,int n,uint32_t mod,double*secs=nullptr){if(B.size()!=size_t(n)*n)throw std::runtime_error("invert size");const int cols=2*n;std::vector<uint32_t>A(size_t(n)*cols);for(int i=0;i<n;++i){std::copy_n(B.data()+size_t(i)*n,n,A.data()+size_t(i)*cols);A[size_t(i)*cols+n+i]=1;}uint32_t*dA=nullptr;int*dP=nullptr;mck(cudaMalloc(&dA,A.size()*4),"inv A");mck(cudaMemcpy(dA,A.data(),A.size()*4,cudaMemcpyHostToDevice),"inv Acp");mck(cudaMalloc(&dP,4),"inv pivot");cudaEvent_t es,ee;mck(cudaEventCreate(&es),"ev");mck(cudaEventCreate(&ee),"ev");mck(cudaEventRecord(es),"rec");for(int c=0;c<n;++c){int init=n;mck(cudaMemcpy(dP,&init,4,cudaMemcpyHostToDevice),"pinit");find_pivot<<<std::min(256,(n-c+127)/128),128>>>(dA,n,cols,c,c,dP);int pr;mck(cudaMemcpy(&pr,dP,4,cudaMemcpyDeviceToHost),"pcp");if(pr==n)throw std::runtime_error("singular at "+std::to_string(c));if(pr!=c)swap_rows<<<std::min(256,(cols+255)/256),256>>>(dA,cols,c,pr);uint32_t pv;mck(cudaMemcpy(&pv,dA+size_t(c)*cols+c,4,cudaMemcpyDeviceToHost),"pv");scale_row<<<std::min(256,(cols-c+255)/256),256>>>(dA,cols,c,c,mpow(pv,uint64_t(mod)-2,mod),mod);size_t cells=size_t(n-1)*std::max(0,cols-c-1);if(cells)eliminate_all<<<std::min<size_t>(65535,(cells+255)/256),256>>>(dA,n,cols,c,c,mod);zero_col_except<<<std::min(256,(n+255)/256),256>>>(dA,n,cols,c,c);}mck(cudaEventRecord(ee),"rec");mck(cudaEventSynchronize(ee),"sync");float ms=0;mck(cudaEventElapsedTime(&ms,es,ee),"elapsed");if(secs)*secs=ms/1000.0;mck(cudaMemcpy(A.data(),dA,A.size()*4,cudaMemcpyDeviceToHost),"inv out");std::vector<uint32_t>I(size_t(n)*n);for(int i=0;i<n;++i)std::copy_n(A.data()+size_t(i)*cols+n,n,I.data()+size_t(i)*n);cudaFree(dA);cudaFree(dP);cudaEventDestroy(es);cudaEventDestroy(ee);return I;}
__global__ void accum_digit(const int32_t*C,int ldc,int m,int n,const int32_t*rs,const int32_t*cs,unsigned long long*acc,int np,int k,int e,int reduce,uint32_t mod){for(unsigned long long q=(unsigned long long)blockIdx.x*blockDim.x+threadIdx.x,st=(unsigned long long)gridDim.x*blockDim.x;q<(unsigned long long)m*n;q+=st){int r=q%m,c=q/m;long long ar=0,bc=0;for(int a=0;a<4;++a){int b=e-a;if(0<=b&&b<4){ar+=rs[(size_t)a*m+r];bc+=cs[(size_t)b*n+c];}}long long de=(long long)C[r+(size_t)ldc*c]+128LL*(ar+bc)-(long long)np*16384LL*k;unsigned long long x=acc[q]*256ULL+(unsigned long long)de;if(reduce)x%=mod;acc[q]=x;}}
inline std::vector<uint32_t> multiply(const std::vector<uint32_t>&A,int m,int k,const std::vector<uint32_t>&B,int n,uint32_t mod,double*secs=nullptr){if(A.size()!=size_t(m)*k||B.size()!=size_t(k)*n)throw std::runtime_error("mul size");int kp=(k+15)&~15,mp=(m+15)&~15,np=(n+15)&~15;std::array<std::vector<int8_t>,4>a,b;std::vector<int32_t>rs(size_t(4)*m),cs(size_t(4)*n);for(int z=0;z<4;++z){a[z].assign(size_t(kp)*mp,0);b[z].assign(size_t(kp)*np,0);}for(int r=0;r<m;++r)for(int j=0;j<k;++j){uint32_t x=A[size_t(r)*k+j];for(int z=0;z<4;++z){int v=(x>>(8*z))&255;a[z][j+size_t(kp)*r]=int8_t(v-128);rs[size_t(z)*m+r]+=v;}}for(int j=0;j<k;++j)for(int c=0;c<n;++c){uint32_t x=B[size_t(j)*n+c];for(int z=0;z<4;++z){int v=(x>>(8*z))&255;b[z][j+size_t(kp)*c]=int8_t(v-128);cs[size_t(z)*n+c]+=v;}}
 std::array<int8_t*,4>da{},db{};for(int z=0;z<4;++z){mck(cudaMalloc(&da[z],a[z].size()),"mul A");mck(cudaMalloc(&db[z],b[z].size()),"mul B");mck(cudaMemcpy(da[z],a[z].data(),a[z].size(),cudaMemcpyHostToDevice),"mul Acp");mck(cudaMemcpy(db[z],b[z].data(),b[z].size(),cudaMemcpyHostToDevice),"mul Bcp");}int32_t*dC=nullptr,*dRS=nullptr,*dCS=nullptr;unsigned long long*dAcc=nullptr;mck(cudaMalloc(&dC,size_t(mp)*np*4),"mul C");mck(cudaMalloc(&dRS,rs.size()*4),"mul rs");mck(cudaMalloc(&dCS,cs.size()*4),"mul cs");mck(cudaMalloc(&dAcc,size_t(m)*n*8),"mul acc");mck(cudaMemcpy(dRS,rs.data(),rs.size()*4,cudaMemcpyHostToDevice),"rscp");mck(cudaMemcpy(dCS,cs.data(),cs.size()*4,cudaMemcpyHostToDevice),"cscp");mck(cudaMemset(dAcc,0,size_t(m)*n*8),"acc0");cublasHandle_t h;mcb(cublasCreate(&h),"create");mcb(cublasSetMathMode(h,CUBLAS_TENSOR_OP_MATH),"math");cudaEvent_t es,ee;mck(cudaEventCreate(&es),"ev");mck(cudaEventCreate(&ee),"ev");mck(cudaEventRecord(es),"rec");for(int e=6;e>=0;--e){int pairs=0;bool first=true;int32_t one=1;for(int x=0;x<4;++x){int y=e-x;if(y<0||y>=4)continue;++pairs;int32_t beta=first?0:1;mcb(cublasGemmEx(h,CUBLAS_OP_T,CUBLAS_OP_N,mp,np,kp,&one,da[x],CUDA_R_8I,kp,db[y],CUDA_R_8I,kp,&beta,dC,CUDA_R_32I,mp,CUBLAS_COMPUTE_32I,CUBLAS_GEMM_DEFAULT_TENSOR_OP),"gemm");first=false;}int blocks=std::min<unsigned long long>(65535,((unsigned long long)m*n+255)/256);accum_digit<<<std::max(1,blocks),256>>>(dC,mp,m,n,dRS,dCS,dAcc,pairs,k,e,e==3||e==0,mod);}mck(cudaEventRecord(ee),"rec");mck(cudaEventSynchronize(ee),"sync");float ms=0;mck(cudaEventElapsedTime(&ms,es,ee),"elapsed");if(secs)*secs=ms/1000.0;std::vector<unsigned long long>tmp(size_t(m)*n);mck(cudaMemcpy(tmp.data(),dAcc,tmp.size()*8,cudaMemcpyDeviceToHost),"mul out");std::vector<uint32_t>C(tmp.size());for(int r=0;r<m;++r)for(int c=0;c<n;++c)C[size_t(r)*n+c]=uint32_t(tmp[size_t(c)*m+r]);for(int z=0;z<4;++z){cudaFree(da[z]);cudaFree(db[z]);}cudaFree(dC);cudaFree(dRS);cudaFree(dCS);cudaFree(dAcc);cudaEventDestroy(es);cudaEventDestroy(ee);cublasDestroy(h);return C;}
}
