#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

using Code=unsigned long long;
static constexpr int MAXW=28,NGPU=8;
static constexpr Code MIN_AVG_INTERVAL_ELEMS=65536,IO_TILE_ELEMS=65536;
static Code H[MAXW+1][MAXW+2]{};
struct Spec{int width=0;std::uint32_t fixed=0,occ=0;Code dp[MAXW+1][MAXW+2]{};Code size=0;};
static void build_full(){for(int h=0;h<=MAXW+1;++h)H[0][h]=(h==0);for(int w=1;w<=MAXW;++w)for(int h=0;h<=MAXW;++h){Code x=H[w-1][h];if(h)x+=H[w-1][h-1];if(h<MAXW+1)x+=H[w-1][h+1];H[w][h]=x;}}
static Spec make_spec(int width,std::uint32_t fixed,std::uint32_t occ){Spec s;s.width=width;s.fixed=fixed;s.occ=occ;s.dp[0][0]=1;for(int w=1;w<=width;++w){int pos=w-1;bool f=(fixed>>pos)&1u,o=(occ>>pos)&1u;for(int h=0;h<=MAXW;++h){Code x=0;if(!f||!o)x+=s.dp[w-1][h];if(!f||o){if(h)x+=s.dp[w-1][h-1];if(h<MAXW+1)x+=s.dp[w-1][h+1];}s.dp[w][h]=x;}}s.size=s.dp[width][1];return s;}
static std::vector<int> candidates(int W,int hi,int lo){std::vector<int>v;for(int q=W-1;q>=0;--q)if(q<lo-1||q>hi)v.push_back(q);return v;}
static void masks(int hi,int lo,const std::vector<int>&fp,std::uint32_t g,std::uint32_t&mf,std::uint32_t&mo,std::uint32_t&bf,std::uint32_t&bo){(void)hi;mf=mo=bf=bo=0;for(size_t i=0;i<fp.size();++i){int q=fp[i];bool one=(g>>i)&1u;mf|=1u<<q;if(one)mo|=1u<<q;int bq=q<lo-1?q:q-1;bf|=1u<<bq;if(one)bo|=1u<<bq;}}
static Code leaf_rec(const Spec&s,int pos,int h,Code memo[MAXW+1][MAXW+2],bool seen[MAXW+1][MAXW+2]){if(pos<0)return h==0;if(seen[pos][h])return memo[pos][h];seen[pos][h]=true;std::uint32_t lower=(1u<<(pos+1))-1u;if((s.fixed&lower)==0)return memo[pos][h]=H[pos+1][h]?1:0;bool f=(s.fixed>>pos)&1u,o=(s.occ>>pos)&1u;Code z=0;if(!f||!o)z+=leaf_rec(s,pos-1,h,memo,seen);if(!f||o){if(h)z+=leaf_rec(s,pos-1,h-1,memo,seen);if(h<MAXW+1)z+=leaf_rec(s,pos-1,h+1,memo,seen);}return memo[pos][h]=z;}
static Code leaf_upper(const Spec&s){Code memo[MAXW+1][MAXW+2]{};bool seen[MAXW+1][MAXW+2]{};return leaf_rec(s,s.width-1,1,memo,seen);}
struct IntervalStats{Code base=0,tiled=0,total=0;};
static IntervalStats interval_stats(const Spec&s){struct Acc{Code pg=0,pl=0,pn=0;bool have=false;IntervalStats st;};Acc a;auto flush=[&](){if(!a.have)return;a.st.base++;a.st.tiled+=(a.pn+IO_TILE_ELEMS-1)/IO_TILE_ELEMS;a.st.total+=a.pn;a.have=false;};auto add=[&](Code g,Code l,Code n){if(!n)return;if(a.have&&a.pg+a.pn==g&&a.pl+a.pn==l)a.pn+=n;else{flush();a.pg=g;a.pl=l;a.pn=n;a.have=true;}};auto rec=[&](auto&&self,int pos,int h,Code gb,Code lb)->void{if(pos<0){if(h==0)add(gb,lb,1);return;}std::uint32_t lower=(1u<<(pos+1))-1u;if((s.fixed&lower)==0){add(gb,lb,H[pos+1][h]);return;}bool f=(s.fixed>>pos)&1u,o=(s.occ>>pos)&1u;Code gsz=H[pos][h];if(!f||!o){Code lsz=s.dp[pos][h];self(self,pos-1,h,gb,lb);lb+=lsz;}gb+=gsz;if(h){gsz=H[pos][h-1];if(!f||o){Code lsz=s.dp[pos][h-1];self(self,pos-1,h-1,gb,lb);lb+=lsz;}gb+=gsz;}if(h<MAXW+1&&(!f||o))self(self,pos-1,h+1,gb,lb);};rec(rec,s.width-1,1,0,0);flush();if(a.st.total!=s.size){std::fprintf(stderr,"interval size mismatch\n");std::exit(2);}return a.st;}
static Code tiled_if_used(const Spec&s){Code est=leaf_upper(s);if(est&&s.size<est*MIN_AVG_INTERVAL_ELEMS)return 0;auto st=interval_stats(s);if(st.base&&s.size<st.base*MIN_AVG_INTERVAL_ELEMS)return 0;return st.tiled;}
struct Group{Code work=0,main=0,block=0,mi=0,di=0;std::uint32_t g=0;};
static std::vector<Group> make_groups(int hi,int lo){auto fp=candidates(28,hi,lo);fp.resize(13);std::vector<Group>v;v.reserve(8192);for(std::uint32_t g=0;g<8192;++g){std::uint32_t mf,mo,bf,bo;masks(hi,lo,fp,g,mf,mo,bf,bo);auto ms=make_spec(28,mf,mo),ds=make_spec(27,bf,bo);v.push_back({2*ms.size+ds.size,ms.size,ds.size,tiled_if_used(ms),tiled_if_used(ds),g});}std::sort(v.begin(),v.end(),[](auto const&a,auto const&b){if(a.work!=b.work)return a.work>b.work;if(a.main!=b.main)return a.main>b.main;if(a.block!=b.block)return a.block>b.block;return a.g<b.g;});return v;}
int main(){build_full();std::array<Code,NGPU>load{},desc{},main_desc{},block_desc{};std::array<std::uint32_t,NGPU>count{};Code total_desc=0,total_main=0,total_block=0;std::uint64_t used_main=0,used_block=0;for(auto win:std::array<std::array<int,2>,2>{{{{27,14}},{{13,1}}}}){auto v=make_groups(win[0],win[1]);for(auto const&x:v){int d=0;for(int q=1;q<NGPU;++q)if(load[q]<load[d])d=q;load[d]+=x.work;desc[d]+=x.mi+x.di;main_desc[d]+=x.mi;block_desc[d]+=x.di;++count[d];total_desc+=x.mi+x.di;total_main+=x.mi;total_block+=x.di;used_main+=x.mi!=0;used_block+=x.di!=0;}}
constexpr std::array<std::uint32_t,NGPU> ec={2044,2046,2048,2048,2048,2048,2050,2052};constexpr std::array<Code,NGPU> ed={1056256,1057352,1056319,1056324,1056756,1056756,1056888,1056867};constexpr std::array<Code,NGPU> em={758186,758694,758290,758296,758489,758489,758521,758363};constexpr std::array<Code,NGPU> eb={298070,298658,298029,298028,298267,298267,298367,298504};if(count!=ec||desc!=ed||main_desc!=em||block_desc!=eb)return 3;if(total_desc!=8453518ull||total_main!=6067328ull||total_block!=2386190ull||used_main!=8192ull||used_block!=8192ull)return 4;Code max_desc=*std::max_element(desc.begin(),desc.end()),min_desc=*std::min_element(desc.begin(),desc.end());Code total_bytes=total_desc*24,max_bytes=max_desc*24,old_bytes=total_bytes*28,combined_max=0;for(int d=0;d<NGPU;++d)combined_max=std::max(combined_max,Code(count[d])*13936ull+desc[d]*24ull);if(total_bytes!=202884432ull||max_bytes!=25376448ull||old_bytes!=5680764096ull||combined_max!=53961480ull)return 5;std::printf("b300-static-lpt-interval-staging-proof OK windows=2 groups=16384 descriptor_bytes=24 interval_groups_main=8192 interval_groups_block=8192 main_descriptors=6067328 block_descriptors=2386190 total_descriptors=8453518 gpu_descriptor_min=%llu gpu_descriptor_max=%llu staged_total_bytes=%llu staged_total_gib=0.188950851560 staged_max_bytes_per_gpu=%llu staged_max_mib_per_gpu=24.200866699 old_rows=28 repeated_h2d_bytes=%llu repeated_h2d_gib=5.290623843670 h2d_reduction=28x metadata_plus_interval_actual_max_bytes_per_gpu=%llu metadata_plus_interval_actual_max_mib_per_gpu=51.461677551 assignment=static_lpt exact=1\n",min_desc,max_desc,total_bytes,max_bytes,old_bytes,combined_max);return 0;}
