#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

using Code=unsigned long long;
static constexpr int MAXW=28,NGPU=8;
static Code H[MAXW+1][MAXW+2]{};

struct Spec{int width=0;std::uint32_t fixed=0,occ=0;Code dp[MAXW+1][MAXW+2]{};Code size=0;};
struct Group{int win=0;std::uint32_t g=0;Code work=0,main=0,block=0;std::array<Code,NGPU> local{};};
struct Assign{std::array<Code,NGPU> load{},local{};std::array<std::uint32_t,NGPU> count{};};

static void build_full(){for(int h=0;h<=MAXW+1;++h)H[0][h]=(h==0);for(int w=1;w<=MAXW;++w)for(int h=0;h<=MAXW;++h){Code x=H[w-1][h];if(h)x+=H[w-1][h-1];if(h<MAXW+1)x+=H[w-1][h+1];H[w][h]=x;}}
static Spec make_spec(int width,std::uint32_t fixed,std::uint32_t occ){Spec s;s.width=width;s.fixed=fixed;s.occ=occ;s.dp[0][0]=1;for(int w=1;w<=width;++w){int p=w-1;bool f=(fixed>>p)&1u,o=(occ>>p)&1u;for(int h=0;h<=MAXW;++h){Code x=0;if(!f||!o)x+=s.dp[w-1][h];if(!f||o){if(h)x+=s.dp[w-1][h-1];if(h<MAXW+1)x+=s.dp[w-1][h+1];}s.dp[w][h]=x;}}s.size=s.dp[width][1];return s;}
static bool allowed(const Spec&s,int p,int v){bool f=(s.fixed>>p)&1u,o=(s.occ>>p)&1u;if(!f)return true;if(!o)return v==0;return v!=0;}
// Exact accepted-state prefix count in the full canonical rank order.
static Code group_prefix(const Spec&s,Code t){if(!t)return 0;Code full=H[s.width][1];if(t>=full)return s.size;Code ans=0,rem=t;int h=1;for(int p=s.width-1;p>=0;--p){Code fs=H[p][h],gs=allowed(s,p,0)?s.dp[p][h]:0;if(rem<=fs){if(!allowed(s,p,0))return ans;if(rem==fs)return ans+gs;continue;}ans+=gs;rem-=fs;if(h){fs=H[p][h-1];gs=allowed(s,p,1)?s.dp[p][h-1]:0;if(rem<=fs){if(!allowed(s,p,1))return ans;if(rem==fs)return ans+gs;--h;continue;}ans+=gs;rem-=fs;}fs=H[p][h+1];gs=allowed(s,p,2)?s.dp[p][h+1]:0;if(rem<=fs){if(!allowed(s,p,2))return ans;if(rem==fs)return ans+gs;++h;continue;}ans+=gs;rem-=fs;std::abort();}return ans;}
static std::vector<int> candidates(int W,int hi,int lo){std::vector<int>v;for(int q=W-1;q>=0;--q)if(q<lo-1||q>hi)v.push_back(q);return v;}
static void masks(int hi,int lo,const std::vector<int>&fp,std::uint32_t g,std::uint32_t&mf,std::uint32_t&mo,std::uint32_t&bf,std::uint32_t&bo){(void)hi;mf=mo=bf=bo=0;for(size_t i=0;i<fp.size();++i){int q=fp[i];bool one=(g>>i)&1u;mf|=1u<<q;if(one)mo|=1u<<q;int bq=q<lo-1?q:q-1;bf|=1u<<bq;if(one)bo|=1u<<bq;}}
static std::array<Code,NGPU+1> bounds(Code elements,std::size_t gran,int rotation,std::size_t&mapped_units){std::size_t bytes=std::size_t(elements)*4;mapped_units=(bytes+gran-1)/gran;std::size_t q=mapped_units/NGPU,r=mapped_units%NGPU;std::array<Code,NGPU+1>b{};std::size_t off=0;for(int d=0;d<NGPU;++d){int rel=(d-rotation+NGPU)%NGPU;off+=(q+std::size_t(rel<int(r)))*gran;b[d+1]=std::min<Code>(elements,Code(off/4));}return b;}
static std::array<Code,NGPU> segment_counts(const Spec&s,const std::array<Code,NGPU+1>&b){std::array<Code,NGPU>x{};Code sum=0;for(int d=0;d<NGPU;++d){x[d]=group_prefix(s,b[d+1])-group_prefix(s,b[d]);sum+=x[d];}if(sum!=s.size){std::fprintf(stderr,"segment count mismatch %llu != %llu\n",sum,s.size);std::exit(2);}return x;}
static std::vector<Group> build_groups(std::size_t gran){std::size_t mu=0,bu=0;auto mb=bounds(H[28][1],gran,0,mu);auto bb=bounds(H[27][1],gran,int(mu%NGPU),bu);(void)bu;std::vector<Group>out;out.reserve(16384);for(int wi=0;wi<2;++wi){int hi=wi?13:27,lo=wi?1:14;auto fp=candidates(28,hi,lo);fp.resize(13);for(std::uint32_t g=0;g<8192;++g){std::uint32_t mf,mo,bf,bo;masks(hi,lo,fp,g,mf,mo,bf,bo);auto ms=make_spec(28,mf,mo),bs=make_spec(27,bf,bo);auto ml=segment_counts(ms,mb),bl=segment_counts(bs,bb);Group x;x.win=wi;x.g=g;x.work=2*ms.size+bs.size;x.main=ms.size;x.block=bs.size;for(int d=0;d<NGPU;++d)x.local[d]=ml[d]+bl[d];out.push_back(x);}}return out;}
static bool before(const Group&a,const Group&b){if(a.work!=b.work)return a.work>b.work;if(a.main!=b.main)return a.main>b.main;if(a.block!=b.block)return a.block>b.block;return a.g<b.g;}
static Assign assign_window(std::vector<Group>v,bool locality){std::sort(v.begin(),v.end(),before);Assign a;Code total=0;for(auto const&x:v)total+=x.work;const Code cap=(total*10001ull+79999ull)/80000ull;for(auto const&x:v){int d=-1;if(!locality){d=0;for(int q=1;q<NGPU;++q)if(a.load[q]<a.load[d])d=q;}else{for(int q=0;q<NGPU;++q)if(a.load[q]+x.work<=cap){if(d<0||x.local[q]>x.local[d]||(x.local[q]==x.local[d]&&(a.load[q]<a.load[d]||(a.load[q]==a.load[d]&&q<d))))d=q;}if(d<0){d=0;for(int q=1;q<NGPU;++q)if(a.load[q]+x.work<a.load[d]+x.work)d=q;}}a.load[d]+=x.work;a.local[d]+=x.local[d];++a.count[d];}if(locality&&*std::max_element(a.load.begin(),a.load.end())>cap){std::fprintf(stderr,"locality load cap exceeded\n");std::exit(3);}return a;}
static Code sum8(const std::array<Code,NGPU>&a){Code z=0;for(Code x:a)z+=x;return z;}
static void run_gran(std::size_t gran,Code expect_base,Code expect_local){auto groups=build_groups(gran);Code base_local=0,new_local=0,total_states=0;for(int wi=0;wi<2;++wi){std::vector<Group>w;for(auto const&g:groups)if(g.win==wi){w.push_back(g);total_states+=g.main+g.block;}auto b=assign_window(w,false),n=assign_window(w,true);base_local+=sum8(b.local);new_local+=sum8(n.local);if(gran==(2ull<<20)){if(wi==0&&(sum8(b.local)!=65088158032ull||sum8(n.local)!=65615740636ull))std::exit(4);if(wi==1&&(sum8(b.local)!=65855784287ull||sum8(n.local)!=289524764151ull))std::exit(5);if(wi==0&&(n.count!=std::array<std::uint32_t,NGPU>{937,1454,412,752,3875,235,368,159}))std::exit(6);if(wi==1&&(n.count!=std::array<std::uint32_t,NGPU>{1768,2069,562,653,2010,545,435,150}))std::exit(7);}}
if(base_local!=expect_base||new_local!=expect_local||total_states!=1041470024054ull){std::fprintf(stderr,"granularity result mismatch gran=%zu base=%llu local=%llu total=%llu\n",gran,base_local,new_local,total_states);std::exit(8);}Code old_remote=total_states-base_local,new_remote=total_states-new_local;double reduction=100.0*double(old_remote-new_remote)/double(old_remote);std::printf("gran_kib=%zu baseline_local=%llu locality_local=%llu total=%llu baseline_local_pct=%.9f locality_local_pct=%.9f remote_reduction_pct=%.9f\n",gran/1024,base_local,new_local,total_states,100.0*double(base_local)/double(total_states),100.0*double(new_local)/double(total_states),reduction);if(reduction<24.60)std::exit(9);}
int main(){build_full();if(H[28][1]!=385719506620ull||H[27][1]!=135015505407ull)return 2;run_gran(64ull<<10,130943999629ull,355139357541ull);run_gran(2ull<<20,130943942319ull,355140504787ull);run_gran(16ull<<20,130937280355ull,355144011988ull);run_gran(64ull<<20,130937263199ull,355132752276ull);std::puts("b300-vmm-locality-static-assignment-proof OK load_cap_over_ideal=0.01pct granularity_robust=64KiB..64MiB remote_reduction_gt=24.60pct exact_prefix_dp=1");return 0;}
