#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <vector>
using U64 = std::uint64_t; using LD = long double; static constexpr int MAXW=28; static constexpr int S=MAXW+2;
static U64 choose_u64(int n,int k){if(k<0||k>n)return 0;k=std::min(k,n-k);U64 r=1;for(int i=1;i<=k;++i)r=r*U64(n-k+i)/U64(i);return r;}
static std::vector<std::vector<U64>> high_fixed_counts(int width){std::vector<std::vector<U64>> out(width+1,std::vector<U64>(MAXW+3));for(int k=0;k<=width;++k){std::vector<U64>cur(MAXW+3),nxt(MAXW+3);cur[1]=1;for(int step=0;step<k;++step){std::fill(nxt.begin(),nxt.end(),0);for(int h=0;h<=MAXW+1;++h)if(cur[h]){if(h+1<int(nxt.size()))nxt[h+1]+=cur[h];if(h>0)nxt[h-1]+=cur[h];}cur.swap(nxt);}out[k]=std::move(cur);}return out;}
static std::vector<std::vector<U64>> low_fixed_counts(int width){std::vector<std::vector<U64>> out(width+1,std::vector<U64>(MAXW+3));for(int k=0;k<=width;++k){for(int start=0;start<=MAXW+1;++start){std::vector<U64>cur(MAXW+3),nxt(MAXW+3);cur[start]=1;for(int step=0;step<k;++step){std::fill(nxt.begin(),nxt.end(),0);for(int h=0;h<=MAXW+1;++h)if(cur[h]){if(h+1<int(nxt.size()))nxt[h+1]+=cur[h];if(h>0)nxt[h-1]+=cur[h];}cur.swap(nxt);}out[k][start]=cur[0];}}return out;}
static std::vector<U64> high_all_counts(int width){std::vector<U64>cur(MAXW+3),nxt(MAXW+3);cur[1]=1;for(int step=0;step<width;++step){std::fill(nxt.begin(),nxt.end(),0);for(int h=0;h<=MAXW+1;++h)if(cur[h]){nxt[h]+=cur[h];if(h+1<int(nxt.size()))nxt[h+1]+=cur[h];if(h>0)nxt[h-1]+=cur[h];}cur.swap(nxt);}return cur;}
static std::vector<U64> low_all_counts(int width){std::vector<U64>out(MAXW+3);for(int start=0;start<=MAXW+1;++start){std::vector<U64>cur(MAXW+3),nxt(MAXW+3);cur[start]=1;for(int step=0;step<width;++step){std::fill(nxt.begin(),nxt.end(),0);for(int h=0;h<=MAXW+1;++h)if(cur[h]){nxt[h]+=cur[h];if(h+1<int(nxt.size()))nxt[h+1]+=cur[h];if(h>0)nxt[h-1]+=cur[h];}cur.swap(nxt);}out[start]=cur[0];}return out;}
static std::vector<U64> greedy_bins(int bits,const std::vector<U64>&w,int ngpu){struct Item{U64 w;uint32_t m;};std::vector<Item>it;it.reserve(size_t(1)<<bits);for(uint32_t m=0;m<(uint32_t(1)<<bits);++m)it.push_back({w[__builtin_popcount(m)],m});std::sort(it.begin(),it.end(),[](auto&a,auto&b){return a.w!=b.w?a.w>b.w:a.m<b.m;});std::vector<U64>b(ngpu);for(auto&x:it)*std::min_element(b.begin(),b.end())+=x.w;return b;}
static LD gib(LD b){return b/LD(U64(1)<<30);} static LD mib(LD b){return b/LD(U64(1)<<20);}
int main(int argc,char**argv){int W=argc>1?atoi(argv[1]):28,low=argc>2?atoi(argv[2]):14,ngpu=argc>3?atoi(argv[3]):8;LD usable=argc>4?strtold(argv[4],nullptr):268.59L;int high=W-1-low;if(W<4||W>MAXW||low<1||high<1||low>=16||high>=16||ngpu<1||ngpu>8)return 1;auto hfk=high_fixed_counts(high);auto lfk=low_fixed_counts(low);std::vector<std::vector<U64>>pair(high+1,std::vector<U64>(low+1));for(int kh=0;kh<=high;++kh)for(int kl=0;kl<=low;++kl){U64 z=0;for(int he=0;he<=high+1;++he){U64 a=hfk[kh][he];if(!a)continue;z+=2*a*lfk[kl][he];if(he+1<=MAXW+1)z+=a*lfk[kl][he+1];if(he>0)z+=a*lfk[kl][he-1];}pair[kh][kl]=z;}std::vector<U64>hw(high+1),lw(low+1);U64 total=0;for(int kh=0;kh<=high;++kh)for(int kl=0;kl<=low;++kl){U64 z=pair[kh][kl];hw[kh]+=choose_u64(low,kl)*z;lw[kl]+=choose_u64(high,kh)*z;total+=choose_u64(high,kh)*choose_u64(low,kl)*z;}auto bins=greedy_bins(high,hw,ngpu);U64 maxauth=*std::max_element(bins.begin(),bins.end()),maxhg=*std::max_element(hw.begin(),hw.end()),maxlg=*std::max_element(lw.begin(),lw.end());auto hca=high_all_counts(high);auto lca=low_all_counts(low);U64 high_all=std::accumulate(hca.begin(),hca.end(),U64(0)),low_all=std::accumulate(lca.begin(),lca.end(),U64(0));U64 low_dense=U64(1)<<(2*low),high_dense=U64(1)<<(2*high),low_masks=U64(1)<<low,high_masks=U64(1)<<high;LD factor=LD(4)*LD(2*low_all+low_masks*S+low_dense+2*high_all+high_masks*S+high_dense);U64 main_blocks=U64(3)*U64(high+2),block_blocks=U64(high+2);LD meta=LD(high_masks)+LD(8)*LD(2*high_masks+high_masks*main_blocks+high_masks*block_blocks)+LD(4)*LD(high_all)+LD(4)*LD(low_masks*S);U64 hma=0,lma=0,hba=0,lba=0;for(int he=0;he<=high+1;++he){for(int cv=0;cv<3;++cv){int hs=he+(cv==2?1:cv==1?-1:0);if(hs<0||hs>low+1||!hca[he]||!lca[hs])continue;hma+=hca[he];lma+=lca[hs];}if(he<=low+1&&hca[he]&&lca[he]){hba+=hca[he];lba+=lca[he];}}LD hd=LD(4)*LD(high)*LD(hma+hba),ld=LD(4)*LD(low)*LD(lma+lba),auth=LD(maxauth)*4,lowmd=LD(maxhg)*4,highmd=LD(maxlg)*4,v01s=std::max(lowmd,2*highmd),v03s=std::max(lowmd,highmd),v04s=highmd,common=auth+factor+meta,v01=common+v01s,v02=v01+hd,v03=common+v03s+hd,v04=common+v04s+hd+ld;std::cout<<std::fixed<<std::setprecision(6)<<"total_states="<<total<<"\nmax_auth_gpu_gib="<<double(gib(auth))<<"\nlow_md_gib="<<double(gib(lowmd))<<" high_md_gib="<<double(gib(highmd))<<"\nfactor_tables_mib="<<double(mib(factor))<<" meta_mib="<<double(mib(meta))<<" low_begin_mib="<<double(mib(LD(4)*LD(low_masks*S)))<<"\nhighdesc_mib="<<double(mib(hd))<<" lowdesc_mib="<<double(mib(ld))<<"\nv01="<<double(gib(v01))<<" v02="<<double(gib(v02))<<" v03="<<double(gib(v03))<<" v04="<<double(gib(v04))<<" headroom="<<double(usable-gib(v04))<<"\n";return gib(v04)>=usable?2:0;}
