#include <cstdint>
#include <iostream>
#include <random>
#include <stdexcept>
#include <unordered_map>
#include <vector>
using MateID=uint64_t; enum V:uint8_t{N=0,R=1,L=2};
static V get(MateID m,int p){return V((m>>(2*p))&3);} static MateID setv(MateID m,int p,V v){auto q=MateID(3)<<(2*p);return(m&~q)|(MateID(v)<<(2*p));}
static MateID setp(MateID m,int p,V a,V b){return setv(setv(m,p,a),p-1,b);} static MateID shrink(MateID m,int k){MateID lo=k?((MateID(1)<<(2*k))-1):0;return ((m&~lo)>>2)|(m&lo);} static MateID insertN(MateID m,int k){MateID lo=k?((MateID(1)<<(2*k))-1):0;return ((m&~lo)<<2)|(m&lo);}
static void gen(int pos,int h,MateID m,std::vector<MateID>&o){if(pos<0){if(h==0)o.push_back(m);return;}gen(pos-1,h,setv(m,pos,N),o);if(h>0)gen(pos-1,h-1,setv(m,pos,R),o);gen(pos-1,h+1,setv(m,pos,L),o);} static std::vector<MateID> states(int W){std::vector<MateID>o;gen(W-1,1,0,o);return o;}
static MateID closeLL(MateID m,int p){m=setp(m,p,N,N);int q=p-1,s=1;while(s){--q;if(q<0)throw std::runtime_error("LL");auto v=get(m,q);if(v==L)++s;else if(v==R)--s;}return setv(m,q,L);} static MateID closeRR(MateID m,int p,int W){m=setp(m,p,N,N);int q=p,s=1;while(s){++q;if(q>=W)throw std::runtime_error("RR");auto v=get(m,q);if(v==L)--s;else if(v==R)++s;}return setv(m,q,R);} static uint32_t add(uint32_t a,uint32_t b,uint32_t mod){uint64_t x=uint64_t(a)+b;return uint32_t(x>=mod?x-mod:x);}
struct Space{std::vector<MateID> m,d;std::unordered_map<MateID,size_t> mi,di;Space(int W):m(states(W)),d(states(W-1)){for(size_t i=0;i<m.size();++i)mi[m[i]]=i;for(size_t i=0;i<d.size();++i)di[d[i]]=i;}};
static void ref_step(Space const&s,int W,int p,std::vector<uint32_t> const&M,std::vector<uint32_t> const&D,std::vector<uint32_t>&nm,std::vector<uint32_t>&nd,uint32_t mod){nm=M;nd.assign(D.size(),0);for(size_t i=0;i<M.size();++i){uint32_t c=M[i];MateID m=s.m[i],t=m;auto a=get(m,p),b=get(m,p-1);if(a==N&&b==N){t=setp(m,p,L,R);nm[s.mi.at(t)]=add(nm[s.mi.at(t)],c,mod);}else if(a==N&&(b==R||b==L)){if(p==1){t=setp(m,p,b==R?R:L,N);nm[s.mi.at(t)]=add(nm[s.mi.at(t)],c,mod);}else{auto j=s.di.at(shrink(m,p));nd[j]=add(nd[j],c,mod);}}else if(a==R&&b==N){t=setp(m,p,N,R);nm[s.mi.at(t)]=add(nm[s.mi.at(t)],c,mod);}else if(a==L&&b==N){t=setp(m,p,N,L);nm[s.mi.at(t)]=add(nm[s.mi.at(t)],c,mod);}else if(a==L&&b==L){t=closeLL(m,p);if(p==1)nm[s.mi.at(t)]=add(nm[s.mi.at(t)],c,mod);else{auto j=s.di.at(shrink(t,p-1));nd[j]=add(nd[j],c,mod);}}else if(a==R&&b==R){t=closeRR(m,p,W);if(p==1)nm[s.mi.at(t)]=add(nm[s.mi.at(t)],c,mod);else{auto j=s.di.at(shrink(t,p-1));nd[j]=add(nd[j],c,mod);}}else if(a==R&&b==L){t=setp(m,p,N,N);if(p==1)nm[s.mi.at(t)]=add(nm[s.mi.at(t)],c,mod);else{auto j=s.di.at(shrink(t,p-1));nd[j]=add(nd[j],c,mod);}}}
 for(size_t j=0;j<D.size();++j){MateID t=insertN(s.d[j],p);nm[s.mi.at(t)]=add(nm[s.mi.at(t)],D[j],mod);}}
static void orbit_step(Space const&s,int W,int p,std::vector<uint32_t>&M,std::vector<uint32_t>&D,uint32_t mod){for(size_t i=0;i<M.size();++i){MateID m=s.m[i];auto a=get(m,p),b=get(m,p-1);if(a!=N||!(b==N||b==R||b==L))continue;auto dj=s.di.at(shrink(m,p));uint32_t c=M[i],d=D[dj];if(b==N){MateID t=setp(m,p,L,R);auto j=s.mi.at(t);M[j]=add(M[j],c,mod);M[i]=add(c,d,mod);D[dj]=0;}else{MateID t=setp(m,p,b==R?R:L,N);auto j=s.mi.at(t);uint32_t cc=M[j],all=add(add(c,cc,mod),d,mod);if(p==1){M[i]=all;M[j]=add(c,cc,mod);D[dj]=0;}else{M[i]=all;D[dj]=c;}}}
 for(size_t i=0;i<M.size();++i){uint32_t c=M[i];MateID m=s.m[i],t=m;auto a=get(m,p),b=get(m,p-1);if(a==L&&b==L)t=closeLL(m,p);else if(a==R&&b==R)t=closeRR(m,p,W);else if(a==R&&b==L)t=setp(m,p,N,N);else continue;if(p==1){auto j=s.mi.at(t);M[j]=add(M[j],c,mod);}else{auto j=s.di.at(shrink(t,p-1));D[j]=add(D[j],c,mod);}}}
int main(){constexpr uint32_t MOD=4294967291u;std::mt19937_64 rng(1618);for(int W=3;W<=11;++W){Space s(W);for(int p=1;p<W;++p)for(int tr=0;tr<4;++tr){std::vector<uint32_t>M(s.m.size()),D(s.d.size());for(auto&x:M)x=rng()%MOD;for(auto&x:D)x=rng()%MOD;std::vector<uint32_t>rm,rd;ref_step(s,W,p,M,D,rm,rd,MOD);auto im=M,id=D;orbit_step(s,W,p,im,id,MOD);if(im!=rm||id!=rd){std::cerr<<"FAIL W="<<W<<" p="<<p<<" trial="<<tr<<"\n";return 1;}}std::cout<<"W="<<W<<" main="<<s.m.size()<<" block="<<s.d.size()<<" all_p=OK\n";}}
