#define RECT_SEQUENCE_NO_MAIN
#define BM_PRIME 998244353ULL
#include "rect_sequence_bm.cpp"
using namespace std;

static constexpr uint32_t MODN=998244353u, GROOT=3u;
static uint32_t qpow(uint32_t a,uint32_t e){uint64_t r=1,x=a;while(e){if(e&1)r=r*x%MODN;x=x*x%MODN;e>>=1;}return r;}
static void ntt(vector<uint32_t>&a,bool inv){int n=a.size();for(int i=1,j=0;i<n;i++){int b=n>>1;for(;j&b;b>>=1)j^=b;j^=b;if(i<j)swap(a[i],a[j]);}for(int len=2;len<=n;len<<=1){uint32_t wlen=qpow(GROOT,(MODN-1)/len);if(inv)wlen=qpow(wlen,MODN-2);for(int i=0;i<n;i+=len){uint64_t w=1;for(int j=0;j<len/2;j++){uint32_t u=a[i+j],v=w*a[i+j+len/2]%MODN;uint32_t x=u+v;if(x>=MODN)x-=MODN;uint32_t y=u>=v?u-v:u+MODN-v;a[i+j]=x;a[i+j+len/2]=y;w=w*wlen%MODN;}}}if(inv){uint32_t ni=qpow(n,MODN-2);for(auto&x:a)x=(uint64_t)x*ni%MODN;}}
static vector<uint32_t> conv(vector<uint32_t>a,vector<uint32_t>b){if(a.empty()||b.empty())return{};int z=a.size()+b.size()-1,n=1;while(n<z)n<<=1;a.resize(n);b.resize(n);ntt(a,false);ntt(b,false);for(int i=0;i<n;i++)a[i]=(uint64_t)a[i]*b[i]%MODN;ntt(a,true);a.resize(z);return a;}
static uint32_t bostan(const vector<uint64_t>&init,const vector<uint64_t>&rec,unsigned long long n){int d=rec.size();if(n<init.size())return init[n];vector<uint32_t>Q(d+1),Pp(d);Q[0]=1;for(int i=1;i<=d;i++)Q[i]=rec[i-1]?MODN-(uint32_t)rec[i-1]:0;for(int k=0;k<d;k++){uint64_t z=init[k];for(int i=1;i<=k;i++)z=(z+MODN-(uint64_t)rec[i-1]*init[k-i]%MODN)%MODN;Pp[k]=z;}while(n){vector<uint32_t>qm=Q;for(int i=1;i<(int)qm.size();i+=2)if(qm[i])qm[i]=MODN-qm[i];auto s=conv(Pp,qm),t=conv(Q,qm);vector<uint32_t>np,nq;np.reserve((s.size()+1)/2);for(size_t i=n&1;i<s.size();i+=2)np.push_back(s[i]);nq.reserve((t.size()+1)/2);for(size_t i=0;i<t.size();i+=2)nq.push_back(t[i]);Pp.swap(np);Q.swap(nq);n>>=1;}return (uint64_t)Pp[0]*qpow(Q[0],MODN-2)%MODN;}
int main(int argc,char**argv){int W=argc>1?atoi(argv[1]):10,H=argc>2?atoi(argv[2]):12000;unsigned long long qh=argc>3?strtoull(argv[3],nullptr,10):1000000000000000000ULL;auto a=seq(W,H);auto c=BM(a);auto t0=chrono::steady_clock::now();auto z=bostan(a,c,qh-1);auto t1=chrono::steady_clock::now();auto k0=chrono::steady_clock::now();auto zk=nthRec(a,c,qh-1);auto k1=chrono::steady_clock::now();cout<<"W="<<W<<" degree="<<c.size()<<" bostan="<<z<<" kitamasa="<<zk<<" equal="<<(z==zk)<<" bostan_ms="<<chrono::duration<double,milli>(t1-t0).count()<<" kitamasa_ms="<<chrono::duration<double,milli>(k1-k0).count()<<"\n";}
