#define ROW8_CANONICAL_TRIE_NO_MAIN 1
#include "row8_canonical_trie_verify.cpp"
#include <chrono>
#include <functional>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
static constexpr uint32_t Q=1000000007u;
static uint32_t ipow(uint32_t a,uint64_t e){uint64_t r=1,x=a;while(e){if(e&1)r=(__uint128_t)r*x%Q;x=(__uint128_t)x*x%Q;e>>=1;}return r;}
static void recw(int p,int nt,int bal,std::string&w,std::vector<std::pair<Packed,std::string>>&o){if(p==8){if(!nt&&!bal){Packed x;if(enc(w,x))o.push_back({x,w});}return;}if(nt>8-p)return;w[p]='N';recw(p+1,nt,bal,w,o);w[p]='U';recw(p+1,nt,bal+1,w,o);w[p]='D';recw(p+1,nt,bal-1,w,o);if(nt&&bal==0){w[p]='T';recw(p+1,nt-1,0,w,o);}}
static std::vector<std::pair<Packed,std::string>> words3(){std::string w(8,'N');std::vector<std::pair<Packed,std::string>>v;recw(0,3,0,w,v);std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.first<b.first;});v.erase(std::unique(v.begin(),v.end(),[](auto&a,auto&b){return a.first==b.first;}),v.end());return v;}
static bool oldhard(std::string const&w){int bal=0,n=0;auto fl=[&](){bool z=n>=2;bal=n=0;return z;};for(char c:w){if(c=='T'){if(fl())return true;continue;}if(c=='N')continue;int d=c=='U'?1:-1;if(bal==0&&d<0)++n;bal+=d;}return fl();}
static std::string dsig(Packed p){State s=unpack(p);std::set<int>sk;for(int i=0;i<s.sp;++i)sk.insert(s.stack[i]);std::ostringstream o;o<<"T=";for(int i=0;i<8;++i)if(s.deg[i]&&sk.count(s.comp[i]))o<<i;std::map<int,std::vector<int>>po;for(int i=0;i<8;++i)if(s.deg[i]&&!sk.count(s.comp[i]))po[s.comp[i]].push_back(i);o<<" P=";for(auto const&[q,v]:po)if(v.size()==2)o<<v[0]<<'-'<<v[1]<<':'<<int(s.status[q]&1)<<',';return o.str();}
int main(){MODP=Q;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::vector<Packed>hs;for(auto&p:all)if(unpack(p).sp==3)hs.push_back(p);auto ws=words3();if(ws.size()!=888)throw std::runtime_error("words");std::vector<char>bad(888);int bc=0;for(int j=0;j<888;++j)if(oldhard(ws[j].second)){bad[j]=1;++bc;}if(bc!=32)throw std::runtime_error("bad count");
 std::vector<std::pair<Packed,int>> gp;std::vector<char>isgood(hs.size());for(int j=0;j<888;++j)if(!bad[j]){auto it=std::lower_bound(hs.begin(),hs.end(),ws[j].first);if(it==hs.end()||!(*it==ws[j].first))throw std::runtime_error("missing");int i=it-hs.begin();isgood[i]=1;gp.push_back({ws[j].first,j});}std::sort(gp.begin(),gp.end(),[](auto&a,auto&b){return a.first<b.first;});std::vector<int>nid(hs.size(),-1),nts;for(int i=0;i<(int)hs.size();++i)if(!isgood[i]){nid[i]=nts.size();nts.push_back(i);}int nn=nts.size();std::vector<std::vector<std::pair<int,uint32_t>>>pred(888);size_t edges=0,tg=0;auto t=std::chrono::steady_clock::now();for(int i=0;i<(int)hs.size();++i){WVec v{{hs[i],1}};auto z=wcolumn(std::move(v),8,false,0);edges+=z.size();if(!isgood[i])for(auto&e:z){auto it=std::lower_bound(gp.begin(),gp.end(),e.p,[](auto&a,Packed const&b){return a.first<b;});if(it!=gp.end()&&it->first==e.p){pred[it->second].push_back({nid[i],e.v});++tg;}}if((i&4095)==0)std::cerr<<"tr "<<i<<"/"<<hs.size()<<"\n";}double sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-t).count();std::cout<<"h3_states="<<hs.size()<<" good=856 non="<<nn<<" edges="<<edges<<" togood="<<tg<<" trans_s="<<sec<<"\n";
 struct B{int p,j;std::vector<uint32_t>v;};std::vector<B>bs;for(int j=0;j<888;++j)if(!bad[j]){std::vector<uint32_t>y(nn);for(auto[i,c]:pred[j])y[i]=c;for(auto const&b:bs){uint32_t f=y[b.p];if(!f)continue;for(int k=b.p;k<nn;++k)if(b.v[k])y[k]=(y[k]+Q-(__uint128_t)f*b.v[k]%Q)%Q;}int p=-1;for(int k=0;k<nn;++k)if(y[k]){p=k;break;}if(p<0)continue;uint32_t iv=ipow(y[p],Q-2);for(int k=p;k<nn;++k)if(y[k])y[k]=(__uint128_t)y[k]*iv%Q;bs.push_back({p,j,std::move(y)});std::cout<<"new="<<bs.size()<<" from="<<j<<" word="<<ws[j].second<<" pivot="<<p<<"\n";if(bs.size()==32)break;}
 std::map<size_t,int>nzh;std::cout<<"extra_rank="<<bs.size()<<"\n";for(size_t bi=0;bi<bs.size();++bi){size_t nz=0;for(auto x:bs[bi].v)if(x)++nz;++nzh[nz];std::cout<<"B "<<bi<<" from="<<bs[bi].j<<" word="<<ws[bs[bi].j].second<<" nz="<<nz<<"\n";int sh=0;for(int k=0;k<nn&&sh<8;++k)if(bs[bi].v[k]){int64_t c=bs[bi].v[k]<=Q/2?bs[bi].v[k]:(int64_t)bs[bi].v[k]-Q;std::cout<<" c="<<c<<" "<<dsig(hs[nts[k]])<<"\n";++sh;}}
 std::cout<<"nz_hist";for(auto[n,c]:nzh)std::cout<<' '<<n<<':'<<c;std::cout<<'\n';return bs.size()==32?0:1;}
