#define ROW8_RAW_PREFIX_NO_MAIN 1
#include "row8_raw_prefix_vector.cpp"
#include <fstream>
#include <filesystem>

static constexpr int D[9]={1107,1640,1428,888,420,152,42,8,1};
static constexpr int DEL[3]={0,-1,1};
struct Cache {std::array<std::array<std::vector<uint32_t>,9>,3> M;};
static Cache load_cache(std::string path,uint32_t mod){
 std::ifstream in(path,std::ios::binary);if(!in)throw std::runtime_error("cache open");char magic[8];uint32_t ver,pm,ds[9];uint64_t fp,abi,an,bn,cnt[27],hash;in.read(magic,8);in.read((char*)&ver,4);in.read((char*)&pm,4);in.read((char*)&fp,8);in.read((char*)&abi,8);in.read((char*)ds,36);in.read((char*)&an,8);in.read((char*)&bn,8);in.read((char*)cnt,sizeof(cnt));in.read((char*)&hash,8);if(std::string(magic,7)!="R8MDC02"||ver!=2||pm!=mod)throw std::runtime_error("cache header");in.seekg((std::streamoff)(4*(an+bn)),std::ios::cur);Cache z;int q=0;for(int a=0;a<3;++a)for(int h=0;h<9;++h){z.M[a][h].resize(cnt[q++]);if(!z.M[a][h].empty())in.read((char*)z.M[a][h].data(),z.M[a][h].size()*4);}if(!in)throw std::runtime_error("cache read");return z;
}
static std::array<std::vector<uint32_t>,9> load_pc(){std::ifstream in("src/cuda/b300/row8_pivots_w19.bin",std::ios::binary);char m[8];uint32_t v,ds[9];in.read(m,8);in.read((char*)&v,4);in.read((char*)ds,36);std::array<std::vector<uint32_t>,9> p;for(int h=0;h<9;++h){p[h].resize(ds[h]);for(auto&x:p[h]){uint32_t sc;in.read((char*)&x,4);in.read((char*)&sc,4);}}return p;}
static WVec linear_combo(std::vector<WVec> const&basis,uint32_t const*coef,int n){WVec z;size_t cap=0;for(int j=0;j<n;++j)if(coef[j])cap+=basis[j].size();z.reserve(cap);for(int j=0;j<n;++j){uint32_t c=coef[j];if(!c)continue;for(auto const&e:basis[j])z.push_back({e.p,(uint32_t)((__uint128_t)e.v*c%MODP)});}wnorm(z);return z;}
static uint64_t whash(WVec const&v){uint64_t h=1469598103934665603ULL;for(auto const&e:v){for(auto x:e.p.w)for(int b=0;b<8;++b){h^=uint8_t(x>>(8*b));h*=1099511628211ULL;}for(int b=0;b<4;++b){h^=uint8_t(e.v>>(8*b));h*=1099511628211ULL;}}return h;}
int main(int argc,char**argv){MODP=argc>1?std::strtoul(argv[1],nullptr,10):1000000007u;int h=argc>2?std::atoi(argv[2]):8;int i=argc>3?std::atoi(argv[3]):0;std::string cp;for(auto const&e:std::filesystem::directory_iterator("work/row8_mod_cache")){auto s=e.path().filename().string();if(s.find("row8_mod_"+std::to_string(MODP)+"_") == 0 && s.find("_52384d4443414249.bin")!=std::string::npos){cp=e.path();break;}}if(cp.empty())throw std::runtime_error("cache not found");auto C=load_cache(cp,MODP); auto P=load_pc();if(i<0||i>=D[h])return 2;std::array<std::vector<WVec>,9> bases;auto getbasis=[&](int hh)->std::vector<WVec>&{auto&b=bases[hh];if(b.empty()){b.reserve(D[hh]);for(int j=0;j<D[hh];++j){auto t=std::chrono::steady_clock::now();b.push_back(prefix_vec(P[hh][j]));if((j&31)==0)std::cerr<<"basis h="<<hh<<" "<<j+1<<"/"<<D[hh]<<" support="<<b.back().size()<<"\n";}}return b;};auto&srcs=getbasis(h);for(int a=0;a<3;++a){int h2=h+DEL[a];if(h2<0||h2>=9)continue;auto actual=wcolumn(srcs[i],8,false,a);auto&dst=getbasis(h2);auto const&M=C.M[a][h];auto predicted=linear_combo(dst,M.data()+size_t(i)*D[h2],D[h2]);bool ok=actual==predicted;std::cout<<"mod="<<MODP<<" h="<<h<<" i="<<i<<" sym="<<a<<" h2="<<h2<<" actual_n="<<actual.size()<<" pred_n="<<predicted.size()<<" actual_hash="<<std::hex<<whash(actual)<<" pred_hash="<<whash(predicted)<<std::dec<<" exact="<<ok<<"\n";if(!ok)return 1;}return 0;}
