#define ROW8_H2_PARTITION_NO_MAIN 1
#include "row8_h2_relation_partition.cpp"
#include <fstream>
#include <iostream>
static uint32_t Q=1000000007u;
struct HH{char m[8];uint32_t ver,mod,h,rows,states;};
static std::vector<uint32_t> loadDense(std::string p,int h,int rows,int states){std::ifstream in(p,std::ios::binary);HH x{};in.read((char*)&x,sizeof(x));if(!in||x.mod!=Q||x.h!=(uint32_t)h||x.rows!=(uint32_t)rows||x.states!=(uint32_t)states)throw std::runtime_error("hdr "+p);std::vector<uint32_t>A((size_t)rows*states);in.read((char*)A.data(),A.size()*4);if(!in)throw std::runtime_error("read");return A;}
static std::vector<std::vector<std::pair<int,uint32_t>>> tr(std::vector<Packed>const&s,std::vector<Packed>const&t){std::vector<std::vector<std::pair<int,uint32_t>>>T(s.size());size_t e=0;for(int i=0;i<(int)s.size();++i){WVec v{{s[i],1}};auto z=wcolumn(std::move(v),8,false,1);for(auto&x:z){auto it=std::lower_bound(t.begin(),t.end(),x.p);if(it==t.end()||!(*it==x.p))throw std::runtime_error("target");T[i].push_back({int(it-t.begin()),x.v});++e;}}std::cout<<"R_edges src="<<s.size()<<" dst="<<t.size()<<" edges="<<e<<"\n";return T;}
struct Reducer{int n;std::vector<std::vector<uint32_t>>rows;std::vector<int>at;Reducer(int nn):n(nn),at(nn,-1){}void addRow(std::vector<uint32_t>r){for(int p=0;p<n;++p)if(r[p]&&at[p]>=0){auto const&b=rows[at[p]];uint32_t f=r[p];for(int k=p;k<n;++k)if(b[k])r[k]=(r[k]+Q-(__uint128_t)f*b[k]%Q)%Q;}int p=-1;for(int k=0;k<n;++k)if(r[k]){p=k;break;}if(p<0)throw std::runtime_error("dependent basis input");uint64_t e=Q-2,x=r[p],iv=1;while(e){if(e&1)iv=(__uint128_t)iv*x%Q;x=(__uint128_t)x*x%Q;e>>=1;}for(int k=p;k<n;++k)if(r[k])r[k]=(__uint128_t)r[k]*iv%Q;at[p]=rows.size();rows.push_back(std::move(r));}bool inSpan(std::vector<uint32_t>y)const{for(int p=0;p<n;++p)if(y[p]&&at[p]>=0){auto const&b=rows[at[p]];uint32_t f=y[p];for(int k=p;k<n;++k)if(b[k])y[k]=(y[k]+Q-(__uint128_t)f*b[k]%Q)%Q;}for(auto x:y)if(x)return false;return true;}};
static std::vector<uint32_t> phi2full(std::vector<Packed>const&h2){auto ws=words2();std::set<int>bad;{std::ifstream in("work/formal-probes/canonical-matrix/h2_actual_bad_indices.txt");int x;while(in>>x)bad.insert(x);}std::vector<uint32_t>P((size_t)1428*h2.size());int r=0;for(int j=0;j<(int)ws.size();++j)if(!bad.count(j)){int i=std::lower_bound(h2.begin(),h2.end(),ws[j].first)-h2.begin();P[(size_t)r*h2.size()+i]=1;++r;}std::ifstream in("work/formal-probes/dual-basis/Phi_h2_extra_mod"+std::to_string(Q)+".bin",std::ios::binary);HH x{};in.read((char*)&x,sizeof(x));if(x.rows!=120||x.states!=h2.size())throw std::runtime_error("p2");in.read((char*)(P.data()+(size_t)1308*h2.size()),(size_t)120*h2.size()*4);return P;}
int main(int argc,char**argv){if(argc>1)Q=std::strtoul(argv[1],nullptr,10);MODP=Q;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::array<std::vector<Packed>,3>H;for(auto&p:all){int h=unpack(p).sp;if(h<=2)H[h].push_back(p);}auto P0=loadDense("work/formal-probes/dual-basis/Phi_h0_mod"+std::to_string(Q)+".bin",0,1107,H[0].size());auto P1=loadDense("work/formal-probes/dual-basis/Phi_h1_mod"+std::to_string(Q)+".bin",1,1640,H[1].size());auto P2=phi2full(H[2]);
 auto T10=tr(H[1],H[0]);Reducer R1(H[1].size());for(int r=0;r<1640;++r)R1.addRow(std::vector<uint32_t>(P1.begin()+(size_t)r*H[1].size(),P1.begin()+(size_t)(r+1)*H[1].size()));int bad10=0;for(int f=0;f<1107;++f){auto pf=P0.data()+(size_t)f*H[0].size();std::vector<uint32_t>y(H[1].size());for(int i=0;i<(int)H[1].size();++i){uint64_t z=0;for(auto[t,c]:T10[i])z=(z+(uint64_t)c*pf[t])%Q;y[i]=z;}if(!R1.inSpan(std::move(y))){if(bad10<8)std::cerr<<"h1R missing f="<<f<<"\n";++bad10;}}
 auto T21=tr(H[2],H[1]); // specialized reducer for Phi2 to avoid rebuilding 1428 dense rows through Gaussian.
 std::vector<int>goodPos;auto ws=words2();std::set<int>badidx;{std::ifstream in("work/formal-probes/canonical-matrix/h2_actual_bad_indices.txt");int x;while(in>>x)badidx.insert(x);}for(int j=0;j<(int)ws.size();++j)if(!badidx.count(j))goodPos.push_back(std::lower_bound(H[2].begin(),H[2].end(),ws[j].first)-H[2].begin());std::vector<char>isg(H[2].size());for(int x:goodPos)isg[x]=1;std::vector<int>non;for(int i=0;i<(int)H[2].size();++i)if(!isg[i])non.push_back(i);Reducer Rex(non.size());for(int r=1308;r<1428;++r){std::vector<uint32_t>v(non.size());for(int k=0;k<(int)non.size();++k)v[k]=P2[(size_t)r*H[2].size()+non[k]];Rex.addRow(std::move(v));}int bad21=0;for(int f=0;f<1640;++f){auto pf=P1.data()+(size_t)f*H[1].size();std::vector<uint32_t>y(H[2].size());for(int i=0;i<(int)H[2].size();++i){uint64_t z=0;for(auto[t,c]:T21[i])z=(z+(uint64_t)c*pf[t])%Q;y[i]=z;}std::vector<uint32_t>yn(non.size());for(int k=0;k<(int)non.size();++k)yn[k]=y[non[k]];if(!Rex.inSpan(std::move(yn))){if(bad21<8)std::cerr<<"h2R missing f="<<f<<"\n";++bad21;}}
 std::cout<<"h1_R_bad="<<bad10<<"/1107 h2_R_bad="<<bad21<<"/1640 all_R_closed="<<(bad10==0&&bad21==0)<<"\n";return bad10||bad21?1:0;}
