#define ROW8_H2_PARTITION_NO_MAIN 1
#include "row8_h2_relation_partition.cpp"
#include <deque>
#include <fstream>
#include <iostream>
static uint32_t Q=1000000007u;
static uint32_t invq(uint32_t a){uint64_t e=Q-2,r=1,x=a;while(e){if(e&1)r=(__uint128_t)r*x%Q;x=(__uint128_t)x*x%Q;e>>=1;}return r;}
struct GB{int p,depth;std::vector<uint32_t>v;};
struct Basis{int n;std::vector<GB>b;std::vector<int>at;std::deque<int>q;Basis(int nn):n(nn),at(nn,-1){}bool add(std::vector<uint32_t>y,int dep){for(int p=0;p<n;++p)if(y[p]&&at[p]>=0){auto const&z=b[at[p]];uint32_t f=y[p];for(int k=p;k<n;++k)if(z.v[k])y[k]=(y[k]+Q-(__uint128_t)f*z.v[k]%Q)%Q;}int p=-1;for(int k=0;k<n;++k)if(y[k]){p=k;break;}if(p<0)return false;uint32_t iv=invq(y[p]);for(int k=p;k<n;++k)if(y[k])y[k]=(__uint128_t)y[k]*iv%Q;int id=b.size();b.push_back({p,dep,std::move(y)});at[p]=id;q.push_back(id);return true;}};
static std::vector<std::vector<std::pair<int,uint32_t>>> trans(std::vector<Packed>const&src,std::vector<Packed>const&dst,int sym){std::vector<std::vector<std::pair<int,uint32_t>>>T(src.size());size_t e=0;for(int i=0;i<(int)src.size();++i){WVec v{{src[i],1}};auto z=wcolumn(std::move(v),8,false,sym);for(auto&x:z){auto it=std::lower_bound(dst.begin(),dst.end(),x.p);if(it==dst.end()||!(*it==x.p))throw std::runtime_error("target missing");T[i].push_back({int(it-dst.begin()),x.v});++e;}if((i&1023)==0)std::cerr<<"tr sym="<<sym<<" "<<i<<"/"<<src.size()<<"\n";}std::cerr<<"edges sym="<<sym<<" "<<e<<"\n";return T;}
static std::vector<uint32_t> loadPhi2(std::vector<Packed>const&h2){auto ws=words2();std::set<int>bad;{std::ifstream in("work/formal-probes/canonical-matrix/h2_actual_bad_indices.txt");int x;while(in>>x)bad.insert(x);}std::vector<uint32_t>P((size_t)1428*h2.size());int r=0;for(int j=0;j<(int)ws.size();++j)if(!bad.count(j)){int i=std::lower_bound(h2.begin(),h2.end(),ws[j].first)-h2.begin();P[(size_t)r*h2.size()+i]=1;++r;}if(r!=1308)throw std::runtime_error("good1308");struct HH{char m[8];uint32_t ver,mod,h,rows,states;}hh{};std::ifstream in("work/formal-probes/dual-basis/Phi_h2_extra_mod"+std::to_string(Q)+".bin",std::ios::binary);in.read((char*)&hh,sizeof(hh));if(!in||hh.mod!=Q||hh.h!=2||hh.rows!=120||hh.states!=h2.size())throw std::runtime_error("phi2 hdr");in.read((char*)(P.data()+(size_t)1308*h2.size()),(size_t)120*h2.size()*4);if(!in)throw std::runtime_error("phi2 read");return P;}
static void savePhi(std::string path,int h,std::vector<GB>const&B,int n){std::filesystem::create_directories("work/formal-probes/dual-basis");struct HH{char m[8];uint32_t ver,mod,h,rows,states;}hh{{'R','8','D','U','A','L','F','1'},1,Q,(uint32_t)h,(uint32_t)B.size(),(uint32_t)n};std::ofstream out(path,std::ios::binary|std::ios::trunc);out.write((char*)&hh,sizeof(hh));for(auto const&b:B)out.write((char*)b.v.data(),(size_t)n*4);}
static std::vector<uint32_t> loadPhi(std::string path,int h,int rows,int states){struct HH{char m[8];uint32_t ver,mod,h,rows,states;}hh{};std::ifstream in(path,std::ios::binary);in.read((char*)&hh,sizeof(hh));if(!in||hh.mod!=Q||hh.h!=(uint32_t)h||hh.rows!=(uint32_t)rows||hh.states!=(uint32_t)states)throw std::runtime_error("phi hdr");std::vector<uint32_t>P((size_t)rows*states);in.read((char*)P.data(),P.size()*4);if(!in)throw std::runtime_error("phi read");return P;}
static Basis buildFromHigher(int h,std::vector<Packed>const&src,std::vector<Packed>const&higher,std::vector<uint32_t>const&PhiHigher,int dh,int targetDim){auto TL=trans(src,higher,2),TN=trans(src,src,0);Basis B(src.size());for(int f=0;f<dh;++f){auto const*pf=PhiHigher.data()+(size_t)f*higher.size();std::vector<uint32_t>y(src.size());for(int i=0;i<(int)src.size();++i){uint64_t z=0;for(auto[t,c]:TL[i])z=(z+(uint64_t)c*pf[t])%Q;y[i]=z;}B.add(std::move(y),0);if((f&127)==0)std::cerr<<"seed f="<<f<<" rank="<<B.b.size()<<"\n";}int seed=B.b.size();std::map<int,int>adds;while(!B.q.empty()&&B.b.size()<(size_t)targetDim){int bi=B.q.front();B.q.pop_front();auto f=B.b[bi].v;std::vector<uint32_t>y(src.size());for(int i=0;i<(int)src.size();++i){uint64_t z=0;for(auto[t,c]:TN[i])z=(z+(uint64_t)c*f[t])%Q;y[i]=z;}if(B.add(std::move(y),B.b[bi].depth+1)){++adds[B.b.back().depth];if((B.b.size()&31)==0)std::cerr<<"N rank="<<B.b.size()<<"\n";}}std::cout<<"h="<<h<<" seed_rank="<<seed<<" final_rank="<<B.b.size()<<" target="<<targetDim<<" depthAdds";for(auto[d,c]:adds)std::cout<<' '<<d<<':'<<c;std::cout<<'\n';return B;}
int main(int argc,char**argv){if(argc>1)Q=std::strtoul(argv[1],nullptr,10);MODP=Q;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::array<std::vector<Packed>,3>H;for(auto&p:all){int s=unpack(p).sp;if(s<=2)H[s].push_back(p);}std::cout<<"counts h0="<<H[0].size()<<" h1="<<H[1].size()<<" h2="<<H[2].size()<<"\n";auto P2=loadPhi2(H[2]);auto B1=buildFromHigher(1,H[1],H[2],P2,1428,1640);if(B1.b.size()!=1640)return 2;savePhi("work/formal-probes/dual-basis/Phi_h1_mod"+std::to_string(Q)+".bin",1,B1.b,H[1].size());std::vector<uint32_t>P1((size_t)B1.b.size()*H[1].size());for(int i=0;i<(int)B1.b.size();++i)std::copy(B1.b[i].v.begin(),B1.b[i].v.end(),P1.begin()+(size_t)i*H[1].size());auto B0=buildFromHigher(0,H[0],H[1],P1,1640,1107);if(B0.b.size()!=1107)return 3;savePhi("work/formal-probes/dual-basis/Phi_h0_mod"+std::to_string(Q)+".bin",0,B0.b,H[0].size());return 0;}
