#define ROW8_STRUCTURAL_UPPER_NO_MAIN 1
#include "row8_structural_upper_sparsity.cpp"
#include <random>
using Adj=std::vector<std::vector<std::pair<int,uint32_t>>>;
static Adj buildQ(Space const&S,Space const&T,int a){Adj Qm(S.dim);for(auto const&sb:S.blocks)for(int sr=0;sr<(int)sb.rr.size();++sr){int si=sb.idx[sb.piv[sr]],row=sb.off+sr;WVec v{{S.states[si],1}};auto z=wcolumn(std::move(v),8,false,a);std::vector<uint32_t>q(T.dim);for(auto const&e:z){int ti=std::lower_bound(T.states.begin(),T.states.end(),e.p)-T.states.begin();int bi=T.stateBlock[ti],lc=T.stateLocal[ti];auto const&tb=T.blocks[bi];for(int tr=0;tr<(int)tb.rr.size();++tr)if(tb.rr[tr][lc])q[tb.off+tr]=(q[tb.off+tr]+(uint64_t)e.v*tb.rr[tr][lc])%Q;}for(int k=0;k<T.dim;++k)if(q[k])Qm[row].push_back({k,q[k]});}return Qm;}
static std::vector<uint32_t> project(WVec const&v,Space const&S){std::vector<uint32_t>c(S.dim);for(auto const&e:v){int i=std::lower_bound(S.states.begin(),S.states.end(),e.p)-S.states.begin();if(i==(int)S.states.size()||!(S.states[i]==e.p))throw std::runtime_error("project state");int bi=S.stateBlock[i],lc=S.stateLocal[i];auto const&b=S.blocks[bi];for(int r=0;r<(int)b.rr.size();++r)if(b.rr[r][lc])c[b.off+r]=(c[b.off+r]+(uint64_t)e.v*b.rr[r][lc])%Q;}return c;}
static std::vector<uint32_t> stepC(std::vector<uint32_t>const&c,Adj const&A,int nt){std::vector<uint32_t>z(nt);for(int i=0;i<(int)c.size();++i)if(c[i])for(auto[j,a]:A[i])z[j]=(z[j]+(uint64_t)c[i]*a)%Q;return z;}
static std::vector<uint32_t> beta(Space const&S,int sym){std::vector<uint32_t>b(S.dim);for(auto const&bl:S.blocks)for(int r=0;r<(int)bl.rr.size();++r){int si=bl.idx[bl.piv[r]];WVec v{{S.states[si],1}};b[bl.off+r]=wlast_value(std::move(v),8,sym);}return b;}
static uint32_t dot(std::vector<uint32_t>const&a,std::vector<uint32_t>const&b){uint64_t z=0;for(int i=0;i<(int)a.size();++i)z=(z+(uint64_t)a[i]*b[i])%Q;return z;}
int main(int ac,char**av){MODP=Q;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::array<std::vector<Packed>,9>H;for(auto&p:all)H[unpack(p).sp].push_back(p);std::array<std::unique_ptr<Space>,9>S;auto A0=loadA01(0,H[0].size()),A1=loadA01(1,H[1].size()),A2=loadA2(H[2]);S[0]=std::make_unique<Space>(makeSpace(0,H[0],A0));S[1]=std::make_unique<Space>(makeSpace(1,H[1],A1));S[2]=std::make_unique<Space>(makeSpace(2,H[2],A2));for(int h=3;h<=8;++h){auto A=makeAupper(h,H[h]);S[h]=std::make_unique<Space>(makeSpace(h,H[h],A));}
 std::array<std::array<Adj,9>,3>QM;size_t qnz=0;for(int h=0;h<=8;++h)for(int a=0;a<3;++a){int h2=h+DEL_[a];if(h2<0||h2>8)continue;QM[a][h]=buildQ(*S[h],*S[h2],a);for(auto const&r:QM[a][h])qnz+=r.size();}std::cout<<"built structural Q nz="<<qnz<<"\n";
 auto eval=[&](uint32_t pc,uint32_t sc){auto p=digits9(pc);auto s=digits10(sc);State z{};z.n=8;WVec raw{{pack(z),1}};raw=wcolumn(std::move(raw),8,true,p[0]);int h=1+DEL_[p[0]];if(h<0||h>8)return uint32_t(0);auto c=project(raw,*S[h]);for(int i=1;i<9;++i){int h2=h+DEL_[p[i]];if(h2<0||h2>8)return uint32_t(0);c=stepC(c,QM[p[i]][h],S[h2]->dim);h=h2;}for(int i=0;i<9;++i){int h2=h+DEL_[s[i]];if(h2<0||h2>8)return uint32_t(0);c=stepC(c,QM[s[i]][h],S[h2]->dim);h=h2;}auto b=beta(*S[h],s[9]);return dot(c,b);};
 std::vector<std::pair<uint32_t,uint32_t>> tests={{1,0},{0,1},{2186,3280},{2186,0},{3,7}};std::mt19937 rng(1234567);for(int i=0;i<15;++i)tests.push_back({rng()%19683u,rng()%59049u});size_t bad=0;for(auto [pc,sc]:tests){auto x=eval(pc,sc),y=full_value(pc,sc);std::cout<<"pc="<<pc<<" sc="<<sc<<" structural="<<x<<" raw="<<y<<" eq="<<(x==y)<<"\n";bad+=x!=y;}std::cout<<"structural_eval_bad="<<bad<<" tests="<<tests.size()<<" exact="<<(bad==0)<<"\n";return bad?1:0;}
