#define ROW8_STRUCTURAL_UPPER_NO_MAIN 1
#include "row8_structural_upper_sparsity.cpp"
#include <cstdint>
#include <iostream>
using I=std::int64_t;using IAdj=std::vector<std::vector<std::pair<int,I>>>;
static I si(uint32_t x){return x<=Q/2?(I)x:(I)x-(I)Q;}
static std::vector<std::vector<std::pair<int,I>>> evalI(Space const&S){std::vector<std::vector<std::pair<int,I>>> e(S.states.size());for(auto const&b:S.blocks)for(int c=0;c<(int)b.idx.size();++c)for(int r=0;r<(int)b.rr.size();++r)if(b.rr[r][c])e[b.idx[c]].push_back({b.off+r,si(b.rr[r][c])});return e;}
static IAdj buildQI(Space const&S,Space const&T,int a,std::vector<std::vector<std::pair<int,I>>>const&te){IAdj A(S.dim);for(auto const&b:S.blocks)for(int r=0;r<(int)b.rr.size();++r){int row=b.off+r,src=b.idx[b.piv[r]];WVec v{{S.states[src],1}};auto z=wcolumn(std::move(v),8,false,a);std::vector<I>q(T.dim);for(auto const&x:z){int ti=std::lower_bound(T.states.begin(),T.states.end(),x.p)-T.states.begin();for(auto[k,c]:te[ti])q[k]+=(I)x.v*c;}for(int k=0;k<T.dim;++k)if(q[k])A[row].push_back({k,q[k]});}return A;}
static bool verifyI(Space const&S,Space const&T,int a){auto se=evalI(S),te=evalI(T);auto A=buildQI(S,T,a,te);size_t bad=0;I maxabs=0;std::map<I,size_t>qh;for(auto const&r:A)for(auto[k,c]:r){++qh[c];maxabs=std::max(maxabs,c<0?-c:c);}for(int s=0;s<(int)S.states.size();++s){std::vector<I>act(T.dim),pred(T.dim);WVec v{{S.states[s],1}};auto z=wcolumn(std::move(v),8,false,a);for(auto const&x:z){int ti=std::lower_bound(T.states.begin(),T.states.end(),x.p)-T.states.begin();for(auto[k,c]:te[ti])act[k]+=(I)x.v*c;}for(auto[i,c]:se[s])for(auto[k,q]:A[i])pred[k]+=c*q;if(act!=pred){if(bad<4){int k=0;while(k<T.dim&&act[k]==pred[k])++k;std::cerr<<"bad h="<<S.h<<" a="<<a<<" state="<<s<<" k="<<k<<" act="<<(k<T.dim?act[k]:0)<<" pred="<<(k<T.dim?pred[k]:0)<<"\n";}++bad;}}
 std::cout<<"INTEGER h="<<S.h<<" a="<<a<<" h2="<<T.h<<" states="<<S.states.size()<<" q_nz=";size_t nz=0;for(auto const&r:A)nz+=r.size();std::cout<<nz<<" maxQ="<<maxabs<<" coeff";for(auto[v,c]:qh)std::cout<<' '<<v<<':'<<c;std::cout<<" bad="<<bad<<" exact="<<(bad==0)<<"\n";return bad==0;}
static bool verifyFinalI(Space const&S,int sym){auto se=evalI(S);std::vector<I>b(S.dim);for(auto const&bl:S.blocks)for(int r=0;r<(int)bl.rr.size();++r){int src=bl.idx[bl.piv[r]];WVec v{{S.states[src],1}};b[bl.off+r]=wlast_value(std::move(v),8,sym);}size_t bad=0;for(int s=0;s<(int)S.states.size();++s){WVec v{{S.states[s],1}};I act=wlast_value(std::move(v),8,sym),pred=0;for(auto[i,c]:se[s])pred+=c*b[i];if(act!=pred)++bad;}std::cout<<"INTEGER_FINAL h="<<S.h<<" sym="<<sym<<" bad="<<bad<<" exact="<<(bad==0)<<"\n";return bad==0;}
#ifndef ROW8_STRUCTURAL_INTEGER_NO_MAIN
int main(){MODP=4294967291u;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::vector<Packed>H0,H1,H2;for(auto&p:all){int h=unpack(p).sp;if(h==0)H0.push_back(p);else if(h==1)H1.push_back(p);else if(h==2)H2.push_back(p);}auto A0=loadA01(0,H0.size()),A1=loadA01(1,H1.size()),A2=loadA2(H2);auto S0=makeSpace(0,H0,A0),S1=makeSpace(1,H1,A1),S2=makeSpace(2,H2,A2);bool ok=true;ok&=verifyI(S0,S0,0);ok&=verifyI(S0,S1,2);ok&=verifyI(S1,S1,0);ok&=verifyI(S1,S0,1);ok&=verifyI(S1,S2,2);ok&=verifyI(S2,S2,0);ok&=verifyI(S2,S1,1);ok&=verifyFinalI(S0,0);ok&=verifyFinalI(S1,1);std::cout<<"structural_integer_lower_exact="<<ok<<"\n";return ok?0:1;}
#endif
