#define ROW8_H2_PARTITION_NO_MAIN 1
#include "row8_h2_relation_partition.cpp"
#include <deque>
static constexpr uint32_t QK=1000000007u;static uint32_t qinv(uint32_t a){uint64_t e=QK-2,r=1,x=a;while(e){if(e&1)r=(__uint128_t)r*x%QK;x=(__uint128_t)x*x%QK;e>>=1;}return r;}
int main(){MODP=QK;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::vector<Packed>hs;for(auto&p:all)if(unpack(p).sp==2)hs.push_back(p);auto ws=words2();std::set<int>bad;{std::ifstream in("work/formal-probes/canonical-matrix/h2_actual_bad_indices.txt");int x;while(in>>x)bad.insert(x);}std::vector<std::vector<std::pair<int,uint32_t>>>T(hs.size());for(int i=0;i<(int)hs.size();++i){WVec v{{hs[i],1}};auto z=wcolumn(std::move(v),8,false,0);for(auto&e:z){int t=std::lower_bound(hs.begin(),hs.end(),e.p)-hs.begin();T[i].push_back({t,e.v});}}
 std::vector<int>anchor(hs.size(),-1),cls(hs.size(),-1);int an=0;for(int j=0;j<(int)ws.size();++j)if(!bad.count(j)){int i=std::lower_bound(hs.begin(),hs.end(),ws[j].first)-hs.begin();anchor[i]=cls[i]=an++;}for(int round=0;round<4;++round){auto sig=[&](int i){Sig s;for(auto[t,c]:T[i])if(cls[t]>=0)s.push_back({cls[t],c});std::sort(s.begin(),s.end());Sig o;for(auto[q,c]:s){if(!o.empty()&&o.back().first==q)o.back().second+=c;else o.push_back({q,c});}return o;};std::map<Sig,std::vector<int>>groups;for(int i=0;i<(int)hs.size();++i)if(anchor[i]<0){auto s=sig(i);if(!s.empty())groups[s].push_back(i);}std::vector<int>ncls=cls;int nx=1308;for(auto const&[s,v]:groups){for(int i:v)ncls[i]=nx;++nx;}if(ncls==cls)break;cls.swap(ncls);}std::vector<int>sup,sid(hs.size(),-1);for(int i=0;i<(int)hs.size();++i)if(cls[i]>=1308){sid[i]=sup.size();sup.push_back(i);}if(sup.size()!=243)throw std::runtime_error("support243");int m=sup.size();
 std::vector<std::vector<std::pair<int,uint32_t>>>K(m);std::vector<std::vector<std::pair<int,uint32_t>>>seed(1308);for(int si=0;si<m;++si){int i=sup[si];for(auto[t,c]:T[i]){if(cls[t]<0)continue;if(cls[t]<1308)seed[cls[t]].push_back({si,c});else K[si].push_back({sid[t],c});}}
 struct B{int pivot,depth,src;std::vector<uint32_t>v;};std::vector<B>bs;std::array<int,243>at;at.fill(-1);std::deque<int>q;
 auto add=[&](std::vector<uint32_t>y,int depth,int src)->bool{for(int p=0;p<m;++p)if(y[p]&&at[p]>=0){auto const&b=bs[at[p]];uint32_t f=y[p];for(int k=p;k<m;++k)if(b.v[k])y[k]=(y[k]+QK-(__uint128_t)f*b.v[k]%QK)%QK;}int p=-1;for(int k=0;k<m;++k)if(y[k]){p=k;break;}if(p<0)return false;uint32_t iv=qinv(y[p]);for(int k=p;k<m;++k)if(y[k])y[k]=(__uint128_t)y[k]*iv%QK;int bi=bs.size();bs.push_back({p,depth,src,std::move(y)});at[p]=bi;q.push_back(bi);return true;};
 int sadded=0;for(int j=0;j<1308;++j){std::vector<uint32_t>v(m);for(auto[i,c]:seed[j])v[i]=c;if(add(std::move(v),1,j))++sadded;}std::cout<<"seed_rank="<<sadded<<" support="<<m<<"\n";std::map<int,int>depthadd;while(!q.empty()){int bi=q.front();q.pop_front();auto const f=bs[bi].v;std::vector<uint32_t>y(m);for(int si=0;si<m;++si){uint64_t z=0;for(auto[t,c]:K[si])z=(z+(uint64_t)c*f[t])%QK;y[si]=z;}if(add(std::move(y),bs[bi].depth+1,bi)){++depthadd[bs.back().depth];std::cout<<"add rank="<<bs.size()<<" depth="<<bs.back().depth<<" from="<<bi<<" pivot="<<bs.back().pivot<<"\n";}}
 std::map<size_t,int>nz;for(auto const&b:bs){size_t z=0;for(auto x:b.v)z+=x!=0;++nz[z];}std::cout<<"final_extra_rank="<<bs.size()<<" total="<<1308+bs.size()<<" depthAdds";for(auto[d,c]:depthadd)std::cout<<' '<<d<<':'<<c;std::cout<<" nzHist";for(auto[z,c]:nz)std::cout<<' '<<z<<':'<<c;std::cout<<'\n';return bs.size()==120?0:1;}
