#define ROW8_H2_PARTITION_NO_MAIN 1
#include "row8_h2_relation_partition.cpp"
#include <iomanip>
static uint32_t P2=1000000007u;static uint32_t invp(uint32_t a){uint64_t e=P2-2,r=1,x=a;while(e){if(e&1)r=(__uint128_t)r*x%P2;x=(__uint128_t)x*x%P2;e>>=1;}return r;}
int main(){MODP=P2;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::vector<Packed>hs;for(auto&p:all)if(unpack(p).sp==2)hs.push_back(p);auto ws=words2();std::set<int>bad;{std::ifstream in("work/formal-probes/canonical-matrix/h2_actual_bad_indices.txt");int x;while(in>>x)bad.insert(x);}std::vector<std::vector<std::pair<int,uint32_t>>>T(hs.size());for(int i=0;i<(int)hs.size();++i){WVec v{{hs[i],1}};auto z=wcolumn(std::move(v),8,false,0);for(auto&e:z){auto it=std::lower_bound(hs.begin(),hs.end(),e.p);T[i].push_back({int(it-hs.begin()),e.v});}}
 std::vector<int>anchor(hs.size(),-1),cls(hs.size(),-1);int an=0;for(int j=0;j<(int)ws.size();++j)if(!bad.count(j)){int i=std::lower_bound(hs.begin(),hs.end(),ws[j].first)-hs.begin();anchor[i]=cls[i]=an++;}for(int round=0;round<3;++round){auto sig=[&](int i){Sig s;for(auto[t,c]:T[i])if(cls[t]>=0)s.push_back({cls[t],c});std::sort(s.begin(),s.end());Sig o;for(auto[q,c]:s){if(!o.empty()&&o.back().first==q)o.back().second+=c;else o.push_back({q,c});}return o;};std::map<Sig,std::vector<int>>groups;for(int i=0;i<(int)hs.size();++i)if(anchor[i]<0){auto s=sig(i);if(!s.empty())groups[s].push_back(i);}std::vector<int>ncls=cls;int nx=1308;for(auto const&[s,v]:groups){for(int i:v)ncls[i]=nx;++nx;}if(ncls==cls)break;cls.swap(ncls);}int nc=*std::max_element(cls.begin(),cls.end())+1;if(nc!=1434)throw std::runtime_error("classes");int m=126,n=1308;std::vector<uint32_t>A((size_t)m*n);std::vector<std::vector<int>>members(m);for(int i=0;i<(int)hs.size();++i)if(cls[i]>=1308)members[cls[i]-1308].push_back(i);for(int r=0;r<m;++r){int i=members[r][0];for(auto[t,c]:T[i])if(cls[t]>=0&&cls[t]<1308)A[(size_t)r*n+cls[t]]+=c;}
 std::vector<int>hardWord(m,-1);for(int j:bad){int i=std::lower_bound(hs.begin(),hs.end(),ws[j].first)-hs.begin();hardWord[cls[i]-1308]=j;}
 std::vector<uint32_t>C((size_t)m*m);for(int i=0;i<m;++i)C[(size_t)i*m+i]=1;int rank=0;std::vector<int>pivrow;for(int c=0;c<n&&rank<m;++c){int r=rank;while(r<m&&!A[(size_t)r*n+c])++r;if(r==m)continue;if(r!=rank){for(int j=c;j<n;++j)std::swap(A[(size_t)r*n+j],A[(size_t)rank*n+j]);for(int j=0;j<m;++j)std::swap(C[(size_t)r*m+j],C[(size_t)rank*m+j]);}uint32_t iv=invp(A[(size_t)rank*n+c]);for(int j=c;j<n;++j)A[(size_t)rank*n+j]=(__uint128_t)A[(size_t)rank*n+j]*iv%P2;for(int j=0;j<m;++j)C[(size_t)rank*m+j]=(__uint128_t)C[(size_t)rank*m+j]*iv%P2;for(int r2=0;r2<m;++r2)if(r2!=rank&&A[(size_t)r2*n+c]){uint32_t f=A[(size_t)r2*n+c];for(int j=c;j<n;++j)A[(size_t)r2*n+j]=(A[(size_t)r2*n+j]+P2-(__uint128_t)f*A[(size_t)rank*n+j]%P2)%P2;for(int j=0;j<m;++j)C[(size_t)r2*m+j]=(C[(size_t)r2*m+j]+P2-(__uint128_t)f*C[(size_t)rank*m+j]%P2)%P2;}++rank;}
 std::cout<<"signature_rank="<<rank<<"/126 nullity="<<126-rank<<"\n";int dep=0;for(int r=rank;r<m;++r){bool zero=true;for(int c=0;c<n;++c)zero&=A[(size_t)r*n+c]==0;if(!zero)continue;std::cout<<"DEP "<<dep++<<" terms=";for(int j=0;j<m;++j)if(C[(size_t)r*m+j]){int64_t x=C[(size_t)r*m+j]<=P2/2?C[(size_t)r*m+j]:(int64_t)C[(size_t)r*m+j]-P2;std::cout<<" [c"<<j<<" coef="<<x<<" size="<<members[j].size();if(hardWord[j]>=0)std::cout<<" hard="<<hardWord[j]<<":"<<ws[hardWord[j]].second;else std::cout<<" aux";std::cout<<"]";}std::cout<<"\n";}
 std::cout<<"class_summary\n";for(int j=0;j<m;++j)if(hardWord[j]<0){std::cout<<"aux c"<<j<<" size="<<members[j].size()<<" first="<<members[j][0]<<"\n";}return rank==120?0:1;}
