#define ROW8_RAW_PREFIX_NO_MAIN 1
#include "row8_raw_prefix_vector.cpp"
#include <array>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <vector>

static constexpr int D_[9]={1107,1640,1428,888,420,152,42,8,1};
static constexpr int DEL_[3]={0,-1,1};
struct CacheM{std::array<std::array<std::vector<uint32_t>,9>,3>M;};
static CacheM loadM(uint32_t mod){std::string path;for(auto const&e:std::filesystem::directory_iterator("work/row8_mod_cache")){auto s=e.path().filename().string();if(s.find("row8_mod_"+std::to_string(mod)+"_")==0&&s.find("_52384d4443414249.bin")!=std::string::npos){path=e.path();break;}}if(path.empty())throw std::runtime_error("M cache missing");std::ifstream in(path,std::ios::binary);char magic[8];uint32_t ver,pm,ds[9];uint64_t fp,abi,an,bn,cnt[27],hash;in.read(magic,8);in.read((char*)&ver,4);in.read((char*)&pm,4);in.read((char*)&fp,8);in.read((char*)&abi,8);in.read((char*)ds,36);in.read((char*)&an,8);in.read((char*)&bn,8);in.read((char*)cnt,sizeof(cnt));in.read((char*)&hash,8);if(std::string(magic,7)!="R8MDC02"||ver!=2||pm!=mod)throw std::runtime_error("M header");in.seekg((std::streamoff)(4*(an+bn)),std::ios::cur);CacheM z;int q=0;for(int a=0;a<3;++a)for(int h=0;h<9;++h){z.M[a][h].resize(cnt[q++]);if(!z.M[a][h].empty())in.read((char*)z.M[a][h].data(),z.M[a][h].size()*4);}if(!in)throw std::runtime_error("M read");return z;}
static std::array<std::vector<uint32_t>,9> loadpc(){std::ifstream in("src/cuda/b300/row8_pivots_w19.bin",std::ios::binary);char m[8];uint32_t v,ds[9];in.read(m,8);in.read((char*)&v,4);in.read((char*)ds,36);std::array<std::vector<uint32_t>,9>p;for(int h=0;h<9;++h){p[h].resize(ds[h]);for(auto&x:p[h]){uint32_t sc;in.read((char*)&x,4);in.read((char*)&sc,4);}}return p;}
static bool enc(std::string const&t,Packed&out){if(t.size()!=8)return false;int h=0,b=0;for(char c:t){if(c=='T'){if(b)return false;++h;}else if(c=='U')++b;else if(c=='D')--b;else if(c!='N')return false;}if(b)return false;State s{};s.n=8;s.sp=h;std::vector<int>tp;for(int i=0;i<8;++i)if(t[i]=='T')tp.push_back(i);int nx=1;for(int k=0;k<h;++k){int q=nx++,i=tp[k];s.deg[i]=1;s.comp[i]=q;s.stack[k]=q;}std::vector<std::pair<int,int>>op;b=0;for(int i=0;i<8;++i){char c=t[i];if(c=='T'){if(b||!op.empty())return false;continue;}if(c=='N')continue;int st=c=='U'?1:-1;bool o=b==0||(b>0&&st>0)||(b<0&&st<0);if(o){op.push_back({i,st});b+=st;}else{if(op.empty())return false;auto[j,sg]=op.back();op.pop_back();if(sg!=-st)return false;int q=nx++;s.deg[j]=s.deg[i]=1;s.comp[j]=s.comp[i]=q;s.status[q]=sg<0;b+=st;}}if(b||!op.empty())return false;s.ns=nx;out=pack(s);return true;}
static void grec(int pos,int nt,int bal,std::string&w,std::vector<Packed>&out){if(pos==8){if(!nt&&!bal){Packed p;if(!enc(w,p))throw std::runtime_error("enc");out.push_back(p);}return;}if(nt>8-pos)return;w[pos]='N';grec(pos+1,nt,bal,w,out);w[pos]='U';grec(pos+1,nt,bal+1,w,out);w[pos]='D';grec(pos+1,nt,bal-1,w,out);if(nt&&bal==0){w[pos]='T';grec(pos+1,nt-1,0,w,out);}}
static std::vector<Packed> basis(int h){std::string w(8,'N');std::vector<Packed>v;grec(0,h,0,w,v);std::sort(v.begin(),v.end());v.erase(std::unique(v.begin(),v.end()),v.end());if((int)v.size()!=D_[h])throw std::runtime_error("basis size");return v;}
static std::vector<uint32_t> proj(WVec const&v,std::vector<Packed>const&b){std::vector<uint32_t>z(b.size());size_t i=0,j=0;while(i<v.size()&&j<b.size()){if(v[i].p<b[j])++i;else if(b[j]<v[i].p)++j;else{z[j]=v[i].v;++i;++j;}}return z;}
static bool loadA(int h,uint32_t mod,std::vector<uint32_t>&A){std::string path="work/formal-probes/canonical-matrix/A_h"+std::to_string(h)+"_mod"+std::to_string(mod)+".bin";std::ifstream in(path,std::ios::binary);if(!in)return false;struct H{char magic[8];uint32_t ver,mod,h,dim;uint64_t count,hash;}x{};in.read((char*)&x,sizeof(x));if(!in||std::string(x.magic,8)!="R8CANA01"||x.ver!=1||x.mod!=mod||x.h!=(uint32_t)h||x.dim!=(uint32_t)D_[h]||x.count!=A.size())return false;in.read((char*)A.data(),A.size()*4);return bool(in);}
static uint64_t fnv(void const*p,size_t n,uint64_t h=1469598103934665603ULL){auto*b=(unsigned char const*)p;for(size_t i=0;i<n;++i){h^=b[i];h*=1099511628211ULL;}return h;}
static void saveA(int h,uint32_t mod,std::vector<uint32_t>const&A){std::filesystem::create_directories("work/formal-probes/canonical-matrix");std::string path="work/formal-probes/canonical-matrix/A_h"+std::to_string(h)+"_mod"+std::to_string(mod)+".bin";struct H{char magic[8];uint32_t ver,mod,h,dim;uint64_t count,hash;}x{{'R','8','C','A','N','A','0','1'},1,mod,(uint32_t)h,(uint32_t)D_[h],(uint64_t)A.size(),fnv(A.data(),A.size()*4)};std::ofstream out(path,std::ios::binary|std::ios::trunc);out.write((char*)&x,sizeof(x));out.write((char*)A.data(),A.size()*4);}
static int rankmod(std::vector<uint32_t>A,int n,uint32_t p){int r=0;for(int c=0;c<n&&r<n;++c){int q=r;while(q<n&&!A[(size_t)q*n+c])++q;if(q==n)continue;if(q!=r)for(int j=c;j<n;++j)std::swap(A[(size_t)q*n+j],A[(size_t)r*n+j]);uint64_t a=A[(size_t)r*n+c],e=p-2,iv=1;while(e){if(e&1)iv=(__uint128_t)iv*a%p;a=(__uint128_t)a*a%p;e>>=1;}for(int j=c;j<n;++j)A[(size_t)r*n+j]=(__uint128_t)A[(size_t)r*n+j]*iv%p;for(int i=0;i<n;++i)if(i!=r&&A[(size_t)i*n+c]){uint32_t f=A[(size_t)i*n+c];for(int j=c;j<n;++j)A[(size_t)i*n+j]=(A[(size_t)i*n+j]+p-(__uint128_t)f*A[(size_t)r*n+j]%p)%p;}++r;}return r;}
struct Node{std::array<std::unique_ptr<Node>,3>ch;int row=-1;};
static std::array<int,9>d9(uint32_t x){std::array<int,9>d{};for(int i=8;i>=0;--i){d[i]=x%3;x/=3;}return d;}
struct BuildCtx{int h;uint32_t mod;std::array<std::vector<Packed>,9> b;std::vector<uint32_t>A;std::array<std::vector<uint32_t>,3>E;size_t nodes=0;};
static void dfs(Node const&n,int depth,WVec const&v,BuildCtx&c){++c.nodes;if(depth==9){int i=n.row;if(i<0)throw std::runtime_error("leaf");auto q=proj(v,c.b[c.h]);std::copy(q.begin(),q.end(),c.A.begin()+(size_t)i*D_[c.h]);for(int a=0;a<3;++a){int h2=c.h+DEL_[a];if(h2<0||h2>8)continue;auto ext=wcolumn(v,8,false,a);auto e=proj(ext,c.b[h2]);std::copy(e.begin(),e.end(),c.E[a].begin()+(size_t)i*D_[h2]);}if((i&31)==0)std::cerr<<"leaf "<<i+1<<"/"<<D_[c.h]<<" support="<<v.size()<<"\n";return;}for(int a=0;a<3;++a)if(n.ch[a]){auto z=wcolumn(v,8,depth==0,a);dfs(*n.ch[a],depth+1,z,c);}}
#ifndef ROW8_CANONICAL_TRIE_NO_MAIN
int main(int argc,char**argv){MODP=argc>1?std::strtoul(argv[1],nullptr,10):1000000007u;int h=argc>2?std::atoi(argv[2]):5;if(h<0||h>8)return 2;auto P=loadpc();auto M=loadM(MODP);BuildCtx c;c.h=h;c.mod=MODP;for(int q=0;q<9;++q)c.b[q]=basis(q);c.A.resize((size_t)D_[h]*D_[h]);for(int a=0;a<3;++a){int h2=h+DEL_[a];if(0<=h2&&h2<=8)c.E[a].resize((size_t)D_[h]*D_[h2]);}
 Node root;for(int i=0;i<D_[h];++i){auto d=d9(P[h][i]);Node*t=&root;for(int a:d){if(!t->ch[a])t->ch[a]=std::make_unique<Node>();t=t->ch[a].get();}t->row=i;}State z{};z.n=8;WVec init{{pack(z),1}};auto t0=std::chrono::steady_clock::now();dfs(root,0,init,c);double buildsec=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();saveA(h,MODP,c.A);int rk=rankmod(c.A,D_[h],MODP);std::cout<<"h="<<h<<" A_rank="<<rk<<"/"<<D_[h]<<" trie_nodes="<<c.nodes<<" build_s="<<buildsec<<"\n";
 size_t allbad=0;for(int a=0;a<3;++a){int h2=h+DEL_[a];if(h2<0||h2>8)continue;std::vector<uint32_t>At((size_t)D_[h2]*D_[h2]);if(h2==h)At=c.A;else if(!loadA(h2,MODP,At))throw std::runtime_error("target A cache missing h="+std::to_string(h2));int rt=rankmod(At,D_[h2],MODP);size_t bad=0;uint64_t he=1469598103934665603ULL,hp=he;auto const&mm=M.M[a][h];for(int i=0;i<D_[h];++i)for(int k=0;k<D_[h2];++k){__uint128_t s=0;for(int j=0;j<D_[h2];++j)s+=(__uint128_t)mm[(size_t)i*D_[h2]+j]*At[(size_t)j*D_[h2]+k];uint32_t pred=s%MODP,got=c.E[a][(size_t)i*D_[h2]+k];if(got!=pred){if(bad<5)std::cerr<<"mismatch a="<<a<<" i="<<i<<" k="<<k<<" got="<<got<<" pred="<<pred<<"\n";++bad;}he^=got;he*=1099511628211ULL;hp^=pred;hp*=1099511628211ULL;}allbad+=bad;std::cout<<"sym="<<a<<" h2="<<h2<<" target_rank="<<rt<<" bad="<<bad<<" hashE="<<std::hex<<he<<" hashP="<<hp<<std::dec<<" exact="<<(bad==0)<<"\n";}
 std::cout<<"all_exact="<<(allbad==0)<<"\n";return allbad?1:0;}

#endif
