#define ROW8_H2_PARTITION_NO_MAIN 1
#include "row8_h2_relation_partition.cpp"
#include <deque>
#include <functional>
#include <unordered_map>
static uint32_t Q=1000000007u;static uint32_t qi(uint32_t a){uint64_t e=Q-2,r=1,x=a;while(e){if(e&1)r=(__uint128_t)r*x%Q;x=(__uint128_t)x*x%Q;e>>=1;}return r;}
struct PH2{size_t operator()(Packed const&p)const noexcept{uint64_t h=0;for(auto x:p.w)h^=x+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);return h;}};
static void wr(int p,int nt,int bal,std::string&w,std::vector<std::pair<Packed,std::string>>&o){if(p==8){if(!nt&&!bal){Packed x;if(enc(w,x))o.push_back({x,w});}return;}if(nt>8-p)return;w[p]='N';wr(p+1,nt,bal,w,o);w[p]='U';wr(p+1,nt,bal+1,w,o);w[p]='D';wr(p+1,nt,bal-1,w,o);if(nt&&bal==0){w[p]='T';wr(p+1,nt-1,0,w,o);}}
static std::vector<std::pair<Packed,std::string>> ww(int h){std::string w(8,'N');std::vector<std::pair<Packed,std::string>>v;wr(0,h,0,w,v);std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.first<b.first;});v.erase(std::unique(v.begin(),v.end(),[](auto&a,auto&b){return a.first==b.first;}),v.end());return v;}
static bool h3hard(std::string const&w){int b=0,n=0;auto fl=[&](){bool z=n>=2;b=n=0;return z;};for(char c:w){if(c=='T'){if(fl())return true;continue;}if(c=='N')continue;int d=c=='U'?1:-1;if(b==0&&d<0)++n;b+=d;}return fl();}
static Packed h3mix(std::string const&w){State s{};s.n=8;int q=1,sk=0;std::array<int,4>z{};bool got=false;int st=0;while(st<8){int en=st;while(en<8&&w[en]!='T')++en;int b=0,ns=-1,c=0;for(int i=st;i<en;++i){if(w[i]=='N')continue;int d=w[i]=='U'?1:-1;if(b==0&&d<0)ns=i;b+=d;if(ns>=0&&b==0){if(c<2){z[2*c]=ns;z[2*c+1]=i;}++c;ns=-1;}}if(c>=2){got=true;break;}st=en+1;}if(!got)throw std::runtime_error("mix");for(int i=0;i<8;++i)if(w[i]=='T'){int c=q++;s.deg[i]=1;s.comp[i]=c;s.stack[sk++]=c;}auto add=[&](int a,int b,int stt){int c=q++;s.deg[a]=s.deg[b]=1;s.comp[a]=s.comp[b]=c;s.status[c]=stt;};add(z[0],z[3],1);add(z[1],z[2],0);s.sp=sk;s.ns=q;return pack(s);}
struct FB{int p,depth,origin;std::vector<uint32_t>v;};
int main(int argc,char**argv){if(argc>1)Q=std::strtoul(argv[1],nullptr,10);MODP=Q;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::vector<Packed>h2,h3;for(auto&p:all){int s=unpack(p).sp;if(s==2)h2.push_back(p);else if(s==3)h3.push_back(p);}auto w2=words2();std::set<int>bad2;{std::ifstream in("work/formal-probes/canonical-matrix/h2_actual_bad_indices.txt");int x;while(in>>x)bad2.insert(x);}std::vector<char>good2(h2.size());std::vector<int>nonId(h2.size(),-1),nonTo;int gc=0;for(int j=0;j<(int)w2.size();++j)if(!bad2.count(j)){int i=std::lower_bound(h2.begin(),h2.end(),w2[j].first)-h2.begin();good2[i]=1;++gc;}for(int i=0;i<(int)h2.size();++i)if(!good2[i]){nonId[i]=nonTo.size();nonTo.push_back(i);}int nn=nonTo.size();
 std::vector<std::vector<std::pair<int,uint32_t>>>TN(h2.size()),TL(h2.size());for(int i=0;i<(int)h2.size();++i){for(int a:{0,2}){WVec v{{h2[i],1}};auto z=wcolumn(std::move(v),8,false,a);auto&dst=a==0?TN[i]:TL[i];auto const&tar=a==0?h2:h3;for(auto&e:z){int t=std::lower_bound(tar.begin(),tar.end(),e.p)-tar.begin();dst.push_back({t,e.v});}}if((i&2047)==0)std::cerr<<"trans "<<i<<"/"<<h2.size()<<"\n";}
 // Rebuild the 117-dimensional N-closure using full non-good coordinates.
 std::vector<FB>B;std::vector<int>at(nn,-1);std::deque<int>queue;auto add=[&](std::vector<uint32_t>y,int dep,int org){for(int p=0;p<nn;++p)if(y[p]&&at[p]>=0){auto const&b=B[at[p]];uint32_t f=y[p];for(int k=p;k<nn;++k)if(b.v[k])y[k]=(y[k]+Q-(__uint128_t)f*b.v[k]%Q)%Q;}int p=-1;for(int k=0;k<nn;++k)if(y[k]){p=k;break;}if(p<0)return false;uint32_t iv=qi(y[p]);for(int k=p;k<nn;++k)if(y[k])y[k]=(__uint128_t)y[k]*iv%Q;int z=B.size();B.push_back({p,dep,org,std::move(y)});at[p]=z;queue.push_back(z);return true;};
 // Initial preimages of 1308 good singletons under N.
 std::vector<int>goodCoord(h2.size(),-1);int cc=0;for(int j=0;j<(int)w2.size();++j)if(!bad2.count(j)){int i=std::lower_bound(h2.begin(),h2.end(),w2[j].first)-h2.begin();goodCoord[i]=cc++;}
 std::vector<std::vector<std::pair<int,uint32_t>>>seed(1308);for(int si=0;si<nn;++si){int i=nonTo[si];for(auto[t,c]:TN[i])if(goodCoord[t]>=0)seed[goodCoord[t]].push_back({si,c});}for(int j=0;j<1308;++j){std::vector<uint32_t>y(nn);for(auto[i,c]:seed[j])y[i]=c;add(std::move(y),1,j);}while(!queue.empty()){int bi=queue.front();queue.pop_front();auto f=B[bi].v;std::vector<uint32_t>y(nn);for(int si=0;si<nn;++si){uint64_t z=0;for(auto[t,c]:TN[nonTo[si]])if(nonId[t]>=0)z=(z+(uint64_t)c*f[nonId[t]])%Q;y[si]=z;}add(std::move(y),B[bi].depth+1,bi);}std::cout<<"N_extra="<<B.size()<<" total="<<1308+B.size()<<"\n";
 // h3 relation coordinate map (856 singleton + 32 two-state sums).
 auto w3=ww(3);std::unordered_map<Packed,int,PH2>c3;int pairs=0;for(int j=0;j<(int)w3.size();++j){c3[w3[j].first]=j;if(h3hard(w3[j].second)){c3[h3mix(w3[j].second)]=j;++pairs;}}if(pairs!=32)throw std::runtime_error("pairs32");std::vector<std::vector<std::pair<int,uint32_t>>>pull(888);size_t outside=0;for(int si=0;si<nn;++si){int i=nonTo[si];for(auto[t,c]:TL[i]){auto it=c3.find(h3[t]);if(it!=c3.end())pull[it->second].push_back({si,c});}}
 int before=B.size(),addL=0;for(int j=0;j<888;++j){std::vector<uint32_t>y(nn);for(auto[i,c]:pull[j])y[i]=(y[i]+c)%Q;if(add(std::move(y),0,100000+j)){++addL;std::cout<<"L_add rank="<<B.size()<<" coord3="<<j<<" word="<<w3[j].second<<" pivot="<<B.back().p<<"\n";}}
 // Close any new L directions under N.
 int nAfterL=B.size();while(!queue.empty()){int bi=queue.front();queue.pop_front();auto f=B[bi].v;std::vector<uint32_t>y(nn);for(int si=0;si<nn;++si){uint64_t z=0;for(auto[t,c]:TN[nonTo[si]])if(nonId[t]>=0)z=(z+(uint64_t)c*f[nonId[t]])%Q;y[si]=z;}if(add(std::move(y),B[bi].depth+1,bi))std::cout<<"postN add rank="<<B.size()<<" depth="<<B.back().depth<<"\n";}
 std::map<size_t,int>nz;for(int bi=before;bi<(int)B.size();++bi){size_t z=0;for(auto x:B[bi].v)z+=x!=0;++nz[z];std::cout<<"NEWB bi="<<bi<<" nz="<<z<<"\n";int sh=0;for(int k=0;k<nn;++k)if(B[bi].v[k]){State ss=unpack(h2[nonTo[k]]);int64_t cv=B[bi].v[k]<=Q/2?B[bi].v[k]:(int64_t)B[bi].v[k]-Q;std::set<int> stk;for(int u=0;u<ss.sp;++u)stk.insert(ss.stack[u]);std::cout<<" c="<<cv<<" T=";for(int u=0;u<8;++u)if(ss.deg[u]&&stk.count(ss.comp[u]))std::cout<<u;std::map<int,std::vector<int>> po;for(int u=0;u<8;++u)if(ss.deg[u]&&!stk.count(ss.comp[u]))po[ss.comp[u]].push_back(u);std::cout<<" P=";for(auto const&qq:po)if(qq.second.size()==2)std::cout<<qq.second[0]<<"-"<<qq.second[1]<<":"<<int(ss.status[qq.first]&1)<<",";std::cout<<"\n";if(++sh>=12)break;}}
 std::filesystem::create_directories("work/formal-probes/dual-basis"); { struct HH{char magic[8];uint32_t ver,mod,h,rows,states;}; HH hh{{'R','8','D','U','A','L','0','1'},1,Q,2,(uint32_t)B.size(),(uint32_t)h2.size()}; std::ofstream out("work/formal-probes/dual-basis/Phi_h2_extra_mod"+std::to_string(Q)+".bin",std::ios::binary|std::ios::trunc); out.write((char*)&hh,sizeof(hh)); std::vector<uint32_t> full(h2.size()); for(auto const&bb:B){std::fill(full.begin(),full.end(),0);for(int k=0;k<nn;++k)full[nonTo[k]]=bb.v[k];out.write((char*)full.data(),full.size()*4);} }
 std::cout<<"L_added="<<addL<<" afterL="<<nAfterL<<" final_extra="<<B.size()<<" total="<<1308+B.size()<<" new_nz";for(auto[z,c]:nz)std::cout<<' '<<z<<':'<<c;std::cout<<'\n';return B.size()==120?0:1;}
