#define ROW8_CANONICAL_TRIE_NO_MAIN 1
#include "row8_canonical_trie_verify.cpp"
#include <array>
#include <functional>
#include <iostream>
#include <map>
#include <unordered_map>
static void rw(int p,int nt,int bal,std::string&w,std::vector<std::pair<Packed,std::string>>&o){if(p==8){if(!nt&&!bal){Packed x;if(enc(w,x))o.push_back({x,w});}return;}if(nt>8-p)return;w[p]='N';rw(p+1,nt,bal,w,o);w[p]='U';rw(p+1,nt,bal+1,w,o);w[p]='D';rw(p+1,nt,bal-1,w,o);if(nt&&bal==0){w[p]='T';rw(p+1,nt-1,0,w,o);}}
static std::vector<std::pair<Packed,std::string>> words(int h){std::string w(8,'N');std::vector<std::pair<Packed,std::string>>v;rw(0,h,0,w,v);std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.first<b.first;});v.erase(std::unique(v.begin(),v.end(),[](auto&a,auto&b){return a.first==b.first;}),v.end());return v;}
static bool hard(std::string const&w){int bal=0,n=0;auto fl=[&](){bool z=n>=2;bal=n=0;return z;};for(char c:w){if(c=='T'){if(fl())return true;continue;}if(c=='N')continue;int d=c=='U'?1:-1;if(bal==0&&d<0)++n;bal+=d;}return fl();}
static Packed mixed(std::string const&w){State s{};s.n=8;int q=1,sk=0;std::vector<std::array<int,4>> hp;int start=0;while(start<=8){int end=start;while(end<8&&w[end]!='T')++end;int bal=0;std::vector<std::pair<int,int>> neg;int st=-1;for(int i=start;i<end;++i){if(w[i]=='N')continue;int d=w[i]=='U'?1:-1;if(bal==0&&d<0)st=i;bal+=d;if(st>=0&&bal==0){neg.push_back({st,i});st=-1;}}if(neg.size()>=2){hp.push_back({neg[0].first,neg[0].second,neg[1].first,neg[1].second});}start=end+1;}if(hp.size()!=1)throw std::runtime_error("mixed hard gap");auto z=hp[0];std::array<char,8>special{};for(int x:z)special[x]=1;for(int i=0;i<8;++i)if(w[i]=='T'){int c=q++;s.deg[i]=1;s.comp[i]=c;s.stack[sk++]=c;}auto add=[&](int a,int b,int stt){int c=q++;s.deg[a]=s.deg[b]=1;s.comp[a]=s.comp[b]=c;s.status[c]=stt;};add(z[0],z[3],1);add(z[1],z[2],0);s.sp=sk;s.ns=q;return pack(s);}
struct PH{size_t operator()(Packed const&p)const noexcept{uint64_t h=0;for(auto x:p.w)h^=x+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);return h;}};
int main(){MODP=1000000007u;Vec all;int col=0;load_ck("work/formal-probes/raw_wfa_r8.ck",8,col,all);std::vector<Packed>hs;for(auto&p:all)if(unpack(p).sp==3)hs.push_back(p);auto ws=words(3);std::unordered_map<Packed,int,PH> coord;std::vector<std::array<Packed,2>> pairs;int good=0;for(int j=0;j<(int)ws.size();++j){if(!hard(ws[j].second)){coord[ws[j].first]=j;++good;}else{Packed m=mixed(ws[j].second);int c=j;coord[ws[j].first]=c;coord[m]=c;pairs.push_back({ws[j].first,m});auto it=std::lower_bound(hs.begin(),hs.end(),m);if(it==hs.end()||!(*it==m))throw std::runtime_error("mixed missing "+ws[j].second);}}if(good!=856||pairs.size()!=32)throw std::runtime_error("counts");
 size_t outsideHit=0,pairBad=0,edges=0;std::vector<std::vector<std::pair<int,uint32_t>>> rows(hs.size());for(int i=0;i<(int)hs.size();++i){WVec v{{hs[i],1}};auto z=wcolumn(std::move(v),8,false,0);edges+=z.size();for(auto&e:z){auto it=coord.find(e.p);if(it!=coord.end())rows[i].push_back({it->second,e.v});}auto si=coord.find(hs[i]);if(si==coord.end()&&!rows[i].empty()){if(outsideHit<8)std::cerr<<"outside source i="<<i<<" projected_edges="<<rows[i].size()<<"\n";++outsideHit;}if((i&4095)==0)std::cerr<<"row "<<i<<"/"<<hs.size()<<"\n";}
 auto normrow=[](std::vector<std::pair<int,uint32_t>>v){std::sort(v.begin(),v.end());std::vector<std::pair<int,uint32_t>>o;for(auto [j,c]:v){if(!o.empty()&&o.back().first==j)o.back().second+=c;else o.push_back({j,c});}return o;};for(auto&p:pairs){int a=std::lower_bound(hs.begin(),hs.end(),p[0])-hs.begin(),b=std::lower_bound(hs.begin(),hs.end(),p[1])-hs.begin();auto ra=normrow(rows[a]),rb=normrow(rows[b]);if(ra!=rb){if(pairBad<8)std::cerr<<"pair mismatch a="<<a<<" b="<<b<<" sa="<<ra.size()<<" sb="<<rb.size()<<"\n";++pairBad;}}
 std::cout<<"h3_relation_states="<<coord.size()<<" coords=888 good=856 pairs=32 raw="<<hs.size()<<" edges="<<edges<<" outside_hit="<<outsideHit<<" pair_bad="<<pairBad<<" integer_N_closure="<<(outsideHit==0&&pairBad==0)<<"\n";return outsideHit||pairBad?1:0;}
