#define main zero_reference_main_unused
#include "ramstream32_bucket_reverse_fused_selftest.cu"
#undef main

#include "../ramstream32_bucket_orbit_closure_zero.cuh"

static void zc_forward_low(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"zc flow H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_low_orbit_closure_zero(layout,256,4,4);ck(cudaDeviceSynchronize(),"zc flow sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"zc flow D2H");}bkft_free_slots(d);}}
static void zc_forward_high(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"zc fhigh H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_high_orbit_closure_zero(layout,256,4,4);ck(cudaDeviceSynchronize(),"zc fhigh sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"zc fhigh D2H");}bkft_free_slots(d);}}
static void zc_reverse_low(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"zc rlow H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_low_split54_zero(layout,256,4,4);ck(cudaDeviceSynchronize(),"zc rlow sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"zc rlow D2H");}bkft_free_slots(d);}}
static void zc_reverse_high(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"zc rhigh H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_high_split54_zero(layout,256,4,4);ck(cudaDeviceSynchronize(),"zc rhigh sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"zc rhigh D2H");}bkft_free_slots(d);}}

int main(){
    constexpr Count mod=4294967291u;constexpr int W=TARGET_W,L=LOW_LUT_K;static_assert(W<=12,"closure-zero selftest uses small width");int visible=0;cudaError_t ce=cudaGetDeviceCount(&visible);if(ce!=cudaSuccess||visible<1){std::cout<<"bucket-closure-zero-selftest SKIP no CUDA device\n";return 0;}ck(cudaSetDevice(0),"zc set device");
    build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);
    uint64_t key4_checked=0;for(uint32_t code:storage.low_all_codes){uint32_t a=gpu_direct_ternary_key_host(code,LOW_LUT_K),b=bkcz_ternary_key4_legal<LOW_LUT_K>(code);if(a!=b){std::cerr<<"chunked LOW ternary key mismatch code="<<code<<" old="<<a<<" new="<<b<<'\n';return 8;}++key4_checked;}for(uint32_t code:storage.high_all_codes){uint32_t a=gpu_direct_ternary_key_host(code,HIGH_LUT_K),b=bkcz_ternary_key4_legal<HIGH_LUT_K>(code);if(a!=b){std::cerr<<"chunked HIGH ternary key mismatch code="<<code<<" old="<<a<<" new="<<b<<'\n';return 9;}++key4_checked;}
    StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);HighDescHost highdesc=build_high_descriptors(storage,layout);LowOrbitHost loworbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuHighDirectHost highdirect=build_cpu_high_direct(storage,layout,highdesc);GpuDirectGatherHost ordinary=build_gpu_direct_gather(layout,lowdesc,loworbit,highdirect);GpuDirectCrossGatherHost cross=build_gpu_direct_cross_gather(storage,layout,lowdesc,loworbit,highdirect);GpuDirectFusedHost fused=build_gpu_direct_fused_checked(layout,ordinary,cross);CpuLowSparseHost lowsparse=build_cpu_low_sparse(storage,layout,lowdesc,loworbit);BucketOwnerHost owner=build_bucket_owners(G_FACTOR,storage);BucketPhysicalLayoutHost phy=build_bucket_physical_layout(layout,owner);BucketOrbitStreamsHost bo=build_bucket_orbits(storage,layout,owner,lowsparse,highdirect);BucketFusedHost bf=build_bucket_fused(storage,layout,owner,ordinary,cross,fused);ReverseLowDescHost rlow=build_reverse_low_descriptors(storage,layout);ReverseHighDescHost rhigh=build_reverse_high_descriptors(storage,layout);ReverseOrbitHost rlo=build_reverse_orbit(storage,layout,true),rhi=build_reverse_orbit(storage,layout,false);ReverseBucketAtomicHost rb=build_reverse_bucket_atomic(storage,layout,owner,rlow,rhigh,rlo,rhi);ReverseSplit54Host rs54=build_reverse_split54(layout,rb,false);
    auto ms=gdg_enum_states(W),bs=gdg_enum_states(W-1);std::unordered_map<MateID,size_t>mi,di;for(size_t i=0;i<ms.size();++i)mi.emplace(ms[i],i);for(size_t i=0;i<bs.size();++i)di.emplace(bs[i],i);std::mt19937_64 rng(0x1618C200ULL);std::vector<Count>im(ms.size()),ib(bs.size());for(auto&x:im)x=Count(rng()%mod);for(auto&x:ib)x=Count(rng()%mod);auto[flm,flb]=gdg_reference_window(W,L,1,mod,ms,bs,mi,di,im,ib);auto[fhm,fhb]=gdg_reference_window(W,W-1,L+1,mod,ms,bs,mi,di,im,ib);auto[rlm,rlb]=bra_reference(1,L,mod,ms,bs,mi,di,im,ib);auto[rhm,rhb]=bra_reference(L+1,W-1,mod,ms,bs,mi,di,im,ib);
    ck(cudaMemcpyToSymbol(D_MOD,&mod,sizeof(mod)),"zc modulus");BucketFusedDeviceTables dt;dt.install_metadata(layout,bo,bf);ReverseSplit54DeviceTables rs;rs.install(rs54);
    auto g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);zc_forward_low(g,layout,phy,dt);if(!bkft_compare("zero-forward-low",g,ms,bs,flm,flb,storage,layout,owner,phy))return 10;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);zc_forward_high(g,layout,phy,dt);if(!bkft_compare("zero-forward-high",g,ms,bs,fhm,fhb,storage,layout,owner,phy))return 11;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);zc_reverse_low(g,layout,phy,dt);if(!bkft_compare("zero-reverse-low",g,ms,bs,rlm,rlb,storage,layout,owner,phy))return 12;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);zc_reverse_high(g,layout,phy,dt);if(!bkft_compare("zero-reverse-high",g,ms,bs,rhm,rhb,storage,layout,owner,phy))return 13;
    std::cout<<"bucket-closure-zero-selftest OK W="<<W<<" closure_record_bytes=0 closure_source_bytes=0 closure_attach_bytes=0 reverse_orbit_bytes="<<rs54.bytes()<<" ternary_key4_match=1 ternary_key4_checked="<<key4_checked<<" pm_accum="<<GPU_DIRECT_PM_ACCUM<<"\n";rs.release();dt.release();return 0;
}
