#define main reverse_split18_reference_main_unused
#include "ramstream32_bucket_reverse_fused_selftest.cu"
#undef main
#include "../ramstream32_bucket_reverse_split18.cuh"
#include "../ramstream32_bucket_orbit_closure_preflight.cuh"

static void rs18_run_low(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"rs18 low H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_low_split18(layout,256,4,4);ck(cudaDeviceSynchronize(),"rs18 low sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"rs18 low D2H");}bkft_free_slots(d);}}
static void rs18_run_high(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"rs18 high H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_high_split18(layout,256,4,4);ck(cudaDeviceSynchronize(),"rs18 high sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"rs18 high D2H");}bkft_free_slots(d);}}

int main(){
    constexpr Count mod=4294967291u;constexpr int W=TARGET_W,L=LOW_LUT_K;static_assert(W<=12,"reverse split18 selftest uses small width");
    int visible=0;cudaError_t ce=cudaGetDeviceCount(&visible);if(ce!=cudaSuccess||visible<1){std::cout<<"bucket-reverse-split18-selftest SKIP no CUDA device\n";return 0;}ck(cudaSetDevice(0),"rs18 set device");
    build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);HighDescHost highdesc=build_high_descriptors(storage,layout);LowOrbitHost loworbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuHighDirectHost highdirect=build_cpu_high_direct(storage,layout,highdesc);GpuDirectGatherHost ordinary=build_gpu_direct_gather(layout,lowdesc,loworbit,highdirect);GpuDirectCrossGatherHost cross=build_gpu_direct_cross_gather(storage,layout,lowdesc,loworbit,highdirect);GpuDirectFusedHost fused=build_gpu_direct_fused_checked(layout,ordinary,cross);CpuLowSparseHost lowsparse=build_cpu_low_sparse(storage,layout,lowdesc,loworbit);BucketOwnerHost owner=build_bucket_owners(G_FACTOR,storage);BucketPhysicalLayoutHost phy=build_bucket_physical_layout(layout,owner);BucketOrbitStreamsHost bo=build_bucket_orbits(storage,layout,owner,lowsparse,highdirect);BucketFusedHost bf=build_bucket_fused(storage,layout,owner,ordinary,cross,fused);ReverseLowDescHost rlow=build_reverse_low_descriptors(storage,layout);ReverseHighDescHost rhigh=build_reverse_high_descriptors(storage,layout);ReverseOrbitHost rlo=build_reverse_orbit(storage,layout,true),rhi=build_reverse_orbit(storage,layout,false);ReverseBucketAtomicHost rb=build_reverse_bucket_atomic(storage,layout,owner,rlow,rhigh,rlo,rhi);ReverseBucketFusedHost rf=build_reverse_bucket_fused_checked(layout,owner,rb);auto att=build_bucket_reverse_orbit_closure_attach_checked(layout,bo,bf,rb,rf);auto split=build_reverse_split18(layout,rb,rf,att);
    auto ms=gdg_enum_states(W),bs=gdg_enum_states(W-1);std::unordered_map<MateID,size_t>mi,di;for(size_t i=0;i<ms.size();++i)mi.emplace(ms[i],i);for(size_t i=0;i<bs.size();++i)di.emplace(bs[i],i);std::mt19937_64 rng(0x1618a518ULL);std::vector<Count>im(ms.size()),ib(bs.size());for(auto&x:im)x=Count(rng()%mod);for(auto&x:ib)x=Count(rng()%mod);auto[lm,lb]=bra_reference(1,L,mod,ms,bs,mi,di,im,ib);auto[hm,hb]=bra_reference(L+1,W-1,mod,ms,bs,mi,di,im,ib);
    ck(cudaMemcpyToSymbol(D_MOD,&mod,sizeof(mod)),"rs18 modulus");BucketFusedDeviceTables dt;dt.install_metadata(layout,bo,bf);ReverseBucketFusedClosureOnlyTables ct;ct.install(rb,rf);ReverseSplit18DeviceTables st;st.install(split);
    auto g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);rs18_run_low(g,layout,phy,dt);if(!bkft_compare("reverse-split18-low",g,ms,bs,lm,lb,storage,layout,owner,phy))return 10;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);rs18_run_high(g,layout,phy,dt);if(!bkft_compare("reverse-split18-high",g,ms,bs,hm,hb,storage,layout,owner,phy))return 11;
    size_t old_orbit=reverse_bucket_orbit_bytes(rb),new_orbit=split.bytes();std::cout<<"bucket-reverse-split18-selftest OK W="<<W<<" old_orbit_mib="<<double(old_orbit)/double(1<<20)<<" split_orbit_mib="<<double(new_orbit)/double(1<<20)<<" kind_bits=0 jblock_bits=0 bytes_per_orbit_payload=9 pm_accum="<<GPU_DIRECT_PM_ACCUM<<"\n";st.release();ct.release();dt.release();return 0;
}
