#define BUCKET_SNAKE_REVERSE_FUSED 1
#define main full_inverse_driver_main_unused
#include "../../b300/oneesan_cuda_gridfp_b300_bucket_snake_atomic.cu"
#undef main
#include "../../common/gridfp_closure_inverse.hpp"

#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <vector>

static int finv_delta(uint32_t c){return c==uint32_t(::L)?1:(c==uint32_t(R)?-1:0);}
static uint32_t finv_low_code_at(const BucketFusedHost&bf,uint32_t loc,int h){uint32_t g=bkf_loc_owner(loc),r=bkf_loc_rank(loc);return bf.low_codes[bf.low_code_off[size_t(g)*bf.code_pitch+h]+r];}
static uint32_t finv_high_code_at(const BucketFusedHost&bf,uint32_t loc,int h){uint32_t g=bkf_loc_owner(loc),r=bkf_loc_rank(loc);return bf.high_codes[bf.high_code_off[size_t(g)*bf.code_pitch+h]+r];}
static uint32_t finv_low_source(MateID partial,int he,const StorageFactorHost&s,const StorageLayout&layout,const BucketOwnerHost&o){constexpr int K=LOW_LUT_K;constexpr uint64_t MASK=(uint64_t(1)<<(2*K))-1;uint32_t c=uint32_t(mget(partial,K)),lc=uint32_t(partial&MASK);int hs=he+finv_delta(c);if(he<0||he>HIGH_LUT_K+1||hs<0||hs>LOW_LUT_K+1)return 0xffffffffu;uint32_t bid=uint32_t(3*he+int(c));if(bid>=layout.main_blocks.size()||!layout.main_blocks[bid].valid||layout.main_blocks[bid].hs!=hs)return 0xffffffffu;uint32_t pr=s.low_packed_rank[lc];if(pr==0xffffffffu)return 0xffffffffu;uint32_t ar=pr>>K,n=s.low_all_off[hs+1]-s.low_all_off[hs];if(ar>=n||s.low_all_codes[s.low_all_off[hs]+ar]!=lc)return 0xffffffffu;return bkf_src_pack(bid,bucket_low_locator(s,o,hs,ar));}
static uint32_t finv_high_source(MateID partial,int hs,const StorageFactorHost&s,const StorageLayout&layout,const BucketOwnerHost&o){constexpr int K=HIGH_LUT_K;constexpr uint64_t MASK=(uint64_t(1)<<(2*K))-1;uint32_t c=uint32_t(mget(partial,0)),hc=uint32_t((partial>>2)&MASK);int he=hs-finv_delta(c);if(hs<0||hs>LOW_LUT_K+1||he<0||he>HIGH_LUT_K+1)return 0xffffffffu;uint32_t bid=uint32_t(3*he+int(c));if(bid>=layout.main_blocks.size()||!layout.main_blocks[bid].valid||layout.main_blocks[bid].hs!=hs)return 0xffffffffu;uint32_t pr=s.high_packed_rank[hc];if(pr==0xffffffffu)return 0xffffffffu;uint32_t ar=pr>>K,n=s.high_all_off[he+1]-s.high_all_off[he];if(ar>=n||s.high_all_codes[s.high_all_off[he]+ar]!=hc)return 0xffffffffu;return bkf_src_pack(bid,bucket_high_locator(s,o,he,ar));}
static uint32_t finv_cross_pack_from_src(uint32_t src,uint32_t depth){return src==0xffffffffu?0xffffffffu:bkf_cross_pack(bkf_src_block(src),bkf_src_locator(src),depth);}
static void finv_cmp(std::vector<uint32_t>got,std::vector<uint32_t>want,const char*kind,const char*side,int p,uint32_t dbid,uint32_t q){
    std::sort(got.begin(),got.end());std::sort(want.begin(),want.end());
    if(got!=want){
        std::cerr<<"full closure inverse mismatch kind="<<kind<<" side="<<side<<" p="<<p<<" dbid="<<dbid<<" q="<<q<<" got="<<got.size()<<" want="<<want.size()<<'\n';
        size_t n=std::min(got.size(),want.size());for(size_t i=0;i<n;++i)if(got[i]!=want[i]){std::cerr<<" first_diff="<<i<<" got_value="<<got[i]<<" want_value="<<want[i]<<'\n';break;}
        std::exit(530);
    }
}

int main(){
    build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);HighDescHost highdesc=build_high_descriptors(storage,layout);LowOrbitHost loworbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuHighDirectHost highdirect=build_cpu_high_direct(storage,layout,highdesc);GpuDirectGatherHost ordinary=build_gpu_direct_gather(layout,lowdesc,loworbit,highdirect);GpuDirectCrossGatherHost cross=build_gpu_direct_cross_gather(storage,layout,lowdesc,loworbit,highdirect);GpuDirectFusedHost fused=build_gpu_direct_fused_checked(layout,ordinary,cross);BucketOwnerHost owner=build_bucket_owners(G_FACTOR,storage);BucketFusedHost bf=build_bucket_fused(storage,layout,owner,ordinary,cross,fused);ReverseLowDescHost rlow=build_reverse_low_descriptors(storage,layout);ReverseHighDescHost rhigh=build_reverse_high_descriptors(storage,layout);ReverseOrbitHost rlo=build_reverse_orbit(storage,layout,true),rhi=build_reverse_orbit(storage,layout,false);ReverseBucketAtomicHost rb=build_reverse_bucket_atomic(storage,layout,owner,rlow,rhigh,rlo,rhi);ReverseBucketFusedHost rf=build_reverse_bucket_fused_checked(layout,owner,rb);
    MateID cand[32],xsrc=0;uint64_t records=0,local_edges=0,cross_edges=0,cross_candidates=0;
    auto check_low=[&](bool rev){const auto&fd=rev?rf.low_dst:bf.low_dst;const auto&fo=rev?rf.low_off:bf.low_off;uint32_t pitch=rev?rf.low_pitch:bf.low_pitch;const auto&ls=rev?rf.low_local_src:bf.low_local_src;const auto&xs=rev?rf.low_cross_op:bf.low_cross_op;for(int p=rev?1:LOW_LUT_K;rev?p<=LOW_LUT_K:p>=1;rev?++p:--p){uint32_t pi=rev?uint32_t(p-1):uint32_t(LOW_LUT_K-p);bool tm=!rev&&p==1;uint32_t nt=tm?uint32_t(layout.main_blocks.size()):uint32_t(layout.block_blocks.size());for(uint32_t dbid=0;dbid<nt;++dbid){const StorageBlock&db=tm?layout.main_blocks[dbid]:layout.block_blocks[dbid];size_t oi=size_t(pi)*pitch+dbid;for(uint32_t q=fo[oi];q<fo[oi+1];++q){const auto&r=fd[q];uint32_t dc=finv_low_code_at(bf,r.dst_locator,db.hs);MateID partial=tm?(MateID(dc)|(MateID(db.c)<<(2*LOW_LUT_K))):(rev?blocked_exclude_reverse(MateID(dc),LOW_LUT_K+1,p):minsert(MateID(dc),p,N));int n=rev?ordinary_closure_preimages_partial_reverse(partial,LOW_LUT_K+1,p,cand):ordinary_closure_preimages_partial(partial,LOW_LUT_K+1,p,cand);std::vector<uint32_t>gl,wl,gx,wx;for(int i=0;i<n;++i){uint32_t z=finv_low_source(cand[i],db.he,storage,layout,owner);if(z!=0xffffffffu)gl.push_back(z);}uint32_t lc=r.counts&0xffffu,cc=r.counts>>16;for(uint32_t e=r.local_begin;e<r.local_begin+lc;++e)wl.push_back(ls[e]);int depth=low_cross_preimage_partial(partial,LOW_LUT_K+1,p,xsrc);if(depth>0){uint32_t z=finv_low_source(xsrc,int(db.he)+2,storage,layout,owner);z=finv_cross_pack_from_src(z,uint32_t(depth));if(z!=0xffffffffu)gx.push_back(z);}for(uint32_t e=r.cross_begin;e<r.cross_begin+cc;++e)wx.push_back(xs[e]);finv_cmp(gl,wl,"ordinary",rev?"reverse-low":"forward-low",p,dbid,q);finv_cmp(gx,wx,"cross",rev?"reverse-low":"forward-low",p,dbid,q);++records;local_edges+=gl.size();cross_edges+=wx.size();cross_candidates+=gx.size();}}}}
    };
    auto check_high=[&](bool rev){const auto&fd=rev?rf.high_dst:bf.high_dst;const auto&fo=rev?rf.high_off:bf.high_off;uint32_t pitch=rev?rf.high_pitch:bf.high_pitch;const auto&ls=rev?rf.high_local_src:bf.high_local_src;const auto&xs=rev?rf.high_cross_op:bf.high_cross_op;int p0=LOW_LUT_K+1,p1=TARGET_W-1;for(int p=rev?p0:p1;rev?p<=p1:p>=p0;rev?++p:--p){uint32_t pi=rev?uint32_t(p-p0):uint32_t(p1-p),rel=uint32_t(p-LOW_LUT_K);bool tm=rev&&p==p1;uint32_t nt=tm?uint32_t(layout.main_blocks.size()):uint32_t(layout.block_blocks.size());for(uint32_t dbid=0;dbid<nt;++dbid){const StorageBlock&db=tm?layout.main_blocks[dbid]:layout.block_blocks[dbid];size_t oi=size_t(pi)*pitch+dbid;for(uint32_t q=fo[oi];q<fo[oi+1];++q){const auto&r=fd[q];uint32_t dc=finv_high_code_at(bf,r.dst_locator,db.he);MateID partial=tm?(MateID(db.c)|(MateID(dc)<<2)):(rev?blocked_exclude_reverse(MateID(dc),HIGH_LUT_K+1,int(rel)):minsert(MateID(dc),int(rel),N));int n=rev?ordinary_closure_preimages_partial_reverse(partial,HIGH_LUT_K+1,int(rel),cand):ordinary_closure_preimages_partial(partial,HIGH_LUT_K+1,int(rel),cand);std::vector<uint32_t>gl,wl,gx,wx;for(int i=0;i<n;++i){uint32_t z=finv_high_source(cand[i],db.hs,storage,layout,owner);if(z!=0xffffffffu)gl.push_back(z);}uint32_t lc=r.counts&0xffffu,cc=r.counts>>16;for(uint32_t e=r.local_begin;e<r.local_begin+lc;++e)wl.push_back(ls[e]);int depth=high_cross_preimage_partial(partial,HIGH_LUT_K+1,int(rel),xsrc);if(depth>0){uint32_t z=finv_high_source(xsrc,int(db.hs)+2,storage,layout,owner);z=finv_cross_pack_from_src(z,uint32_t(depth));if(z!=0xffffffffu)gx.push_back(z);}for(uint32_t e=r.cross_begin;e<r.cross_begin+cc;++e)wx.push_back(xs[e]);finv_cmp(gl,wl,"ordinary",rev?"reverse-high":"forward-high",p,dbid,q);finv_cmp(gx,wx,"cross",rev?"reverse-high":"forward-high",p,dbid,q);++records;local_edges+=gl.size();cross_edges+=wx.size();cross_candidates+=gx.size();}}}}
    };
    check_low(false);check_high(false);check_low(true);check_high(true);
    std::cout<<"closure-full-inverse-plan OK W="<<TARGET_W<<" records="<<records<<" local_edges="<<local_edges<<" cross_edges="<<cross_edges<<" generated_cross="<<cross_candidates<<" exact_multiset=1 local_source_csr_eliminable=1 cross_op_csr_eliminable=1 source_metadata_entries=0\n";return 0;
}
