#define main inline8_reference_main_unused
#include "ramstream32_bucket_reverse_fused_selftest.cu"
#undef main

#include "../ramstream32_bucket_orbit_closure_inline8_hybrid18.cuh"
#include "../ramstream32_bucket_reverse_closure_only.cuh"

static void i8_forward_low(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"i8 flow H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_low_orbit_closure18_inline8(layout,256,4,4);ck(cudaDeviceSynchronize(),"i8 flow sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"i8 flow D2H");}bkft_free_slots(d);}}
static void i8_forward_high(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"i8 fhigh H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_high_orbit_closure18_inline8(layout,256,4,4);ck(cudaDeviceSynchronize(),"i8 fhigh sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"i8 fhigh D2H");}bkft_free_slots(d);}}
static void i8_reverse_low(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"i8 rlow H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_low_split18_inline8(layout,256,4,4);ck(cudaDeviceSynchronize(),"i8 rlow sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"i8 rlow D2H");}bkft_free_slots(d);}}
static void i8_reverse_high(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"i8 rhigh H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_high_split18_inline8(layout,256,4,4);ck(cudaDeviceSynchronize(),"i8 rhigh sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"i8 rhigh D2H");}bkft_free_slots(d);}}

int main(){
    constexpr Count mod=4294967291u;constexpr int W=TARGET_W,L=LOW_LUT_K;static_assert(W<=12,"inline8 hybrid18 selftest uses small width");
    int visible=0;cudaError_t ce=cudaGetDeviceCount(&visible);if(ce!=cudaSuccess||visible<1){std::cout<<"bucket-onepass-inline8-hybrid18-selftest SKIP no CUDA device\n";return 0;}ck(cudaSetDevice(0),"i8 set device");
    build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);HighDescHost highdesc=build_high_descriptors(storage,layout);LowOrbitHost loworbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuHighDirectHost highdirect=build_cpu_high_direct(storage,layout,highdesc);GpuDirectGatherHost ordinary=build_gpu_direct_gather(layout,lowdesc,loworbit,highdirect);GpuDirectCrossGatherHost cross=build_gpu_direct_cross_gather(storage,layout,lowdesc,loworbit,highdirect);GpuDirectFusedHost fused=build_gpu_direct_fused_checked(layout,ordinary,cross);CpuLowSparseHost lowsparse=build_cpu_low_sparse(storage,layout,lowdesc,loworbit);BucketOwnerHost owner=build_bucket_owners(G_FACTOR,storage);BucketPhysicalLayoutHost phy=build_bucket_physical_layout(layout,owner);BucketOrbitStreamsHost bo=build_bucket_orbits(storage,layout,owner,lowsparse,highdirect);BucketFusedHost bf=build_bucket_fused(storage,layout,owner,ordinary,cross,fused);ReverseLowDescHost rlow=build_reverse_low_descriptors(storage,layout);ReverseHighDescHost rhigh=build_reverse_high_descriptors(storage,layout);ReverseOrbitHost rlo=build_reverse_orbit(storage,layout,true),rhi=build_reverse_orbit(storage,layout,false);ReverseBucketAtomicHost rb=build_reverse_bucket_atomic(storage,layout,owner,rlow,rhigh,rlo,rhi);ReverseBucketFusedHost rf=build_reverse_bucket_fused_checked(layout,owner,rb);
    auto f18=build_bucket_forward_orbit_closure_attach18(layout,bo,bf);auto fullr=build_bucket_reverse_orbit_closure_attach_checked(layout,bo,bf,rb,rf);auto rs18=build_reverse_split18(layout,rb,rf,fullr);auto fi8=build_bucket_forward_onepass_inline8(bf);auto ri8=build_bucket_reverse_onepass_inline8(rf);
    auto ms=gdg_enum_states(W),bs=gdg_enum_states(W-1);std::unordered_map<MateID,size_t>mi,di;for(size_t i=0;i<ms.size();++i)mi.emplace(ms[i],i);for(size_t i=0;i<bs.size();++i)di.emplace(bs[i],i);std::mt19937_64 rng(0x1618A118ULL);std::vector<Count>im(ms.size()),ib(bs.size());for(auto&x:im)x=Count(rng()%mod);for(auto&x:ib)x=Count(rng()%mod);auto[flm,flb]=gdg_reference_window(W,L,1,mod,ms,bs,mi,di,im,ib);auto[fhm,fhb]=gdg_reference_window(W,W-1,L+1,mod,ms,bs,mi,di,im,ib);auto[rlm,rlb]=bra_reference(1,L,mod,ms,bs,mi,di,im,ib);auto[rhm,rhb]=bra_reference(L+1,W-1,mod,ms,bs,mi,di,im,ib);
    ck(cudaMemcpyToSymbol(D_MOD,&mod,sizeof(mod)),"i8 modulus");BucketFusedDeviceTables dt;dt.install_metadata(layout,bo,bf);ReverseBucketFusedClosureOnlyDirectTables rt;rt.install(rb,rf);BucketForwardOrbitClosureAttach18DeviceTables fa;fa.install(f18);ReverseSplit18DeviceTables rs;rs.install(rs18);BucketForwardOnePassInline8DeviceTables fid;fid.install(fi8);BucketReverseOnePassInline8DeviceTables rid;rid.install(ri8);
    auto g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);i8_forward_low(g,layout,phy,dt);if(!bkft_compare("inline8-forward-low",g,ms,bs,flm,flb,storage,layout,owner,phy))return 10;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);i8_forward_high(g,layout,phy,dt);if(!bkft_compare("inline8-forward-high",g,ms,bs,fhm,fhb,storage,layout,owner,phy))return 11;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);i8_reverse_low(g,layout,phy,dt);if(!bkft_compare("inline8-reverse-low",g,ms,bs,rlm,rlb,storage,layout,owner,phy))return 12;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);i8_reverse_high(g,layout,phy,dt);if(!bkft_compare("inline8-reverse-high",g,ms,bs,rhm,rhb,storage,layout,owner,phy))return 13;
    size_t old=(bf.low_dst.size()+bf.high_dst.size()+rf.low_dst.size()+rf.high_dst.size())*sizeof(BucketFusedDst)+(bf.low_local_src.size()+bf.low_cross_op.size()+bf.high_local_src.size()+bf.high_cross_op.size()+rf.low_local_src.size()+rf.low_cross_op.size()+rf.high_local_src.size()+rf.high_cross_op.size())*sizeof(uint32_t);size_t nw=fi8.bytes()+ri8.bytes();std::cout<<"bucket-onepass-inline8-hybrid18-selftest OK W="<<W<<" closure_old_mib="<<double(old)/double(1<<20)<<" closure_inline8_mib="<<double(nw)/double(1<<20)<<" ratio="<<(old?double(nw)/double(old):0.0)<<" pm_accum="<<GPU_DIRECT_PM_ACCUM<<"\n";
    rid.release();fid.release();rs.release();fa.release();rt.release();dt.release();return 0;
}
