#define RAMSTREAM_CPU_LOW_WORKER_LOCALITY_SELFTEST_NO_MAIN
#include "ramstream32_cpu_low_domain_worker_locality_selftest.cu"
#undef RAMSTREAM_CPU_LOW_WORKER_LOCALITY_SELFTEST_NO_MAIN

#include "../ramstream32_cpu_low_domain_worker_multistart.hpp"
#include "../ramstream32_cpu_low_domain_worker_unique_shared_coalesce.hpp"
#include "../ramstream32_cpu_low_domain_worker_unique_fixedpoint.hpp"
#include "../ramstream32_cpu_low_domain_worker_neutral_balance.hpp"

static uint64_t plmax(const CpuLowSparsePersistentPool&p){return p.sticky_worker_cells.empty()?0:*std::max_element(p.sticky_worker_cells.begin(),p.sticky_worker_cells.end());}
static bool pleq(const CpuLowDomainWorkerUniqueScore&a,const CpuLowDomainWorkerUniqueScore&b){return a.pages_2m==b.pages_2m&&a.pages_4k==b.pages_4k&&a.transitions==b.transitions;}
static const CpuLowSparsePersistentPool* plchoose(CpuLowSparsePersistentPool&a,CpuLowWorkerFixedPointStats&as,CpuLowSparsePersistentPool&b,CpuLowWorkerFixedPointStats&bs){bool bb=cpu_low_worker_unique_score_less(bs.after,as.after),ab=cpu_low_worker_unique_score_less(as.after,bs.after);if(bb||(!ab&&plmax(b)<plmax(a)))return &b;return &a;}

int main(){
 constexpr Count mod=4294967291u;constexpr int W=TARGET_W;static_assert(W==LOW_LUT_K+HIGH_LUT_K+1);static_assert(W<=12,"plateau selftest uses small W");
 build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);LowOrbitHost orbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuLowSparseHost sparse=build_cpu_low_sparse(storage,layout,lowdesc,orbit);WindowPlan low_wp=make_direct2d_window(false);auto jobs=make_cpu_low_jobs(W,low_wp);
 CpuLowSparsePersistentPool d(4,CPU_LOW_SCHEDULE_DOMAIN,2,true),h(4,CPU_LOW_SCHEDULE_DOMAIN,2,true),parent(4,CPU_LOW_SCHEDULE_DOMAIN,2,true);for(auto*p:{&d,&h,&parent}){p->prepare_static_schedule(jobs,sparse);cpu_low_apply_domain_page_tiebreak(*p,jobs,sparse,storage,layout);cpu_low_apply_domain_worker_locality(*p,jobs,sparse);}CpuLowWorkerExactWorkspace ws=cpu_low_build_worker_exact_workspace(jobs,sparse,storage,layout);
 auto ds=cpu_low_apply_domain_worker_unique_shared_coalesce(d,jobs,sparse,ws);cpu_low_apply_domain_worker_coalesce(h,jobs,sparse,storage,layout);auto hs=cpu_low_apply_domain_worker_unique_shared_coalesce(h,jobs,sparse,ws);CpuLowDomainWorkerUniqueCoalesceStats cd{},ch{};cd.unique_pages_2m_after=ds.unique_pages_2m_after;cd.unique_pages_4k_after=ds.unique_pages_4k_after;cd.owner_transitions_after=ds.owner_transitions_after;ch.unique_pages_2m_after=hs.unique_pages_2m_after;ch.unique_pages_4k_after=hs.unique_pages_4k_after;ch.owner_transitions_after=hs.owner_transitions_after;auto md=cpu_low_choose_worker_multistart(d,cd,h,ch);cpu_low_copy_worker_static_schedule(parent,md.source==CPU_LOW_WORKER_MULTISTART_HYBRID?h:d);
 CpuLowSparsePersistentPool rs(4,CPU_LOW_SCHEDULE_DOMAIN,2,true),sr(4,CPU_LOW_SCHEDULE_DOMAIN,2,true),baseline(4,CPU_LOW_SCHEDULE_DOMAIN,2,true);rs.prepare_static_schedule(jobs,sparse);sr.prepare_static_schedule(jobs,sparse);baseline.prepare_static_schedule(jobs,sparse);cpu_low_copy_worker_static_schedule(rs,parent);cpu_low_copy_worker_static_schedule(sr,parent);auto r=cpu_low_apply_worker_exact_fixedpoint(rs,jobs,sparse,ws,CPU_LOW_WORKER_FIXED_RUN_SWAP,4,4);auto s=cpu_low_apply_worker_exact_fixedpoint(sr,jobs,sparse,ws,CPU_LOW_WORKER_FIXED_SWAP_RUN,4,4);if(r.component_limit_hit||r.round_limit_hit||s.component_limit_hit||s.round_limit_hit)return 1;const auto*bw=plchoose(rs,r,sr,s);cpu_low_copy_worker_static_schedule(baseline,*bw);CpuLowDomainWorkerUniqueScore base=(bw==&rs?r.after:s.after);uint64_t base_max=plmax(baseline);
 CpuLowSparsePersistentPool plateau(4,CPU_LOW_SCHEDULE_DOMAIN,2,true);plateau.prepare_static_schedule(jobs,sparse);cpu_low_copy_worker_static_schedule(plateau,baseline);auto neutral=cpu_low_apply_worker_neutral_balance(plateau,jobs,sparse,ws);if(neutral.move_limit_hit||!pleq(neutral.exact_before,base)||!pleq(neutral.exact_after,base)||plmax(plateau)>base_max)return 2;
 CpuLowSparsePersistentPool rr(4,CPU_LOW_SCHEDULE_DOMAIN,2,true),ss(4,CPU_LOW_SCHEDULE_DOMAIN,2,true),selected(4,CPU_LOW_SCHEDULE_DOMAIN,2,true);rr.prepare_static_schedule(jobs,sparse);ss.prepare_static_schedule(jobs,sparse);selected.prepare_static_schedule(jobs,sparse);cpu_low_copy_worker_static_schedule(rr,plateau);cpu_low_copy_worker_static_schedule(ss,plateau);auto rrst=cpu_low_apply_worker_exact_fixedpoint(rr,jobs,sparse,ws,CPU_LOW_WORKER_FIXED_RUN_SWAP,4,4);auto ssst=cpu_low_apply_worker_exact_fixedpoint(ss,jobs,sparse,ws,CPU_LOW_WORKER_FIXED_SWAP_RUN,4,4);if(rrst.component_limit_hit||rrst.round_limit_hit||ssst.component_limit_hit||ssst.round_limit_hit)return 3;const auto*fw=plchoose(rr,rrst,ss,ssst);CpuLowDomainWorkerUniqueScore final=(fw==&rr?rrst.after:ssst.after);if(cpu_low_worker_unique_score_less(base,final))return 4;cpu_low_copy_worker_static_schedule(selected,*fw);if(plmax(selected)>base_max)return 5;
 auto main_states=enum_states(W);auto block_states=enum_states(W-1);if(main_states.size()!=layout.main_size||block_states.size()!=layout.block_size)return 6;std::unordered_map<MateID,size_t>mi,di;for(size_t i=0;i<main_states.size();++i)mi.emplace(main_states[i],i);for(size_t i=0;i<block_states.size();++i)di.emplace(block_states[i],i);std::vector<Count>im(main_states.size()),ib(block_states.size());std::mt19937_64 rng(351618);for(auto&x:im)x=Count(rng()%mod);for(auto&x:ib)x=Count(rng()%mod);auto one=reference_window(W,LOW_LUT_K,1,mod,main_states,block_states,mi,di,im,ib);if(one.first.empty())return 7;auto two=reference_window(W,LOW_LUT_K,1,mod,main_states,block_states,mi,di,one.first,one.second);if(two.first.empty())return 8;RamCounts ma,ba;ma.alloc(layout.main_size,"plateau main");ba.alloc(layout.block_size,"plateau block");fill_factor(ma,ba,main_states,block_states,im,ib,storage,layout);selected.run(jobs,ma,ba,storage,layout,sparse,mod);if(!compare_factor("plateau-1",ma,ba,main_states,block_states,one.first,one.second,storage,layout))return 9;selected.run(jobs,ma,ba,storage,layout,sparse,mod);if(!compare_factor("plateau-2",ma,ba,main_states,block_states,two.first,two.second,storage,layout))return 10;
 std::cout<<"cpu-low-worker-plateau-selftest OK neutral_moves="<<neutral.accepted_moves<<" baseline_2m="<<base.pages_2m<<" final_2m="<<final.pages_2m<<" baseline_4k="<<base.pages_4k<<" final_4k="<<final.pages_4k<<" exact_generations=2\n";
 d.shutdown();h.shutdown();parent.shutdown();rs.shutdown();sr.shutdown();baseline.shutdown();plateau.shutdown();rr.shutdown();ss.shutdown();selected.shutdown();ma.release();ba.release();return 0;
}
