#define BUCKET_SNAKE_REVERSE_FUSED 1
#define main bkoc18_driver_main_unused
#include "../../b300/oneesan_cuda_gridfp_b300_bucket_snake_atomic.cu"
#undef main
#include "../ramstream32_bucket_reverse_fused_validate.hpp"
#include "../ramstream32_bucket_orbit_closure_packed18.cuh"
#include "../ramstream32_bucket_forward_packed18_direct.hpp"

#include <cstdint>
#include <cstdlib>
#include <iostream>

static uint32_t fcode18(BucketOrbitOp op,uint8_t hi){return (uint32_t(hi)<<10)|uint32_t((op>>54)&0x3ffu);}
static uint32_t rcode18(ReverseBucketOrbitOp op,uint8_t mid,const std::vector<uint8_t>&hi2,size_t q){return (bkoc18_get_hi2_host(hi2,q)<<16)|(uint32_t(mid)<<8)|uint32_t((op>>56)&0xffu);}
static uint32_t rid18(uint32_t z,const std::vector<uint32_t>&off,size_t oi){return z==BKOC18_NONE?BKOC_NONE:off[oi]+z;}

int main(){
    build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);HighDescHost highdesc=build_high_descriptors(storage,layout);LowOrbitHost loworbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuHighDirectHost highdirect=build_cpu_high_direct(storage,layout,highdesc);GpuDirectGatherHost ordinary=build_gpu_direct_gather(layout,lowdesc,loworbit,highdirect);GpuDirectCrossGatherHost cross=build_gpu_direct_cross_gather(storage,layout,lowdesc,loworbit,highdirect);GpuDirectFusedHost fused=build_gpu_direct_fused_checked(layout,ordinary,cross);CpuLowSparseHost lowsparse=build_cpu_low_sparse(storage,layout,lowdesc,loworbit);BucketOwnerHost owner=build_bucket_owners(G_FACTOR,storage);BucketOrbitStreamsHost bo=build_bucket_orbits(storage,layout,owner,lowsparse,highdirect);BucketFusedHost bf=build_bucket_fused(storage,layout,owner,ordinary,cross,fused);ReverseLowDescHost rlow=build_reverse_low_descriptors(storage,layout);ReverseHighDescHost rhigh=build_reverse_high_descriptors(storage,layout);ReverseOrbitHost rlo=build_reverse_orbit(storage,layout,true),rhi=build_reverse_orbit(storage,layout,false);ReverseBucketAtomicHost rb=build_reverse_bucket_atomic(storage,layout,owner,rlow,rhigh,rlo,rhi);ReverseBucketFusedHost rf=build_reverse_bucket_fused_checked(layout,owner,rb);
    auto f32=build_bucket_forward_orbit_closure_attach(layout,bo,bf);auto r32=build_bucket_reverse_orbit_closure_attach_checked(layout,bo,bf,rb,rf);validate_reverse_bucket_partner_blocks(layout,rb);
    BucketOrbitStreamsHost bo18=bo;ReverseBucketAtomicHost rb18=rb;auto f18=build_bucket_forward_orbit_closure_attach18(layout,bo18,bf);auto r18=build_bucket_reverse_orbit_closure_attach18_checked(layout,bo18,bf,rb18,rf);
    BucketOrbitStreamsHost bo18d=bo;auto f18d=build_bucket_forward_orbit_closure_attach18_direct(layout,bo18d,bf);
    if(bo18d.low_nn!=bo18.low_nn||bo18d.low_nr!=bo18.low_nr||bo18d.low_nl!=bo18.low_nl||bo18d.high_nn!=bo18.high_nn||bo18d.high_nrnl!=bo18.high_nrnl||f18d.low_nn!=f18.low_nn||f18d.low_nr!=f18.low_nr||f18d.low_nl!=f18.low_nl||f18d.high_nn!=f18.high_nn||f18d.high_nrnl!=f18.high_nrnl){std::cerr<<"packed18 direct forward mismatch\n";return 413;}
    uint64_t checked=0;size_t lp=size_t(bo.low_nblocks)+1,hp=size_t(bo.high_nblocks)+1,rp=size_t(rb.nblocks)+1;
    auto eq=[&](uint32_t a,uint32_t b,const char*w){if(a!=b){std::cerr<<"packed18 reconstruction mismatch "<<w<<" got="<<b<<" expected="<<a<<'\n';std::exit(410);}++checked;};
    auto baseeqf=[&](BucketOrbitOp a,BucketOrbitOp b){if((a&BKOC18_FORWARD_BASE_MASK)!=(b&BKOC18_FORWARD_BASE_MASK))std::exit(411);};
    auto baseeqr=[&](ReverseBucketOrbitOp a,ReverseBucketOrbitOp b){if((a&BKOC18_REVERSE_BASE_MASK)!=(b&BKOC18_REVERSE_BASE_MASK))std::exit(412);};
    for(size_t i=0;i<bo.low_nn.size();++i)baseeqf(bo.low_nn[i],bo18.low_nn[i]);for(size_t i=0;i<bo.low_nr.size();++i)baseeqf(bo.low_nr[i],bo18.low_nr[i]);for(size_t i=0;i<bo.low_nl.size();++i)baseeqf(bo.low_nl[i],bo18.low_nl[i]);for(size_t i=0;i<bo.high_nn.size();++i)baseeqf(bo.high_nn[i],bo18.high_nn[i]);for(size_t i=0;i<bo.high_nrnl.size();++i)baseeqf(bo.high_nrnl[i],bo18.high_nrnl[i]);for(size_t i=0;i<rb.low_orbit.size();++i)baseeqr(rb.low_orbit[i],rb18.low_orbit[i]);for(size_t i=0;i<rb.high_orbit.size();++i)baseeqr(rb.high_orbit[i],rb18.high_orbit[i]);
    for(int p=LOW_LUT_K;p>=1;--p){uint32_t pi=uint32_t(LOW_LUT_K-p);for(uint32_t bid=0;bid<bo.low_nblocks;++bid){uint32_t dbid=p==1?bid:uint32_t(layout.main_blocks[bid].he);size_t doi=size_t(pi)*bf.low_pitch+dbid;auto ck=[&](const auto&s,const auto&o,const auto&hi,const auto&off){uint32_t a=off[size_t(pi)*lp+bid],b=off[size_t(pi)*lp+bid+1];for(uint32_t q=a;q<b;++q)eq(s[q],rid18(fcode18(o[q],hi[q]),bf.low_off,doi),"forward-low");};ck(f32.low_nn,bo18.low_nn,f18.low_nn,bo.low_nn_off);ck(f32.low_nr,bo18.low_nr,f18.low_nr,bo.low_nr_off);ck(f32.low_nl,bo18.low_nl,f18.low_nl,bo.low_nl_off);}}
    for(int p=TARGET_W-1;p>=LOW_LUT_K+1;--p){uint32_t pi=uint32_t((TARGET_W-1)-p);for(uint32_t bid=0;bid<bo.high_nblocks;++bid){uint32_t dbid=uint32_t(layout.main_blocks[bid].hs);size_t doi=size_t(pi)*bf.high_pitch+dbid;auto ck=[&](const auto&s,const auto&o,const auto&hi,const auto&off){uint32_t a=off[size_t(pi)*hp+bid],b=off[size_t(pi)*hp+bid+1];for(uint32_t q=a;q<b;++q)eq(s[q],rid18(fcode18(o[q],hi[q]),bf.high_off,doi),"forward-high");};ck(f32.high_nn,bo18.high_nn,f18.high_nn,bo.high_nn_off);ck(f32.high_nrnl,bo18.high_nrnl,f18.high_nrnl,bo.high_nrnl_off);}}
    for(int p=1;p<=LOW_LUT_K;++p){uint32_t pi=uint32_t(p-1);for(uint32_t bid=0;bid<rb.nblocks;++bid){uint32_t dbid=uint32_t(layout.main_blocks[bid].he);size_t doi=size_t(pi)*rf.low_pitch+dbid;uint32_t a=rb.low_orbit_off[size_t(pi)*rp+bid],b=rb.low_orbit_off[size_t(pi)*rp+bid+1];for(uint32_t q=a;q<b;++q)eq(r32.low[q],rid18(rcode18(rb18.low_orbit[q],r18.low_mid[q],r18.low_hi2,q),rf.low_off,doi),"reverse-low");}}
    for(int p=LOW_LUT_K+1;p<TARGET_W;++p){uint32_t pi=uint32_t(p-(LOW_LUT_K+1));bool edge=p==TARGET_W-1;for(uint32_t bid=0;bid<rb.nblocks;++bid){uint32_t dbid=edge?bid:uint32_t(layout.main_blocks[bid].hs);size_t doi=size_t(pi)*rf.high_pitch+dbid;uint32_t a=rb.high_orbit_off[size_t(pi)*rp+bid],b=rb.high_orbit_off[size_t(pi)*rp+bid+1];for(uint32_t q=a;q<b;++q)eq(r32.high[q],rid18(rcode18(rb18.high_orbit[q],r18.high_mid[q],r18.high_hi2,q),rf.high_off,doi),"reverse-high");}}
    size_t fn=bo.low_nn.size()+bo.low_nr.size()+bo.low_nl.size()+bo.high_nn.size()+bo.high_nrnl.size();double oldm=double(f32.bytes()+r32.bytes())/double(1<<20),newm=double(f18.bytes()+r18.bytes())/double(1<<20);std::cout<<"orbit-closure-packed18-plan OK W="<<TARGET_W<<" checked="<<checked<<" old_attach_mib="<<oldm<<" packed_sidecar_mib="<<newm<<" sidecar_ratio="<<(oldm?newm/oldm:0.0)<<" forward_bytes_per_orbit=1 reverse_bytes_per_orbit=1.25 reverse_jblock_bits_embedded=6 direct_forward_match=1 avoided_forward_attach_bytes="<<(fn*sizeof(uint32_t))<<"\n";return 0;
}
