#define main pattern10_reference_main_unused
#include "ramstream32_bucket_reverse_fused_selftest.cu"
#undef main

#include "../ramstream32_bucket_orbit_closure_pattern10.cuh"

static void p10_forward_low(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"p10 flow H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_low_orbit_closure_pattern10(layout,256,4,4);ck(cudaDeviceSynchronize(),"p10 flow sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"p10 flow D2H");}bkft_free_slots(d);}}
static void p10_forward_high(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"p10 fhigh H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_high_orbit_closure_pattern10(layout,256,4,4);ck(cudaDeviceSynchronize(),"p10 fhigh sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"p10 fhigh D2H");}bkft_free_slots(d);}}
static void p10_reverse_low(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"p10 rlow H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_low_pattern10(layout,256,4,4);ck(cudaDeviceSynchronize(),"p10 rlow sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[fixed][s];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"p10 rlow D2H");}bkft_free_slots(d);}}
static void p10_reverse_high(BucketHostGrid&g,const StorageLayout&layout,const BucketPhysicalLayoutHost&phy,BucketFusedDeviceTables&dt){for(uint32_t fixed=0;fixed<BUCKET_NGPU;++fixed){std::array<Count*,BUCKET_NGPU>d{};bkft_alloc_slots(fixed,phy,d);for(uint32_t s=0;s<BUCKET_NGPU;++s){auto const&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(d[s],v.data(),v.size()*sizeof(Count),cudaMemcpyHostToDevice),"p10 rhigh H2D");}dt.bind_owner(fixed,phy,d);bucket_launch_reverse_high_pattern10(layout,256,4,4);ck(cudaDeviceSynchronize(),"p10 rhigh sync");for(uint32_t s=0;s<BUCKET_NGPU;++s){auto&v=g[s][fixed];if(!v.empty())ck(cudaMemcpy(v.data(),d[s],v.size()*sizeof(Count),cudaMemcpyDeviceToHost),"p10 rhigh D2H");}bkft_free_slots(d);}}

int main(){
    constexpr Count mod=4294967291u;constexpr int W=TARGET_W,L=LOW_LUT_K;static_assert(W<=12,"pattern10 selftest uses small width");int visible=0;cudaError_t ce=cudaGetDeviceCount(&visible);if(ce!=cudaSuccess||visible<1){std::cout<<"bucket-closure-pattern10-selftest SKIP no CUDA device\n";return 0;}ck(cudaSetDevice(0),"p10 set device");
    build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);HighDescHost highdesc=build_high_descriptors(storage,layout);LowOrbitHost loworbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuHighDirectHost highdirect=build_cpu_high_direct(storage,layout,highdesc);GpuDirectGatherHost ordinary=build_gpu_direct_gather(layout,lowdesc,loworbit,highdirect);GpuDirectCrossGatherHost cross=build_gpu_direct_cross_gather(storage,layout,lowdesc,loworbit,highdirect);GpuDirectFusedHost fused=build_gpu_direct_fused_checked(layout,ordinary,cross);CpuLowSparseHost lowsparse=build_cpu_low_sparse(storage,layout,lowdesc,loworbit);BucketOwnerHost owner=build_bucket_owners(G_FACTOR,storage);BucketPhysicalLayoutHost phy=build_bucket_physical_layout(layout,owner);BucketOrbitStreamsHost bo=build_bucket_orbits(storage,layout,owner,lowsparse,highdirect);BucketFusedHost bf=build_bucket_fused(storage,layout,owner,ordinary,cross,fused);build_bucket_forward_pattern10(layout,bo,bf);ReverseLowDescHost rlow=build_reverse_low_descriptors(storage,layout);ReverseHighDescHost rhigh=build_reverse_high_descriptors(storage,layout);ReverseOrbitHost rlo=build_reverse_orbit(storage,layout,true),rhi=build_reverse_orbit(storage,layout,false);ReverseBucketAtomicHost rb=build_reverse_bucket_atomic(storage,layout,owner,rlow,rhigh,rlo,rhi);ReverseSplit54Host rs54=build_reverse_split54(layout,rb,false);build_reverse_split54_pattern10(layout,bf,rs54);
    auto ms=gdg_enum_states(W),bs=gdg_enum_states(W-1);std::unordered_map<MateID,size_t>mi,di;for(size_t i=0;i<ms.size();++i)mi.emplace(ms[i],i);for(size_t i=0;i<bs.size();++i)di.emplace(bs[i],i);std::mt19937_64 rng(0x1618A10ULL);std::vector<Count>im(ms.size()),ib(bs.size());for(auto&x:im)x=Count(rng()%mod);for(auto&x:ib)x=Count(rng()%mod);auto[flm,flb]=gdg_reference_window(W,L,1,mod,ms,bs,mi,di,im,ib);auto[fhm,fhb]=gdg_reference_window(W,W-1,L+1,mod,ms,bs,mi,di,im,ib);auto[rlm,rlb]=bra_reference(1,L,mod,ms,bs,mi,di,im,ib);auto[rhm,rhb]=bra_reference(L+1,W-1,mod,ms,bs,mi,di,im,ib);
    ck(cudaMemcpyToSymbol(D_MOD,&mod,sizeof(mod)),"p10 modulus");BucketFusedDeviceTables dt;dt.install_metadata(layout,bo,bf);ReverseSplit54DeviceTables rs;rs.install(rs54);
    auto g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);p10_forward_low(g,layout,phy,dt);if(!bkft_compare("pattern10-forward-low",g,ms,bs,flm,flb,storage,layout,owner,phy))return 10;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);p10_forward_high(g,layout,phy,dt);if(!bkft_compare("pattern10-forward-high",g,ms,bs,fhm,fhb,storage,layout,owner,phy))return 11;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);p10_reverse_low(g,layout,phy,dt);if(!bkft_compare("pattern10-reverse-low",g,ms,bs,rlm,rlb,storage,layout,owner,phy))return 12;g=bkft_make_grid(ms,bs,im,ib,storage,layout,owner,phy);p10_reverse_high(g,layout,phy,dt);if(!bkft_compare("pattern10-reverse-high",g,ms,bs,rhm,rhb,storage,layout,owner,phy))return 13;
    std::cout<<"bucket-closure-pattern10-selftest OK W="<<W<<" closure_metadata_bytes=0 pattern_bits=10 pattern_extra_bytes=0 reverse_orbit_bytes="<<rs54.bytes()<<" pm_accum="<<GPU_DIRECT_PM_ACCUM<<"\n";rs.release();dt.release();return 0;
}
