#include "../ramstream32_bucket_orbit_closure_pattern10_depth8_highctx.cuh"
#define bucket_launch_high_orbit_closure_pattern10_depth8 bucket_launch_high_orbit_closure_pattern10_depth8_highctx
#define bucket_launch_reverse_high_pattern10_depth8 bucket_launch_reverse_high_pattern10_depth8_highctx
#include "ramstream32_bucket_orbit_closure_pattern10_depth8_selftest.cu"
