#define BUCKET_SNAKE_REVERSE_FUSED 1
#define main rs18_driver_main_unused
#include "../../b300/oneesan_cuda_gridfp_b300_bucket_snake_atomic.cu"
#undef main
#include "../ramstream32_bucket_reverse_fused_validate.hpp"
#include "../ramstream32_bucket_orbit_closure_preflight.cuh"
#include "../ramstream32_bucket_reverse_split18.hpp"

#include <cstdint>
#include <cstdlib>
#include <iostream>

int main(){
    build_full_dp();G_FACTOR=build_factor_tables();StorageFactorHost storage=build_storage_factor_tables(G_FACTOR);StorageLayout layout=build_storage_layout(storage);LowDescHost lowdesc=build_low_descriptors(storage,layout);HighDescHost highdesc=build_high_descriptors(storage,layout);LowOrbitHost loworbit=build_cpu_low_orbit(storage,layout,lowdesc);CpuHighDirectHost highdirect=build_cpu_high_direct(storage,layout,highdesc);GpuDirectGatherHost ordinary=build_gpu_direct_gather(layout,lowdesc,loworbit,highdirect);GpuDirectCrossGatherHost cross=build_gpu_direct_cross_gather(storage,layout,lowdesc,loworbit,highdirect);GpuDirectFusedHost fused=build_gpu_direct_fused_checked(layout,ordinary,cross);CpuLowSparseHost lowsparse=build_cpu_low_sparse(storage,layout,lowdesc,loworbit);BucketOwnerHost owner=build_bucket_owners(G_FACTOR,storage);BucketOrbitStreamsHost bo=build_bucket_orbits(storage,layout,owner,lowsparse,highdirect);BucketFusedHost bf=build_bucket_fused(storage,layout,owner,ordinary,cross,fused);ReverseLowDescHost rlow=build_reverse_low_descriptors(storage,layout);ReverseHighDescHost rhigh=build_reverse_high_descriptors(storage,layout);ReverseOrbitHost rlo=build_reverse_orbit(storage,layout,true),rhi=build_reverse_orbit(storage,layout,false);ReverseBucketAtomicHost rb=build_reverse_bucket_atomic(storage,layout,owner,rlow,rhigh,rlo,rhi);ReverseBucketFusedHost rf=build_reverse_bucket_fused_checked(layout,owner,rb);auto att=build_bucket_reverse_orbit_closure_attach_checked(layout,bo,bf,rb,rf);auto sp=build_reverse_split18(layout,rb,rf,att);
    size_t pitch=size_t(rb.nblocks)+1;uint64_t checked=0;
    auto side=[&](bool low,const ReverseSplit18SideHost&s){const auto&ov=low?rb.low_orbit:rb.high_orbit;const auto&oo=low?rb.low_orbit_off:rb.high_orbit_off;const auto&aa=low?att.low:att.high;uint32_t steps=low?LOW_LUT_K:HIGH_LUT_K;int p0=low?1:LOW_LUT_K+1;for(uint32_t pi=0;pi<steps;++pi){int p=p0+int(pi);bool edge=!low&&p==TARGET_W-1;for(uint32_t bid=0;bid<rb.nblocks;++bid){uint32_t ni=s.nn_off[size_t(pi)*pitch+bid],ri=s.nr_off[size_t(pi)*pitch+bid],li=s.nl_off[size_t(pi)*pitch+bid];uint32_t dbid=low?uint32_t(layout.main_blocks[bid].he):(edge?bid:uint32_t(layout.main_blocks[bid].hs));const auto&fo=low?rf.low_off:rf.high_off;uint32_t fp=low?rf.low_pitch:rf.high_pitch;size_t doi=size_t(pi)*fp+dbid;uint32_t a=oo[size_t(pi)*pitch+bid],b=oo[size_t(pi)*pitch+bid+1];for(uint32_t q=a;q<b;++q){uint64_t w=ov[q];uint32_t kind=rb_orbit_kind(w);const std::vector<BucketOrbitOp>*v=nullptr;const std::vector<uint8_t>*h=nullptr;uint32_t idx=0;if(kind==CPU_ORBIT_NN){v=&s.nn;h=&s.nn_hi;idx=ni++;}else if(kind==CPU_ORBIT_NR){v=&s.nr;h=&s.nr_hi;idx=ri++;}else{v=&s.nl;h=&s.nl_hi;idx=li++;}BucketOrbitOp z=(*v)[idx];if((z&BKOC18_FORWARD_BASE_MASK)!=(w&BKOC18_FORWARD_BASE_MASK)){std::cerr<<"reverse split locator mismatch\n";std::exit(440);}uint32_t code=(uint32_t((*h)[idx])<<10)|uint32_t((z>>54)&0x3ffu);uint32_t got=code==BKOC18_NONE?BKOC_NONE:fo[doi]+code;if(got!=aa[q]){std::cerr<<"reverse split attachment mismatch got="<<got<<" expected="<<aa[q]<<'\n';std::exit(441);}++checked;}if(ni!=s.nn_off[size_t(pi)*pitch+bid+1]||ri!=s.nr_off[size_t(pi)*pitch+bid+1]||li!=s.nl_off[size_t(pi)*pitch+bid+1])std::exit(442);}}};side(true,sp.low);side(false,sp.high);
    size_t old_side=4ull*(rb.low_orbit.size()+rb.high_orbit.size());size_t new_side=sp.low.nn_hi.size()+sp.low.nr_hi.size()+sp.low.nl_hi.size()+sp.high.nn_hi.size()+sp.high.nr_hi.size()+sp.high.nl_hi.size();std::cout<<"reverse-split18-plan OK W="<<TARGET_W<<" checked="<<checked<<" old_sidecar_mib="<<double(old_side)/double(1<<20)<<" split_sidecar_mib="<<double(new_side)/double(1<<20)<<" sidecar_ratio="<<(old_side?double(new_side)/double(old_side):0.0)<<" kind_bits=0 jblock_bits=0 bytes_per_orbit=1\n";return 0;
}
