#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"
SRC="$ONEESAN_ROOT/src/cuda/b300/oneesan_cuda_gridfp_b300_hbm32_fullmate_dropN.cu"
GEN="$ONEESAN_ROOT/scripts/build/gen-b300-vmm-production.py";PRUNE="$ONEESAN_ROOT/scripts/build/prune-b300-vmm-stale-shard-symbols.py";BASEARG="$ONEESAN_ROOT/scripts/build/lower-b300-vmm-basearg.py";PACK="$ONEESAN_ROOT/scripts/build/lower-b300-packed-group-meta.py";STAGE="$ONEESAN_ROOT/scripts/build/lower-b300-staged-group-meta.py";STATIC="$ONEESAN_ROOT/scripts/build/lower-b300-static-lpt-staged-meta.py";METAARG="$ONEESAN_ROOT/scripts/build/lower-b300-staged-meta-kernelarg.py";ROWLIMIT="$ONEESAN_ROOT/scripts/build/lower-b300-row-limit.py"
OUT="${OUT:-$ONEESAN_BUILD_DIR/generated_b300_vmm_static_lpt_metakernelarg_proof.cu}"
bash "$ONEESAN_ROOT/scripts/bench/b300-staged-group-meta-plan-proof.sh"
bash "$ONEESAN_ROOT/scripts/bench/b300-static-lpt-local-meta-proof.sh"
python3 "$GEN" "$SRC" "$OUT";python3 "$PRUNE" "$OUT" "$OUT";python3 "$BASEARG" "$OUT" "$OUT";python3 "$PACK" "$OUT" "$OUT";python3 "$STAGE" "$OUT" "$OUT";python3 "$STATIC" "$OUT" "$OUT";python3 "$METAARG" "$OUT" "$OUT";python3 "$ROWLIMIT" "$OUT" "$OUT"
grep -Fq 'const DeviceGroupMeta*group_meta=c.dGroupMeta+pg.meta_id;' "$OUT"
grep -Fq 'gather_main_kernel(Count*out,MateID*mates,Code n,const Count* auth,const DeviceGroupMeta*meta)' "$OUT"
grep -Fq 'gather_block_kernel(Count*out,Code n,const Count* auth,const DeviceGroupMeta*meta)' "$OUT"
grep -Fq 'scatter_main_kernel(const Count*in,Code n,Count* auth,const DeviceGroupMeta*meta)' "$OUT"
grep -Fq 'scatter_block_kernel(const Count*in,Code n,Count* auth,const DeviceGroupMeta*meta)' "$OUT"
grep -Fq 'rank_drop_n_t(Code src_rank,MateID m,int p,const DeviceGroupMeta*meta)' "$OUT"
grep -Fq 'blocked_group_kernel(const Count*in,Code n,Count*out_main,int p,const DeviceGroupMeta*meta)' "$OUT"
grep -Fq 'main_group_kernel(const Count*in,const MateID*mates,Code n,Count*out_main,Count*out_block,int p,const DeviceGroupMeta*meta)' "$OUT"
grep -Fq 'gather_main_kernel<<<bm,threads>>>(c.dA,useMate?c.dMate:nullptr,ms.size,c.authMain,group_meta)' "$OUT"
grep -Fq 'gather_block_kernel<<<bd,threads>>>(c.dD,ds.size,c.authBlock,group_meta)' "$OUT"
grep -Fq 'main_group_kernel<<<bm,threads,0,c.sMain>>>(cur,useMate?c.dMate:nullptr,ms.size,nxt,dnext,p,group_meta)' "$OUT"
grep -Fq 'blocked_group_kernel<<<bd,threads,0,c.sBlock>>>(dcur,ds.size,nxt,p,group_meta)' "$OUT"
grep -Fq 'scatter_main_kernel<<<bm,threads>>>(cur,ms.size,c.authMain,group_meta)' "$OUT"
grep -Fq 'scatter_block_kernel<<<bd,threads>>>(dcur,ds.size,c.authBlock,group_meta)' "$OUT"
grep -Fq 'copy_mode=H2D_once_local_then_no_meta_copy_per_group scheduler=static_lpt meta_access=staged_global_kernelarg' "$OUT"
grep -Fq 'B300_ROW_LIMIT' "$OUT"
for stale in D_GROUP_META D_MAIN_DP D_BLOCK_DP D_MAIN_FIXED D_MAIN_OCC D_BLOCK_FIXED D_BLOCK_OCC 'cudaMemcpyToSymbol(D_GROUP_META' 'staged group meta D2D';do if grep -Fq "$stale" "$OUT";then echo "zero-copy metadata source still contains $stale" >&2;exit 3;fi;done
echo "b300-vmm-static-lpt-metakernelarg-production-generate-proof OK scheduler=static_lpt metadata_replication=0 group_meta_source=staged_global_kernelarg constant_metadata_object=0 per_group_meta_copy_bytes=0 per_group_meta_symbol_copy_calls=0 metadata_kernel_launches=6 rank_drop_meta_arg=1 row_limit_env=B300_ROW_LIMIT"
