#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

N="${N:-27}"; [[ "$N" == 27 ]] || { echo 'forced profile tuner targets n=27' >&2; exit 2; }
ARCH="${ARCH:-native}"; PRIME="${SMOKE_PRIME:-4294967291}"; MAX_WINDOW="${MAX_WINDOW:-14}"
TARGET_MIB="${FORCED_TARGET_MIB:-65536}"; THREADS="${GRIDFP_THREADS:-256}"; ROWS="${FORCED_PRESELECT_ROWS:-1}"
REBUILD="${REBUILD:-1}"; PREFIX="${PREFIX:-$ONEESAN_ROOT/work/b300_forced_profile_tune27}"
LOGDIR="${LOGDIR:-${PREFIX}_logs}"; RESULT="${RESULT:-${PREFIX}.tsv}"; PROFILE_OUT="${PROFILE_OUT:-${PREFIX}.env}"
mkdir -p "$LOGDIR" "$(dirname "$RESULT")"
[[ "$REBUILD" == 0 || "$REBUILD" == 1 ]] || { echo 'REBUILD must be 0 or 1' >&2; exit 2; }
[[ "$ROWS" =~ ^[0-9]+$ ]] && (( ROWS>=1 && ROWS<28 )) || { echo 'FORCED_PRESELECT_ROWS must be 1..27' >&2; exit 2; }
command -v nvcc >/dev/null || { echo 'nvcc required' >&2; exit 2; }
command -v nvidia-smi >/dev/null || { echo 'nvidia-smi required' >&2; exit 2; }
(( $(nvidia-smi --query-gpu=index --format=csv,noheader | wc -l) >= 8 )) || { echo 'need 8 visible GPUs' >&2; exit 2; }

# profile|ILP|high-drop-chunk|low-main-recurrence|high-main-recurrence
SPECS=(
 'forced_ilp1|1|0|0|0'
 'forced|2|0|0|0'
 'forced_ilp3|3|0|0|0'
 'forced_ilp4|4|0|0|0'
 'forced_high|2|1|0|0'
 'forced_lowrec|2|0|1|0'
 'forced_highrec|2|0|0|1'
 'forced_highrec_high|2|1|0|1'
)
declare -A BINS BUILD_OK BUILD_ERR
build_one(){
 local mode="$1" ilp="$2" high="$3" lowrec="$4" highrec="$5"
 local bin="$ONEESAN_BUILD_DIR/b300_forced_profile_${mode}_n27" bout="$LOGDIR/$mode.build.out" berr="$LOGDIR/$mode.build.err"
 BINS[$mode]="$bin"; BUILD_ERR[$mode]="$berr"
 if [[ "$REBUILD" == 0 && -x "$bin" ]]; then BUILD_OK[$mode]=1; return 0; fi
 set +e
 N=27 ARCH="$ARCH" OUT="$bin" MAIN_PULL_ILP="$ilp" HIGH_DROP_CHUNK="$high" LOW_MAIN_RECURRENCE="$lowrec" HIGH_MAIN_RECURRENCE="$highrec" \
   MAIN_MATE_CACHE=1 MAIN_PULL=1 BLOCK_PULL=1 BLOCK_MATE_CACHE=1 FAST_SHARD_ADDRESS8=1 LOW_DROP_CACHE=1 LOW_DROP_CHUNK=1 LOW_BLOCK_CACHE=1 RUNTIME_THREADS=1 PTXAS_VERBOSE=1 \
   bash "$ONEESAN_ROOT/scripts/build/b300-hbm32-batch.sh" >"$bout" 2>"$berr"
 local rc=$?; set -e
 if ((rc)); then BUILD_OK[$mode]=0; echo "exclude $mode: build rc=$rc" >&2; return 0; fi
 if ! grep -Fq "main_pull_ilp=$ilp" "$bout" || ! grep -Fq "high_drop_chunk=$high" "$bout" || ! grep -Fq "low_main_recurrence=$lowrec" "$bout" || ! grep -Fq "high_main_recurrence=$highrec" "$bout" || ! grep -Fq 'batch_row_limit_env=B300_ROW_LIMIT' "$bout"; then
   BUILD_OK[$mode]=0; echo "exclude $mode: build metadata mismatch" >&2; return 0
 fi
 BUILD_OK[$mode]=1
}
for spec in "${SPECS[@]}"; do IFS='|' read -r m a b c d <<<"$spec"; build_one "$m" "$a" "$b" "$c" "$d"; done

field(){ local k="$1" l="$2"; sed -nE "s/(^|.*[[:space:]])${k}=([^[:space:]]+).*/\\2/p" <<<"$l" | tail -n1; }
printf 'profile\tbinary\tstatus\tpartial_residue\twall_s\tmc_avg_pct\tmc_max_pct\n' >"$RESULT"
run_one(){
 local mode="$1" bin="${BINS[$1]}" so="$LOGDIR/$1.out" se="$LOGDIR/$1.err" dm="$LOGDIR/$1.dmon"
 if [[ "${BUILD_OK[$mode]:-0}" != 1 ]]; then printf '%s\t%s\tfailed:build\tNA\tNA\tNA\tNA\n' "$mode" "$bin" >>"$RESULT"; return 0; fi
 nvidia-smi dmon -s u -d 1 >"$dm" 2>/dev/null & local dp=$!
 set +e; B300_ROW_LIMIT="$ROWS" GRIDFP_THREADS="$THREADS" "$bin" 27 "$TARGET_MIB" "$MAX_WINDOW" 8 "$PRIME" >"$so" 2>"$se"; local rc=$?; set -e
 kill "$dp" 2>/dev/null || true; wait "$dp" 2>/dev/null || true
 if ((rc)); then printf '%s\t%s\tfailed:%s\tNA\tNA\tNA\tNA\n' "$mode" "$bin" "$rc" >>"$RESULT"; return 0; fi
 local line="$(grep '^backend=gridfp-b300-hbm32-forced2window-opt-batch ' "$so" | tail -n1 || true)"
 if [[ -z "$line" ]] || ! grep -Fq " rows=$ROWS calibration=1 " <<<"$line"; then printf '%s\t%s\tfailed:no_row_result\tNA\tNA\tNA\tNA\n' "$mode" "$bin" >>"$RESULT"; return 0; fi
 local avg mx; read -r avg mx < <(awk 'BEGIN{n=0;s=0;m=0}!/^#/&&NF>=3{x=$3+0;s+=x;if(x>m)m=x;n++}END{if(n)printf "%.3f %.3f\n",s/n,m;else print "NA NA"}' "$dm")
 printf '%s\t%s\tok\t%s\t%s\t%s\t%s\n' "$mode" "$bin" "$(field residue "$line")" "$(field wall_s "$line")" "$avg" "$mx" >>"$RESULT"
}
for spec in "${SPECS[@]}"; do IFS='|' read -r m _ <<<"$spec"; run_one "$m"; done

python3 - "$RESULT" "$PROFILE_OUT" "$ROWS" <<'PY'
import csv,sys
src,out,rows=sys.argv[1:];r=list(csv.DictReader(open(src),delimiter='\t'));ok=[x for x in r if x['status']=='ok']
if not ok:raise SystemExit('no successful forced profile')
res={x['partial_residue'] for x in ok}
if len(res)!=1:raise SystemExit('FATAL forced partial residue mismatch '+repr({x['profile']:x['partial_residue'] for x in ok}))
for x in sorted(ok,key=lambda z:float(z['wall_s'])):
 print('FORCED_PROFILE',x['profile'],'wall_s='+x['wall_s'],'mc_avg='+x['mc_avg_pct'],'mc_max='+x['mc_max_pct'])
b=min(ok,key=lambda z:float(z['wall_s']))
with open(out,'w') as f:
 f.write('# generated by b300-forced-profile-tune27.sh\n')
 f.write(f'FORCED_PROFILE={b["profile"]}\n')
 f.write(f'FORCED_PROFILE_BIN={b["binary"]}\n')
 f.write(f'FORCED_PARTIAL_RESIDUE={b["partial_residue"]}\n')
 f.write(f'FORCED_PRESELECT_ROWS={rows}\n')
print('BEST_FORCED',b['profile'],'wall_s='+b['wall_s'],'profile_file='+out)
PY
cat "$RESULT"
echo "forced tuner OK rows=$ROWS result=$RESULT profile=$PROFILE_OUT" >&2
