#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"
SRC="$ONEESAN_ROOT/src/cuda/b300/oneesan_cuda_gridfp_b300_hbm32_fullmate_dropN.cu"
GEN="$ONEESAN_ROOT/scripts/build/gen-b300-vmm-production.py";PRUNE="$ONEESAN_ROOT/scripts/build/prune-b300-vmm-stale-shard-symbols.py";BASEARG="$ONEESAN_ROOT/scripts/build/lower-b300-vmm-basearg.py";PACK="$ONEESAN_ROOT/scripts/build/lower-b300-packed-group-meta.py";STAGE="$ONEESAN_ROOT/scripts/build/lower-b300-staged-group-meta.py";STATIC="$ONEESAN_ROOT/scripts/build/lower-b300-static-lpt-staged-meta.py";INTERVALS="$ONEESAN_ROOT/scripts/build/lower-b300-static-lpt-staged-intervals.py";ROWLIMIT="$ONEESAN_ROOT/scripts/build/lower-b300-row-limit.py"
OUT="${OUT:-$ONEESAN_BUILD_DIR/generated_b300_static_lpt_staged_intervals_proof.cu}"
bash "$ONEESAN_ROOT/scripts/bench/b300-staged-group-meta-plan-proof.sh"
bash "$ONEESAN_ROOT/scripts/bench/b300-static-lpt-local-meta-proof.sh"
bash "$ONEESAN_ROOT/scripts/bench/b300-static-lpt-interval-staging-proof.sh"
python3 "$GEN" "$SRC" "$OUT";python3 "$PRUNE" "$OUT" "$OUT";python3 "$BASEARG" "$OUT" "$OUT";python3 "$PACK" "$OUT" "$OUT";python3 "$STAGE" "$OUT" "$OUT";python3 "$STATIC" "$OUT" "$OUT";python3 "$INTERVALS" "$OUT" "$OUT";python3 "$ROWLIMIT" "$OUT" "$OUT"
grep -Fq 'PeerInterval*dStageIntervals=nullptr' "$OUT"
grep -Fq 'void stage_intervals(const std::vector<PeerInterval>& h)' "$OUT"
grep -Fq 'mi_stage_off=0,mi_stage_count=0,di_stage_off=0,di_stage_count=0' "$OUT"
grep -Fq 'c.maxIntervals=std::max({c.maxIntervals,pg.mi_stage_count,pg.di_stage_count})' "$OUT"
grep -Fq 'const PeerInterval*dmi=pg.mi_stage_count?c.dStageIntervals+pg.mi_stage_off:nullptr;' "$OUT"
grep -Fq 'const PeerInterval*ddi=pg.di_stage_count?c.dStageIntervals+pg.di_stage_off:nullptr;' "$OUT"
grep -Fq 'staged_interval_total_count!=8453518ull' "$OUT"
grep -Fq 'staged_interval_max_count!=1057352ull' "$OUT"
grep -Fq 'staged_interval_total_bytes!=202884432ull' "$OUT"
grep -Fq 'staged_interval_max_bytes!=25376448ull' "$OUT"
grep -Fq 'combined_stage_max_bytes!=53961480ull' "$OUT"
grep -Fq 'copy_mode=H2D_once_local_then_zero_interval_copy_per_group scheduler=static_lpt' "$OUT"
grep -Fq 'B300_STAGED_INTERVAL_MAX_MIB' "$OUT"
grep -Fq 'B300_ROW_LIMIT' "$OUT"
for stale in 'cudaMemcpy(c.dIM,pg.mi.data()' 'cudaMemcpy(c.dID,pg.di.data()' 'interval_blocks(pg.mi.size(),threads)' 'interval_blocks(pg.di.size(),threads)';do if grep -Fq "$stale" "$OUT";then echo "staged interval source still contains per-group interval transfer: $stale" >&2;exit 3;fi;done
echo "b300-vmm-static-lpt-staged-intervals-production-generate-proof OK scheduler=static_lpt metadata_replication=0 staged_intervals=1 per_group_interval_h2d=0 descriptor_bytes=24 expected_descriptors=8453518 expected_total_h2d_gib=0.188950851560 expected_old_repeated_h2d_gib=5.290623843670 expected_h2d_reduction=28x expected_combined_stage_max_mib_per_gpu=51.461677551 row_limit_env=B300_ROW_LIMIT"
