#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

PROFILE_IN="${PROFILE_IN:-$ONEESAN_ROOT/work/b300_hbm_profile_prectx21.env}"
PROFILE_OUT="${PROFILE_OUT:-$ONEESAN_ROOT/work/b300_hbm_profile_refined21.env}"
PREFIX="${PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_scheduler21}"
[[ -f "$PROFILE_IN" ]] || { echo "missing PROFILE_IN=$PROFILE_IN" >&2; exit 2; }
# shellcheck disable=SC1090
source "$PROFILE_IN"
ORBIT_PRECTX_COMPACT="${ORBIT_PRECTX_COMPACT:-0}"

for n in ORBIT_PROFILE ORBIT_COL_ILP ORBIT_SPARSE64 ORBIT_SORTED ORBIT_CPASYNC_PAIR ORBIT_PRECTX_FORWARD ORBIT_PRECTX_REVERSE; do
  [[ -n "${!n+x}" ]] || { echo "profile missing $n" >&2; exit 2; }
done
[[ "$ORBIT_PRECTX_COMPACT" == 0 || "$ORBIT_PRECTX_COMPACT" == 1 ]] || { echo 'ORBIT_PRECTX_COMPACT must be 0 or 1' >&2; exit 2; }
[[ "$ORBIT_PRECTX_COMPACT" == 0 || "$ORBIT_PRECTX_FORWARD" == 1 || "$ORBIT_PRECTX_REVERSE" == 1 ]] || { echo 'compact orbit prectx requires prectx' >&2; exit 2; }
[[ "$ORBIT_SORTED" == 0 ]] || { echo 'flat orbit scheduler currently uses the unsorted orbit-CTA table path' >&2; exit 2; }
WINNER_ENV="${WINNER_ENV:-${PREFIX}_winner.env}"

N=21 ARCH="${ARCH:-sm_103}" TARGET_MIB="${TARGET_MIB:-16384}" MAX_WINDOW="${MAX_WINDOW:-14}" \
DIRECTGATHER_SPARSE64="$ORBIT_SPARSE64" DIRECTGATHER_SORT_RANKS=0 ORBITCTA_COL_ILP="$ORBIT_COL_ILP" \
PAIR_MLP=1 CPASYNC_PAIR="$ORBIT_CPASYNC_PAIR" RANKFORMULA_MLP_WINDOW4=1 PM_ACCUM="${PM_ACCUM:-1}" \
PRECTX_FORWARD="$ORBIT_PRECTX_FORWARD" PRECTX_REVERSE="$ORBIT_PRECTX_REVERSE" PRECTX_COMPACT="$ORBIT_PRECTX_COMPACT" \
FLAT_PER_SM_LIST="${FLAT_PER_SM_LIST:-auto 1 2 4 8}" REPEATS="${REPEATS:-1}" PREFIX="$PREFIX" WINNER_ENV="$WINNER_ENV" \
  bash "$ONEESAN_ROOT/scripts/bench/b300-orbitcta-flat-ab.sh"

[[ -f "$WINNER_ENV" ]] || { echo "missing scheduler winner env: $WINNER_ENV" >&2; exit 3; }
# shellcheck disable=SC1090
source "$WINNER_ENV"
[[ "$ORBITCTA_FLAT" == 0 || "$ORBITCTA_FLAT" == 1 ]] || { echo 'bad ORBITCTA_FLAT winner' >&2; exit 3; }
# 0 means leave BUCKET_ORBITCTA_FLAT_BLOCKS_PER_SM unset and let the runtime use
# forward/reverse occupancy independently.
[[ "$BUCKET_ORBITCTA_FLAT_BLOCKS_PER_SM" =~ ^[0-9]+$ ]] || { echo 'bad flat blocks/SM winner' >&2; exit 3; }

python3 - "$PROFILE_IN" "$PROFILE_OUT" "$ORBITCTA_FLAT" "$BUCKET_ORBITCTA_FLAT_BLOCKS_PER_SM" "$ORBITCTA_SCHEDULER_PROFILE" "$ORBIT_PRECTX_COMPACT" <<'PY'
import sys,re
src,out,flat,psm,sched,compact=sys.argv[1:]
kv={}
order=[]
for line in open(src):
 s=line.strip()
 if not s or s.startswith('#') or '=' not in s: continue
 k,v=s.split('=',1)
 if k not in kv: order.append(k)
 kv[k]=v.strip('"')
kv.setdefault('ORBIT_PRECTX_COMPACT',compact)
if 'ORBIT_PRECTX_COMPACT' not in order: order.append('ORBIT_PRECTX_COMPACT')
root=re.sub(r'_sched_.*$','',kv['ORBIT_PROFILE'])
kv['ORBIT_PROFILE']=f'{root}_sched_{sched}'
kv['ORBITCTA_FLAT']=flat
kv['ORBITCTA_FLAT_BLOCKS_PER_SM']=psm
for k in ('ORBITCTA_FLAT','ORBITCTA_FLAT_BLOCKS_PER_SM'):
 if k not in order: order.append(k)
with open(out,'w') as f:
 f.write('# generated by b300-hbm-profile-refine-orbit-scheduler21.sh\n')
 for k in order:
  v=kv[k]
  if k=='CANDIDATES': f.write(f'{k}="{v}"\n')
  else: f.write(f'{k}={v}\n')
print('scheduler_profile='+sched,'flat='+flat,'blocks_per_sm='+psm,'pool_mode='+('occupancy' if psm=='0' else 'per_sm'),'profile_file='+out)
PY
cat "$PROFILE_OUT"
echo "orbit scheduler refine OK input=$PROFILE_IN output=$PROFILE_OUT winner=$ORBITCTA_SCHEDULER_PROFILE" >&2
