#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"
ARCH="${ARCH:-native}"; MOD="${MOD:-4294967291}"; TARGET_MIB="${TARGET_MIB:-65536}"; MAX_WINDOW="${MAX_WINDOW:-14}"; NGPU="${NGPU:-8}"
STAGE_F_ENV="${STAGE_F_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_nextself_staged_winner.env}"; STAGEN_WINNER_ENV="${STAGEN_WINNER_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_pair_block_load_stagen_staged_g${NGPU}_winner.env}"; STAGEN_PREPARE_ENV="${STAGEN_PREPARE_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_pair_block_load_stagen_fullprime_n27_prepared.env}"
STAGEO_PREPARE_ENV="${STAGEO_PREPARE_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_stageo_cg_l2_fullprime_n27_prepared.env}"; STAGEP_PREPARE_ENV="${STAGEP_PREPARE_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_stagep_mate_cg_l2_fullprime_n27_prepared.env}"; STAGEQ_PREPARE_ENV="${STAGEQ_PREPARE_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_stageq_ilp8_count_cg_l2_fullprime_n27_prepared.env}"
STAGER_WINNER_ENV="${STAGER_WINNER_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_stager_ilp2_load_staged_g${NGPU}_winner.env}"; STAGER_PREPARE_ENV="${STAGER_PREPARE_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_stager_ilp2_load_fullprime_n27_prepared.env}"; STAGES_WINNER_ENV="${STAGES_WINNER_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_stages_ilp2_cg_l2_staged_g${NGPU}_winner.env}"; STAGES_PREPARE_ENV="${STAGES_PREPARE_ENV:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_stages_ilp2_cg_l2_fullprime_n27_prepared.env}"
UPSTREAM_KIND="${UPSTREAM_KIND:-auto}"; SEARCH_ROWS="${SEARCH_ROWS:-1}"; VALIDATE_ROWS="${VALIDATE_ROWS:-4 8}"; SEARCH_REPEATS="${SEARCH_REPEATS:-1}"; VALIDATE_REPEATS="${VALIDATE_REPEATS:-1}"; MIN_SPEEDUP="${MIN_SPEEDUP:-1.002}"; POLICY_LIST="${POLICY_LIST:-default cg cs}"; THREADS_LIST="${THREADS_LIST:-128 256 512}"
PREFIX="${PREFIX:-$ONEESAN_ROOT/work/b300_nextgen_hybrid8_staget_ilp2_mate_staged_g${NGPU}}"; FINAL_ENV="${FINAL_ENV:-${PREFIX}_winner.env}"; SWEEP="$ONEESAN_ROOT/scripts/bench/b300-nextgen-hybrid8-staget-ilp2-mate-load-policy-sweep.sh"
mkdir -p "$(dirname "$PREFIX")" "$(dirname "$FINAL_ENV")"; [[ -s "$SWEEP" ]] || exit 2; case "$UPSTREAM_KIND" in auto|stager|stages) ;; *) exit 2;; esac; [[ "$SEARCH_ROWS" =~ ^[1-9][0-9]*$ ]] && ((SEARCH_ROWS<=28)) || exit 2; [[ "$NGPU" =~ ^[1-8]$ ]] || exit 2; for x in SEARCH_REPEATS VALIDATE_REPEATS; do [[ "${!x}" =~ ^[1-9][0-9]*$ ]] || exit 2; done
python3 - "$MIN_SPEEDUP" <<'PY'
import sys
if float(sys.argv[1])<1.0: raise SystemExit('MIN_SPEEDUP must be >=1')
PY
passes(){ python3 - "$1" "$MIN_SPEEDUP" <<'PY'
import sys
print(1 if float(sys.argv[1])>=float(sys.argv[2]) else 0)
PY
}
run_stage(){ local rows="$1" policies="$2" threads="$3" repeats="$4" tag="$5"; local p="${PREFIX}.${tag}.r${rows}" log="${p}.log" envf="${p}_winner.env"; STAGE_F_ENV="$STAGE_F_ENV" STAGEN_WINNER_ENV="$STAGEN_WINNER_ENV" STAGEN_PREPARE_ENV="$STAGEN_PREPARE_ENV" STAGEO_PREPARE_ENV="$STAGEO_PREPARE_ENV" STAGEP_PREPARE_ENV="$STAGEP_PREPARE_ENV" STAGEQ_PREPARE_ENV="$STAGEQ_PREPARE_ENV" STAGER_WINNER_ENV="$STAGER_WINNER_ENV" STAGER_PREPARE_ENV="$STAGER_PREPARE_ENV" STAGES_WINNER_ENV="$STAGES_WINNER_ENV" STAGES_PREPARE_ENV="$STAGES_PREPARE_ENV" UPSTREAM_KIND="$UPSTREAM_KIND" ARCH="$ARCH" MOD="$MOD" ROWS="$rows" TARGET_MIB="$TARGET_MIB" MAX_WINDOW="$MAX_WINDOW" NGPU="$NGPU" POLICY_LIST="$policies" THREADS_LIST="$threads" REPEATS="$repeats" PREFIX="$p" WINNER_ENV="$envf" bash "$SWEEP" | tee "$log" >&2; grep -Fq 'b300_staget_exact_match=1' "$log" || { echo "Stage-T exact gate missing rows=$rows" >&2; exit 4; }; [[ -s "$envf" ]] || exit 4; printf '%s\n' "$envf"; }
SEARCH_ENV="$(run_stage "$SEARCH_ROWS" "$POLICY_LIST" "$THREADS_LIST" "$SEARCH_REPEATS" search)"; source "$SEARCH_ENV"
RES_UP="$B300_STAGET_UPSTREAM_KIND"; R_UP="$B300_STAGET_STAGER_UPSTREAM_KIND"; LOW_PAIR="$B300_STAGET_LOW_PAIR_POLICY"; LOW_BLOCK="$B300_STAGET_LOW_BLOCK_POLICY"; LOW_PL2="$B300_STAGET_LOW_PAIR_L2_BYTES"; LOW_BL2="$B300_STAGET_LOW_BLOCK_L2_BYTES"; HIGH_PAIR="$B300_STAGET_HIGH_PAIR_POLICY"; HIGH_BLOCK="$B300_STAGET_HIGH_BLOCK_POLICY"; HIGH_PL2="$B300_STAGET_HIGH_PAIR_L2_BYTES"; HIGH_BL2="$B300_STAGET_HIGH_BLOCK_L2_BYTES"; HIGH_MATE="$B300_STAGET_HIGH_MATE_POLICY"; HIGH_MATE_L2="$B300_STAGET_HIGH_MATE_L2_BYTES"; UP_ROWS="$B300_STAGET_UPSTREAM_ROWS"; UP_RES="$B300_STAGET_UPSTREAM_RESIDUE"; UP_MANIFEST="$B300_STAGET_UPSTREAM_MANIFEST"; SELECTED="$B300_STAGET_POLICY"
check_config(){ [[ "$B300_STAGET_UPSTREAM_KIND" == "$RES_UP" && "$B300_STAGET_STAGER_UPSTREAM_KIND" == "$R_UP" && "$B300_STAGET_NGPU" == "$NGPU" ]] || { echo 'Stage-T upstream/GPU drift' >&2; exit 4; }; [[ "$B300_STAGET_LOW_PAIR_POLICY" == "$LOW_PAIR" && "$B300_STAGET_LOW_BLOCK_POLICY" == "$LOW_BLOCK" && "$B300_STAGET_LOW_PAIR_L2_BYTES" == "$LOW_PL2" && "$B300_STAGET_LOW_BLOCK_L2_BYTES" == "$LOW_BL2" ]] || { echo 'Stage-T low Count provenance drift' >&2; exit 4; }; [[ "$B300_STAGET_HIGH_PAIR_POLICY" == "$HIGH_PAIR" && "$B300_STAGET_HIGH_BLOCK_POLICY" == "$HIGH_BLOCK" && "$B300_STAGET_HIGH_PAIR_L2_BYTES" == "$HIGH_PL2" && "$B300_STAGET_HIGH_BLOCK_L2_BYTES" == "$HIGH_BL2" && "$B300_STAGET_HIGH_MATE_POLICY" == "$HIGH_MATE" && "$B300_STAGET_HIGH_MATE_L2_BYTES" == "$HIGH_MATE_L2" ]] || { echo 'Stage-T high-state provenance drift' >&2; exit 4; }; [[ "$B300_STAGET_CONTROL_POLICY" == default && "$B300_STAGET_UPSTREAM_MANIFEST" == "$UP_MANIFEST" ]] || { echo 'Stage-T exact control provenance drift' >&2; exit 4; }; }
check_residue(){ local rows="$1" got="$2"; if [[ "$rows" == "$UP_ROWS" && "$got" != "$UP_RES" ]]; then echo "FATAL Stage-T/upstream residue mismatch rows=$rows got=$got expected=$UP_RES" >&2; exit 4; fi; }
check_config; check_residue "$SEARCH_ROWS" "$B300_STAGET_RESIDUE"
VALIDATED=0; CURRENT_ENV="$SEARCH_ENV"
if [[ "$B300_STAGET_BEST_ENABLED" == 1 && "$B300_STAGET_CONTROL_SPILL_FREE" == 1 && "$B300_STAGET_SPILL_FREE" == 1 && "$SELECTED" != default && "$(passes "$B300_STAGET_SPEEDUP")" == 1 ]]; then
 VALIDATED=1; control_threads="$B300_STAGET_CONTROL_THREADS"; test_threads="$B300_STAGET_THREADS"; validation_threads="$control_threads"; [[ "$test_threads" == "$control_threads" ]] || validation_threads+=" $test_threads"; validation_policies="default $SELECTED"; validate_rows=(); for rows in $VALIDATE_ROWS "$UP_ROWS"; do [[ "$rows" =~ ^[1-9][0-9]*$ ]] || continue; [[ "$rows" == "$SEARCH_ROWS" ]] && continue; seen=0; for old in "${validate_rows[@]}"; do [[ "$old" == "$rows" ]] && seen=1; done; ((seen)) || validate_rows+=("$rows"); done; stage=0
 for rows in "${validate_rows[@]}"; do ((stage+=1)); CURRENT_ENV="$(run_stage "$rows" "$validation_policies" "$validation_threads" "$VALIDATE_REPEATS" "validate${stage}")"; source "$CURRENT_ENV"; check_config; check_residue "$rows" "$B300_STAGET_RESIDUE"; if [[ "$B300_STAGET_POLICY" != "$SELECTED" || "$B300_STAGET_BEST_ENABLED" != 1 || "$B300_STAGET_CONTROL_SPILL_FREE" != 1 || "$B300_STAGET_SPILL_FREE" != 1 || "$(passes "$B300_STAGET_SPEEDUP")" != 1 ]]; then VALIDATED=0; break; fi; control_threads="$B300_STAGET_CONTROL_THREADS"; test_threads="$B300_STAGET_THREADS"; validation_threads="$control_threads"; [[ "$test_threads" == "$control_threads" ]] || validation_threads+=" $test_threads"; done
fi
source "$CURRENT_ENV"; check_config
if [[ "$VALIDATED" == 1 ]]; then FINAL_POLICY="$B300_STAGET_POLICY"; FINAL_BIN="$B300_STAGET_BIN"; FINAL_THREADS="$B300_STAGET_THREADS"; FINAL_WALL="$B300_STAGET_WALL_S"; FINAL_HIGH="$B300_STAGET_HIGH_S"; FINAL_SPEED="$B300_STAGET_SPEEDUP"; else FINAL_POLICY=default; FINAL_BIN="$B300_STAGET_CONTROL_BIN"; FINAL_THREADS="$B300_STAGET_CONTROL_THREADS"; FINAL_WALL="$B300_STAGET_CONTROL_WALL_S"; FINAL_HIGH="$B300_STAGET_CONTROL_HIGH_S"; FINAL_SPEED=1.000000000; fi
{
 printf 'B300_STAGET_STAGED_VALIDATED=%q\n' "$VALIDATED"; printf 'B300_STAGET_FINAL_ENABLED=%q\n' "$VALIDATED"; printf 'B300_STAGET_NGPU=%q\n' "$NGPU"; printf 'B300_STAGET_UPSTREAM_KIND=%q\n' "$RES_UP"; printf 'B300_STAGET_STAGER_UPSTREAM_KIND=%q\n' "$R_UP"
 printf 'B300_STAGET_LOW_PAIR_POLICY=%q\n' "$LOW_PAIR"; printf 'B300_STAGET_LOW_BLOCK_POLICY=%q\n' "$LOW_BLOCK"; printf 'B300_STAGET_LOW_PAIR_L2_BYTES=%q\n' "$LOW_PL2"; printf 'B300_STAGET_LOW_BLOCK_L2_BYTES=%q\n' "$LOW_BL2"; printf 'B300_STAGET_HIGH_PAIR_POLICY=%q\n' "$HIGH_PAIR"; printf 'B300_STAGET_HIGH_BLOCK_POLICY=%q\n' "$HIGH_BLOCK"; printf 'B300_STAGET_HIGH_PAIR_L2_BYTES=%q\n' "$HIGH_PL2"; printf 'B300_STAGET_HIGH_BLOCK_L2_BYTES=%q\n' "$HIGH_BL2"; printf 'B300_STAGET_HIGH_MATE_POLICY=%q\n' "$HIGH_MATE"; printf 'B300_STAGET_HIGH_MATE_L2_BYTES=%q\n' "$HIGH_MATE_L2"
 printf 'B300_STAGET_CONTROL_POLICY=default\n'; printf 'B300_STAGET_POLICY=%q\n' "$FINAL_POLICY"; printf 'B300_STAGET_FINAL_BIN=%q\n' "$FINAL_BIN"; printf 'B300_STAGET_FINAL_THREADS=%q\n' "$FINAL_THREADS"; printf 'B300_STAGET_FINAL_WALL_S=%q\n' "$FINAL_WALL"; printf 'B300_STAGET_FINAL_HIGH_S=%q\n' "$FINAL_HIGH"; printf 'B300_STAGET_FINAL_SPEEDUP=%q\n' "$FINAL_SPEED"; printf 'B300_STAGET_FINAL_SPILL_FREE=1\n'; printf 'B300_STAGET_CONTROL_BIN=%q\n' "$B300_STAGET_CONTROL_BIN"; printf 'B300_STAGET_CONTROL_THREADS=%q\n' "$B300_STAGET_CONTROL_THREADS"; printf 'B300_STAGET_FINAL_STAGE_ROWS=%q\n' "$B300_STAGET_ROWS"; printf 'B300_STAGET_FINAL_STAGE_RESIDUE=%q\n' "$B300_STAGET_RESIDUE"; printf 'B300_STAGET_UPSTREAM_ROWS=%q\n' "$UP_ROWS"; printf 'B300_STAGET_UPSTREAM_RESIDUE=%q\n' "$UP_RES"; printf 'B300_STAGET_UPSTREAM_MANIFEST=%q\n' "$UP_MANIFEST"; printf 'B300_STAGET_SEARCH_POLICIES=%q\n' "$POLICY_LIST"; printf 'B300_STAGET_MIN_SPEEDUP=%q\n' "$MIN_SPEEDUP"
} >"$FINAL_ENV"
cat "$FINAL_ENV"; echo "b300-nextgen-hybrid8-staget-ilp2-mate-staged-calibrate OK stage=T validated=$VALIDATED upstream=$RES_UP r_upstream=$R_UP high_mate=$HIGH_MATE high_mate_l2=$HIGH_MATE_L2 policy=$FINAL_POLICY speedup=${FINAL_SPEED}x final_rows=$B300_STAGET_ROWS ngpu=$NGPU" >&2
