#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

PROFILE_IN="${PROFILE_IN:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_bid21.env}"
PROFILE_OUT="${PROFILE_OUT:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_lease21.env}"
PREFIX="${PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_lease21}"
WINNER_ENV="${WINNER_ENV:-${PREFIX}_winner.env}"
[[ -f "$PROFILE_IN" ]] || { echo "missing PROFILE_IN=$PROFILE_IN" >&2; exit 2; }
# shellcheck disable=SC1090
source "$PROFILE_IN"

: "${ORBIT_COL_ILP:?profile missing ORBIT_COL_ILP}"
: "${ORBIT_SPARSE64:?profile missing ORBIT_SPARSE64}"
: "${ORBIT_CPASYNC_PAIR:?profile missing ORBIT_CPASYNC_PAIR}"
ORBITCTA_FLAT_DYNAMIC="${ORBITCTA_FLAT_DYNAMIC:-0}"
ORBITCTA_FLAT_DYNAMIC_BATCH="${ORBITCTA_FLAT_DYNAMIC_BATCH:-1}"
ORBITCTA_FLAT_DYNAMIC_FUSE_LEASE_PREP="${ORBITCTA_FLAT_DYNAMIC_FUSE_LEASE_PREP:-0}"
ORBIT_PRECTX_FORWARD="${ORBIT_PRECTX_FORWARD:-0}"
ORBIT_PRECTX_REVERSE="${ORBIT_PRECTX_REVERSE:-0}"
ORBIT_PRECTX_COMPACT="${ORBIT_PRECTX_COMPACT:-0}"
ORBIT_PRECTX_FLAT_BID="${ORBIT_PRECTX_FLAT_BID:-0}"
ORBIT_PRECTX_FLAT_BID_FUSED="${ORBIT_PRECTX_FLAT_BID_FUSED:-0}"
for x in ORBIT_SPARSE64 ORBIT_CPASYNC_PAIR ORBITCTA_FLAT_DYNAMIC ORBITCTA_FLAT_DYNAMIC_FUSE_LEASE_PREP ORBIT_PRECTX_FORWARD ORBIT_PRECTX_REVERSE ORBIT_PRECTX_COMPACT ORBIT_PRECTX_FLAT_BID ORBIT_PRECTX_FLAT_BID_FUSED; do
  v="${!x}"; [[ "$v" == 0 || "$v" == 1 ]] || { echo "$x must be 0/1" >&2; exit 2; }
done
case "$ORBIT_COL_ILP" in 2|4) ;; *) echo 'dynamic lease refine expects ORBIT_COL_ILP=2 or 4' >&2; exit 2;; esac
case "$ORBITCTA_FLAT_DYNAMIC_BATCH" in 1|2|4|8|16) ;; *) echo 'bad ORBITCTA_FLAT_DYNAMIC_BATCH' >&2; exit 2;; esac
[[ "$ORBITCTA_FLAT_DYNAMIC" == 1 ]] || { echo 'dynamic lease refine requires dynamic winner' >&2; exit 2; }
[[ "$ORBITCTA_FLAT_DYNAMIC_FUSE_LEASE_PREP" == 0 ]] || { echo 'dynamic lease refine input must be untuned fuse=0' >&2; exit 2; }
[[ "$ORBIT_PRECTX_FLAT_BID" == 1 || "$ORBIT_PRECTX_FLAT_BID_FUSED" == 0 ]] || { echo 'fused flat-bid requires flat-bid' >&2; exit 2; }

N=21 ARCH="${ARCH:-sm_103}" TARGET_MIB="${TARGET_MIB:-16384}" MAX_WINDOW="${MAX_WINDOW:-14}" REPEATS="${REPEATS:-1}" \
  DIRECTGATHER_SPARSE64="$ORBIT_SPARSE64" ORBITCTA_COL_ILP="$ORBIT_COL_ILP" CPASYNC_PAIR="$ORBIT_CPASYNC_PAIR" \
  ORBITCTA_FLAT_DYNAMIC_BATCH="$ORBITCTA_FLAT_DYNAMIC_BATCH" PM_ACCUM="${PM_ACCUM:-1}" \
  PRECTX_FORWARD="$ORBIT_PRECTX_FORWARD" PRECTX_REVERSE="$ORBIT_PRECTX_REVERSE" PRECTX_COMPACT="$ORBIT_PRECTX_COMPACT" \
  PRECTX_FLAT_BID="$ORBIT_PRECTX_FLAT_BID" PRECTX_FLAT_BID_FUSED="$ORBIT_PRECTX_FLAT_BID_FUSED" \
  PREFIX="$PREFIX" WINNER_ENV="$WINNER_ENV" \
  bash "$ONEESAN_ROOT/scripts/bench/b300-orbitcta-flat-dynamic-lease-prep-ab.sh"
[[ -f "$WINNER_ENV" ]] || { echo "missing dynamic lease winner=$WINNER_ENV" >&2; exit 3; }

python3 - "$PROFILE_IN" "$WINNER_ENV" "$PROFILE_OUT" <<'PY'
import sys,re
pin,wenv,pout=sys.argv[1:]
def read(path):
 d={}; order=[]
 for line in open(path):
  s=line.strip()
  if not s or s.startswith('#') or '=' not in s: continue
  k,v=s.split('=',1)
  if k not in d: order.append(k)
  d[k]=v.strip('"')
 return d,order
kv,order=read(pin); w,_=read(wenv)
for k in ('ORBITCTA_FLAT_DYNAMIC_FUSE_LEASE_PREP','ORBIT_DYNAMIC_LEASE_PREP_PROFILE','ORBIT_DYNAMIC_LEASE_PREP_WALL_S','ORBIT_DYNAMIC_LEASE_PREP_HIGH_S'):
 if k in w:
  kv[k]=w[k]
  if k not in order: order.append(k)
root=re.sub(r'_lease_fuse[01]$','',kv.get('ORBIT_PROFILE','orbit'))
flag=kv.get('ORBITCTA_FLAT_DYNAMIC_FUSE_LEASE_PREP','0')
kv['ORBIT_PROFILE']=root+'_lease_fuse'+flag
if 'ORBIT_PROFILE' not in order: order.append('ORBIT_PROFILE')
with open(pout,'w') as f:
 f.write('# generated by b300-hbm-profile-refine-orbit-dynamic-lease21.sh\n')
 for k in order:
  v=kv[k]
  if k=='CANDIDATES': f.write(f'{k}="{v}"\n')
  else: f.write(f'{k}={v}\n')
print('DYNAMIC_LEASE_REFINE',f"winner={w.get('ORBIT_DYNAMIC_LEASE_PREP_PROFILE')}",f"fuse={flag}",f'profile_file={pout}')
PY
cat "$PROFILE_OUT"
echo "dynamic lease/prepare refine OK input=$PROFILE_IN output=$PROFILE_OUT winner=$WINNER_ENV" >&2
