#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

PROFILE_BASE="${PROFILE_BASE:-$ONEESAN_ROOT/work/b300_hbm_profile_scheduler21.env}"
PROFILE_ADV="${PROFILE_ADV:-$ONEESAN_ROOT/work/b300_hbm_profile_advanced21.env}"
ADV_SUMMARY="${ADV_SUMMARY:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_advanced21_summary.tsv}"
PROFILE_OUT="${PROFILE_OUT:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic21.env}"
PREFIX="${PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic21}"
WINNER_ENV="${WINNER_ENV:-${PREFIX}_winner.env}"
[[ -f "$PROFILE_BASE" ]] || { echo "missing PROFILE_BASE=$PROFILE_BASE" >&2; exit 2; }
[[ -f "$PROFILE_ADV" ]] || { echo "missing PROFILE_ADV=$PROFILE_ADV" >&2; exit 2; }
[[ -f "$ADV_SUMMARY" ]] || { echo "missing ADV_SUMMARY=$ADV_SUMMARY" >&2; exit 2; }
# shellcheck disable=SC1090
source "$PROFILE_BASE"

: "${ORBIT_COL_ILP:?base profile missing ORBIT_COL_ILP}"
: "${ORBIT_SPARSE64:?base profile missing ORBIT_SPARSE64}"
: "${ORBIT_CPASYNC_PAIR:?base profile missing ORBIT_CPASYNC_PAIR}"
: "${ORBIT_PRECTX_FORWARD:?base profile missing ORBIT_PRECTX_FORWARD}"
: "${ORBIT_PRECTX_REVERSE:?base profile missing ORBIT_PRECTX_REVERSE}"
ORBIT_PRECTX_COMPACT="${ORBIT_PRECTX_COMPACT:-0}"
case "$ORBIT_COL_ILP" in 2|4) ;; *) echo 'dynamic refine expects ORBIT_COL_ILP=2 or 4' >&2; exit 2;; esac
for x in ORBIT_SPARSE64 ORBIT_CPASYNC_PAIR ORBIT_PRECTX_FORWARD ORBIT_PRECTX_REVERSE ORBIT_PRECTX_COMPACT; do v="${!x}"; [[ "$v" == 0 || "$v" == 1 ]] || { echo "$x must be 0/1" >&2; exit 2; }; done

N=21 ARCH="${ARCH:-sm_103}" TARGET_MIB="${TARGET_MIB:-16384}" MAX_WINDOW="${MAX_WINDOW:-14}" REPEATS="${REPEATS:-1}" \
  DIRECTGATHER_SPARSE64="$ORBIT_SPARSE64" ORBITCTA_COL_ILP="$ORBIT_COL_ILP" CPASYNC_PAIR="$ORBIT_CPASYNC_PAIR" PM_ACCUM="${PM_ACCUM:-1}" \
  PRECTX_FORWARD="$ORBIT_PRECTX_FORWARD" PRECTX_REVERSE="$ORBIT_PRECTX_REVERSE" PRECTX_COMPACT="$ORBIT_PRECTX_COMPACT" \
  BATCHES="${DYNAMIC_BATCHES:-1 2 4 8 16}" PREFIX="$PREFIX" WINNER_ENV="$WINNER_ENV" \
  bash "$ONEESAN_ROOT/scripts/bench/b300-orbitcta-flat-dynamic-batch-sweep.sh"
[[ -f "$WINNER_ENV" ]] || { echo "missing dynamic winner env=$WINNER_ENV" >&2; exit 3; }

python3 - "$PROFILE_BASE" "$PROFILE_ADV" "$ADV_SUMMARY" "$WINNER_ENV" "$PROFILE_OUT" <<'PY'
import csv,sys,re
pbase,padv,summary,wenv,pout=sys.argv[1:]
def env(path):
 d={};order=[]
 for line in open(path):
  s=line.strip()
  if not s or s.startswith('#') or '=' not in s: continue
  k,v=s.split('=',1)
  if k not in d: order.append(k)
  d[k]=v.strip('"')
 return d,order
base,base_order=env(pbase); adv,adv_order=env(padv); dyn,_=env(wenv)
rows=list(csv.DictReader(open(summary),delimiter='\t'))
if not rows: raise SystemExit('empty advanced summary')
adv_best=min(rows,key=lambda r:float(r['wall_s']))
adv_wall=float(adv_best['wall_s']); dyn_wall=float(dyn['ORBIT_DYNAMIC_WALL_S'])
promote=dyn.get('ORBITCTA_FLAT_DYNAMIC','0')=='1' and dyn_wall < adv_wall
if promote:
 out=dict(base); order=list(base_order)
 defaults={
  'ORBITCTA_FLAT':'1','ORBITCTA_FLAT_CHUNK':'1','ORBITCTA_FLAT_BLOCKS_PER_SM':'0',
  'ORBITCTA_FLAT_DYNAMIC':'1','ORBITCTA_FLAT_DYNAMIC_BATCH':dyn['ORBITCTA_FLAT_DYNAMIC_BATCH'],
  'ORBIT_QUAD_MLP':'0','ORBIT_QUAD_OVERLAP_LOCAL':'0','ORBIT_QUAD_LOCAL_DIRECT_MAX':'0','ORBIT_QUAD_SPARSE_DESC_MLP':'0',
  'ORBIT_QUAD_OVERLAP_BYPASS_LOCAL0':'0','ORBIT_QUAD_CPASYNC_GROUP_COLS':'1','ORBIT_QUAD_CPASYNC_PREFETCH_BYTES':'0',
  'ORBIT_PRECTX_FLAT_BID':'0','ORBIT_PRECTX_FLAT_BID_FUSED':'0','ORBIT_PRECTX_WARPCOOP':'0',
  'ORBIT_DYNAMIC_PROFILE':dyn.get('ORBIT_DYNAMIC_PROFILE','dynamic'),
  'ORBIT_ADVANCED_PROFILE':'dynamic_queue'
 }
 out.update(defaults)
 root=re.sub(r'_adv_.*$','',out.get('ORBIT_PROFILE','orbit'))
 out['ORBIT_PROFILE']=root+'_adv_dynamic_b'+dyn['ORBITCTA_FLAT_DYNAMIC_BATCH']
 for k in defaults:
  if k not in order: order.append(k)
 if 'ORBIT_PROFILE' not in order: order.append('ORBIT_PROFILE')
else:
 out=dict(adv);order=list(adv_order)
 out.setdefault('ORBITCTA_FLAT_DYNAMIC','0');out.setdefault('ORBITCTA_FLAT_DYNAMIC_BATCH','1')
 for k in ('ORBITCTA_FLAT_DYNAMIC','ORBITCTA_FLAT_DYNAMIC_BATCH'):
  if k not in order: order.append(k)
with open(pout,'w') as f:
 f.write('# generated by b300-hbm-profile-refine-orbit-dynamic21.sh\n')
 for k in order:
  v=out[k]
  if k=='CANDIDATES': f.write(f'{k}="{v}"\n')
  else: f.write(f'{k}={v}\n')
print('DYNAMIC_REFINE',f'advanced={adv_best["candidate"]}',f'advanced_wall_s={adv_wall:.6f}',f'dynamic_mode={dyn.get("ORBIT_DYNAMIC_PROFILE")}',f'dynamic_wall_s={dyn_wall:.6f}',f'promote={int(promote)}',f'profile_file={pout}')
PY
cat "$PROFILE_OUT"
echo "dynamic orbit refine OK base=$PROFILE_BASE advanced=$PROFILE_ADV summary=$ADV_SUMMARY output=$PROFILE_OUT winner=$WINNER_ENV" >&2
