#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

BASE_PROFILE="${BASE_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_tune21.env}"
PRECTX_PROFILE="${PRECTX_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_prectx21.env}"
SCHED_PROFILE="${SCHED_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_scheduler21.env}"
ADV_PROFILE="${ADV_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_advanced21.env}"
DYNAMIC_PROFILE="${DYNAMIC_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic21.env}"
DYNAMIC_BID_PROFILE="${DYNAMIC_BID_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_bid21.env}"
DYNAMIC_FUSE_PROFILE="${DYNAMIC_FUSE_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_fuse21.env}"
DYNAMIC_ADAPTIVE_PROFILE="${DYNAMIC_ADAPTIVE_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_adaptive21.env}"
DYNAMIC_PIPE2_PROFILE="${DYNAMIC_PIPE2_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_pipe221.env}"
DYNAMIC_QUAD_PROFILE="${DYNAMIC_QUAD_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_quad21.env}"
DYNAMIC_PRODUCER_PROFILE="${DYNAMIC_PRODUCER_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_producer21.env}"
DYNAMIC_PRODUCER_PRECTX_PROFILE="${DYNAMIC_PRODUCER_PRECTX_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_dynamic_producer_prectx21.env}"
WARPCOOP_PROFILE="${WARPCOOP_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_warpcoop21.env}"
WARPCOOP_AUTO_PROFILE="${WARPCOOP_AUTO_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_warpcoop_auto21.env}"
DESC_PROFILE="${DESC_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_desc21.env}"
LOCAL0_PROFILE="${LOCAL0_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_local021.env}"
GROUP_PROFILE="${GROUP_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_group21.env}"
FINAL_PROFILE="${FINAL_PROFILE:-$ONEESAN_ROOT/work/b300_hbm_profile_refined21.env}"
BASE_PREFIX="${BASE_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_tune21}"
PRECTX_PREFIX="${PRECTX_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_refine_compact_prectx21}"
SCHED_PREFIX="${SCHED_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_scheduler21}"
ADV_PREFIX="${ADV_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_advanced21}"
DYNAMIC_PREFIX="${DYNAMIC_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic21}"
DYNAMIC_BID_PREFIX="${DYNAMIC_BID_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_bid21}"
DYNAMIC_FUSE_PREFIX="${DYNAMIC_FUSE_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_fuse21}"
DYNAMIC_ADAPTIVE_PREFIX="${DYNAMIC_ADAPTIVE_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_adaptive21}"
DYNAMIC_PIPE2_PREFIX="${DYNAMIC_PIPE2_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_pipe221}"
DYNAMIC_QUAD_PREFIX="${DYNAMIC_QUAD_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_quad21}"
DYNAMIC_PRODUCER_PREFIX="${DYNAMIC_PRODUCER_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_producer21}"
DYNAMIC_PRODUCER_PRECTX_PREFIX="${DYNAMIC_PRODUCER_PRECTX_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_dynamic_producer_prectx21}"
WARPCOOP_PREFIX="${WARPCOOP_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_warpcoop21}"
WARPCOOP_AUTO_PREFIX="${WARPCOOP_AUTO_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_warpcoop_auto21}"
QUAD_DESC_PREFIX="${QUAD_DESC_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_quad_desc21}"
QUAD_LOCAL0_PREFIX="${QUAD_LOCAL0_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_quad_local021}"
QUAD_GROUP_PREFIX="${QUAD_GROUP_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_quad_group21}"
QUAD_PREFETCH_PREFIX="${QUAD_PREFETCH_PREFIX:-$ONEESAN_ROOT/work/b300_hbm_profile_orbit_quad_prefetch21}"
RUN_PRECTX="${RUN_PRECTX:-1}"
RUN_ORBIT_SCHEDULER="${RUN_ORBIT_SCHEDULER:-1}"
RUN_ORBIT_ADVANCED="${RUN_ORBIT_ADVANCED:-${RUN_ORBIT_QUAD:-1}}"
RUN_ORBIT_DYNAMIC="${RUN_ORBIT_DYNAMIC:-1}"
RUN_ORBIT_DYNAMIC_BID="${RUN_ORBIT_DYNAMIC_BID:-1}"
RUN_ORBIT_DYNAMIC_FUSE="${RUN_ORBIT_DYNAMIC_FUSE:-1}"
RUN_ORBIT_DYNAMIC_ADAPTIVE="${RUN_ORBIT_DYNAMIC_ADAPTIVE:-1}"
RUN_ORBIT_DYNAMIC_PIPE2="${RUN_ORBIT_DYNAMIC_PIPE2:-1}"
RUN_ORBIT_DYNAMIC_QUAD="${RUN_ORBIT_DYNAMIC_QUAD:-1}"
RUN_ORBIT_DYNAMIC_PRODUCER="${RUN_ORBIT_DYNAMIC_PRODUCER:-1}"
RUN_ORBIT_DYNAMIC_PRODUCER_PRECTX="${RUN_ORBIT_DYNAMIC_PRODUCER_PRECTX:-1}"
RUN_ORBIT_WARPCOOP="${RUN_ORBIT_WARPCOOP:-1}"
RUN_ORBIT_WARPCOOP_AUTO="${RUN_ORBIT_WARPCOOP_AUTO:-1}"
RUN_ORBIT_QUAD_DESC="${RUN_ORBIT_QUAD_DESC:-1}"
RUN_ORBIT_QUAD_LOCAL0="${RUN_ORBIT_QUAD_LOCAL0:-1}"
RUN_ORBIT_QUAD_GROUP="${RUN_ORBIT_QUAD_GROUP:-1}"
RUN_ORBIT_QUAD_PREFETCH="${RUN_ORBIT_QUAD_PREFETCH:-1}"
for x in RUN_PRECTX RUN_ORBIT_SCHEDULER RUN_ORBIT_ADVANCED RUN_ORBIT_DYNAMIC RUN_ORBIT_DYNAMIC_BID RUN_ORBIT_DYNAMIC_FUSE RUN_ORBIT_DYNAMIC_ADAPTIVE RUN_ORBIT_DYNAMIC_PIPE2 RUN_ORBIT_DYNAMIC_QUAD RUN_ORBIT_DYNAMIC_PRODUCER RUN_ORBIT_DYNAMIC_PRODUCER_PRECTX RUN_ORBIT_WARPCOOP RUN_ORBIT_WARPCOOP_AUTO RUN_ORBIT_QUAD_DESC RUN_ORBIT_QUAD_LOCAL0 RUN_ORBIT_QUAD_GROUP RUN_ORBIT_QUAD_PREFETCH; do v="${!x}"; [[ "$v" == 0 || "$v" == 1 ]] || exit 2; done

echo "=== HBM tune21 base search ===" >&2
RUN_PRECTX="$RUN_PRECTX" PROFILE_OUT="$BASE_PROFILE" PREFIX="$BASE_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-tune21.sh"
if [[ "$RUN_PRECTX" == 1 ]]; then PROFILE_IN="$BASE_PROFILE" PROFILE_OUT="$PRECTX_PROFILE" PREFIX="$PRECTX_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-compact-prectx21.sh"; else cp "$BASE_PROFILE" "$PRECTX_PROFILE"; fi
if [[ "$RUN_ORBIT_SCHEDULER" == 1 ]]; then PROFILE_IN="$PRECTX_PROFILE" PROFILE_OUT="$SCHED_PROFILE" PREFIX="$SCHED_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-scheduler21.sh"; else cp "$PRECTX_PROFILE" "$SCHED_PROFILE"; fi
if [[ "$RUN_ORBIT_ADVANCED" == 1 ]]; then PROFILE_IN="$SCHED_PROFILE" PROFILE_OUT="$ADV_PROFILE" PREFIX="$ADV_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-advanced21.sh"; else cp "$SCHED_PROFILE" "$ADV_PROFILE"; fi
if [[ "$RUN_ORBIT_DYNAMIC" == 1 && "$RUN_ORBIT_ADVANCED" == 1 ]]; then PROFILE_BASE="$SCHED_PROFILE" PROFILE_ADV="$ADV_PROFILE" ADV_SUMMARY="${ADV_PREFIX}_summary.tsv" PROFILE_OUT="$DYNAMIC_PROFILE" PREFIX="$DYNAMIC_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic21.sh"; else cp "$ADV_PROFILE" "$DYNAMIC_PROFILE"; fi

ORBITCTA_FLAT_DYNAMIC=0 ORBIT_PRECTX_FORWARD=0 ORBIT_PRECTX_REVERSE=0 ORBIT_PRECTX_COMPACT=0; source "$DYNAMIC_PROFILE"; DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"
if [[ "$RUN_ORBIT_DYNAMIC_BID" == 1 && "$DYNAMIC_SELECTED" == 1 && "${ORBIT_PRECTX_FORWARD:-0}" == 1 && "${ORBIT_PRECTX_REVERSE:-0}" == 1 && "${ORBIT_PRECTX_COMPACT:-0}" == 1 ]]; then PROFILE_IN="$DYNAMIC_PROFILE" PROFILE_OUT="$DYNAMIC_BID_PROFILE" PREFIX="$DYNAMIC_BID_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic-bid21.sh"; else cp "$DYNAMIC_PROFILE" "$DYNAMIC_BID_PROFILE"; fi
ORBITCTA_FLAT_DYNAMIC=0; source "$DYNAMIC_BID_PROFILE"; DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"
if [[ "$RUN_ORBIT_DYNAMIC_FUSE" == 1 && "$DYNAMIC_SELECTED" == 1 ]]; then PROFILE_IN="$DYNAMIC_BID_PROFILE" PROFILE_OUT="$DYNAMIC_FUSE_PROFILE" PREFIX="$DYNAMIC_FUSE_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic-fuse21.sh"; else cp "$DYNAMIC_BID_PROFILE" "$DYNAMIC_FUSE_PROFILE"; fi
ORBITCTA_FLAT_DYNAMIC=0 ORBITCTA_FLAT_DYNAMIC_BATCH=1; source "$DYNAMIC_FUSE_PROFILE"; DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"; DYNAMIC_BATCH_SELECTED="${ORBITCTA_FLAT_DYNAMIC_BATCH:-1}"
if [[ "$RUN_ORBIT_DYNAMIC_ADAPTIVE" == 1 && "$DYNAMIC_SELECTED" == 1 && "$DYNAMIC_BATCH_SELECTED" != 1 ]]; then PROFILE_IN="$DYNAMIC_FUSE_PROFILE" PROFILE_OUT="$DYNAMIC_ADAPTIVE_PROFILE" PREFIX="$DYNAMIC_ADAPTIVE_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic-adaptive21.sh"; else cp "$DYNAMIC_FUSE_PROFILE" "$DYNAMIC_ADAPTIVE_PROFILE"; fi
ORBITCTA_FLAT_DYNAMIC=0; source "$DYNAMIC_ADAPTIVE_PROFILE"; DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"
if [[ "$RUN_ORBIT_DYNAMIC_PIPE2" == 1 && "$DYNAMIC_SELECTED" == 1 ]]; then PROFILE_IN="$DYNAMIC_ADAPTIVE_PROFILE" PROFILE_OUT="$DYNAMIC_PIPE2_PROFILE" PREFIX="$DYNAMIC_PIPE2_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic-pipe2-21.sh"; else cp "$DYNAMIC_ADAPTIVE_PROFILE" "$DYNAMIC_PIPE2_PROFILE"; fi
ORBITCTA_FLAT_DYNAMIC=0; source "$DYNAMIC_PIPE2_PROFILE"; DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"
if [[ "$RUN_ORBIT_DYNAMIC_QUAD" == 1 && "$DYNAMIC_SELECTED" == 1 ]]; then
  echo "=== HBM tune21 dynamic pair-vs-quad MLP refinement ===" >&2
  PROFILE_IN="$DYNAMIC_PIPE2_PROFILE" PROFILE_OUT="$DYNAMIC_QUAD_PROFILE" PREFIX="$DYNAMIC_QUAD_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic-quad21.sh"
else cp "$DYNAMIC_PIPE2_PROFILE" "$DYNAMIC_QUAD_PROFILE"; fi

ORBITCTA_FLAT_DYNAMIC=0 ORBITCTA_FLAT_DYNAMIC_PIPE2=0; source "$DYNAMIC_QUAD_PROFILE"
DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"; DYNAMIC_PIPE2_SELECTED="${ORBITCTA_FLAT_DYNAMIC_PIPE2:-0}"
if [[ "$RUN_ORBIT_DYNAMIC_PRODUCER" == 1 && "$DYNAMIC_SELECTED" == 1 && "$DYNAMIC_PIPE2_SELECTED" == 1 ]]; then
  echo "=== HBM tune21 dynamic PIPE2 producer-warp refinement ===" >&2
  PROFILE_IN="$DYNAMIC_QUAD_PROFILE" PROFILE_OUT="$DYNAMIC_PRODUCER_PROFILE" PREFIX="$DYNAMIC_PRODUCER_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic-producer21.sh"
else cp "$DYNAMIC_QUAD_PROFILE" "$DYNAMIC_PRODUCER_PROFILE"; fi

ORBITCTA_FLAT_DYNAMIC=0 ORBITCTA_FLAT_DYNAMIC_PIPE2=0 ORBITCTA_FLAT_DYNAMIC_PIPE2_PRODUCER_WARP=0 ORBITCTA_FLAT_DYNAMIC_PIPE2_PRODUCER_WORKER_WEIGHT=0 ORBIT_QUAD_MLP=0 ORBIT_COL_ILP=0 ORBIT_CPASYNC_PAIR=0 ORBIT_PRECTX_FORWARD=0 ORBIT_PRECTX_REVERSE=0 ORBIT_PRECTX_COMPACT=0 ORBIT_PRECTX_FLAT_BID_FUSED=0 ORBITCTA_FLAT_BLOCKS_PER_SM=0
source "$DYNAMIC_PRODUCER_PROFILE"
DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"; PRODUCER_SELECTED="${ORBITCTA_FLAT_DYNAMIC_PIPE2_PRODUCER_WARP:-0}"
if [[ "$RUN_ORBIT_DYNAMIC_PRODUCER_PRECTX" == 1 && "$DYNAMIC_SELECTED" == 1 && "${ORBITCTA_FLAT_DYNAMIC_PIPE2:-0}" == 1 && "$PRODUCER_SELECTED" == 1 && "${ORBIT_QUAD_MLP:-0}" == 1 && "${ORBIT_COL_ILP:-0}" == 4 && "${ORBIT_CPASYNC_PAIR:-0}" == 1 && "${ORBIT_PRECTX_FORWARD:-0}" == 1 && "${ORBIT_PRECTX_REVERSE:-0}" == 1 && "${ORBIT_PRECTX_COMPACT:-0}" == 1 && "${ORBIT_PRECTX_FLAT_BID_FUSED:-0}" == 0 ]]; then
  echo "=== HBM tune21 producer compact-prectx warpcoop refinement ===" >&2
  PROFILE_IN="$DYNAMIC_PRODUCER_PROFILE" PROFILE_OUT="$DYNAMIC_PRODUCER_PRECTX_PROFILE" PREFIX="$DYNAMIC_PRODUCER_PRECTX_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-dynamic-producer-prectx21.sh"
else
  [[ "$DYNAMIC_SELECTED" == 0 || "$PRODUCER_SELECTED" == 0 || "$RUN_ORBIT_DYNAMIC_PRODUCER_PRECTX" == 0 ]] || echo "=== skip producer-prectx warpcoop: selected profile outside exact-tested domain ===" >&2
  cp "$DYNAMIC_PRODUCER_PROFILE" "$DYNAMIC_PRODUCER_PRECTX_PROFILE"
fi
ORBITCTA_FLAT_DYNAMIC=0; source "$DYNAMIC_PRODUCER_PRECTX_PROFILE"; DYNAMIC_SELECTED="${ORBITCTA_FLAT_DYNAMIC:-0}"

if [[ "$RUN_ORBIT_WARPCOOP" == 1 && "$RUN_ORBIT_ADVANCED" == 1 && "$DYNAMIC_SELECTED" == 0 ]]; then PROFILE_IN="$DYNAMIC_PRODUCER_PRECTX_PROFILE" PROFILE_OUT="$WARPCOOP_PROFILE" PREFIX="$WARPCOOP_PREFIX" QUAD_WINNER_ENV="${ADV_PREFIX}_quad_winner.env" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-warpcoop21.sh"; else cp "$DYNAMIC_PRODUCER_PRECTX_PROFILE" "$WARPCOOP_PROFILE"; fi
if [[ "$RUN_ORBIT_WARPCOOP_AUTO" == 1 && "$RUN_ORBIT_ADVANCED" == 1 && "$DYNAMIC_SELECTED" == 0 ]]; then PROFILE_IN="$WARPCOOP_PROFILE" PROFILE_OUT="$WARPCOOP_AUTO_PROFILE" PREFIX="$WARPCOOP_AUTO_PREFIX" QUAD_WINNER_ENV="${ADV_PREFIX}_quad_winner.env" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-warpcoop-auto21.sh"; else cp "$WARPCOOP_PROFILE" "$WARPCOOP_AUTO_PROFILE"; fi
if [[ "$RUN_ORBIT_QUAD_DESC" == 1 ]]; then ORBIT_QUAD_MLP=0 ORBIT_QUAD_OVERLAP_LOCAL=0 ORBIT_SPARSE64=0; source "$WARPCOOP_AUTO_PROFILE"; if [[ "${ORBIT_QUAD_MLP:-0}" == 1 && "${ORBIT_QUAD_OVERLAP_LOCAL:-0}" == 1 && "${ORBIT_SPARSE64:-0}" == 1 ]]; then PROFILE_IN="$WARPCOOP_AUTO_PROFILE" PROFILE_OUT="$DESC_PROFILE" PREFIX="$QUAD_DESC_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-quad-desc21.sh"; else cp "$WARPCOOP_AUTO_PROFILE" "$DESC_PROFILE"; fi; else cp "$WARPCOOP_AUTO_PROFILE" "$DESC_PROFILE"; fi
if [[ "$RUN_ORBIT_QUAD_LOCAL0" == 1 ]]; then ORBIT_QUAD_MLP=0 ORBIT_QUAD_OVERLAP_LOCAL=0; source "$DESC_PROFILE"; if [[ "${ORBIT_QUAD_MLP:-0}" == 1 && "${ORBIT_QUAD_OVERLAP_LOCAL:-0}" == 1 ]]; then PROFILE_IN="$DESC_PROFILE" PROFILE_OUT="$LOCAL0_PROFILE" PREFIX="$QUAD_LOCAL0_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-quad-local0-21.sh"; else cp "$DESC_PROFILE" "$LOCAL0_PROFILE"; fi; else cp "$DESC_PROFILE" "$LOCAL0_PROFILE"; fi
if [[ "$RUN_ORBIT_QUAD_GROUP" == 1 ]]; then ORBIT_QUAD_MLP=0 ORBIT_QUAD_OVERLAP_LOCAL=0; source "$LOCAL0_PROFILE"; if [[ "${ORBIT_QUAD_MLP:-0}" == 1 && "${ORBIT_QUAD_OVERLAP_LOCAL:-0}" == 1 ]]; then PROFILE_IN="$LOCAL0_PROFILE" PROFILE_OUT="$GROUP_PROFILE" PREFIX="$QUAD_GROUP_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-quad-group21.sh"; else cp "$LOCAL0_PROFILE" "$GROUP_PROFILE"; fi; else cp "$LOCAL0_PROFILE" "$GROUP_PROFILE"; fi
if [[ "$RUN_ORBIT_QUAD_PREFETCH" == 1 ]]; then ORBIT_QUAD_MLP=0 ORBIT_QUAD_OVERLAP_LOCAL=0; source "$GROUP_PROFILE"; if [[ "${ORBIT_QUAD_MLP:-0}" == 1 && "${ORBIT_QUAD_OVERLAP_LOCAL:-0}" == 1 ]]; then PROFILE_IN="$GROUP_PROFILE" PROFILE_OUT="$FINAL_PROFILE" PREFIX="$QUAD_PREFETCH_PREFIX" bash "$ONEESAN_ROOT/scripts/bench/b300-hbm-profile-refine-orbit-quad-prefetch21.sh"; else cp "$GROUP_PROFILE" "$FINAL_PROFILE"; fi; else cp "$GROUP_PROFILE" "$FINAL_PROFILE"; fi

echo "=== final HBM profile ===" >&2
cat "$FINAL_PROFILE"
echo "b300 HBM profile auto21 OK base_profile=$BASE_PROFILE prectx_profile=$PRECTX_PROFILE sched_profile=$SCHED_PROFILE advanced_profile=$ADV_PROFILE dynamic_profile=$DYNAMIC_PROFILE dynamic_bid_profile=$DYNAMIC_BID_PROFILE dynamic_fuse_profile=$DYNAMIC_FUSE_PROFILE dynamic_adaptive_profile=$DYNAMIC_ADAPTIVE_PROFILE dynamic_pipe2_profile=$DYNAMIC_PIPE2_PROFILE dynamic_quad_profile=$DYNAMIC_QUAD_PROFILE dynamic_producer_profile=$DYNAMIC_PRODUCER_PROFILE dynamic_producer_prectx_profile=$DYNAMIC_PRODUCER_PRECTX_PROFILE dynamic_selected=$DYNAMIC_SELECTED final_profile=$FINAL_PROFILE" >&2
