#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"
W="${W:-10}"; NGPU="${NGPU:-2}"; BLOCKS="${BLOCKS:-256}"; MOD="${MOD:-4294967291}"; REPEATS="${REPEATS:-7}"; WARMUP="${WARMUP:-1}"; ARCH="${ARCH:-native}"; PTXAS_VERBOSE="${PTXAS_VERBOSE:-1}"
if (( W < 8 || W > 28 || W % 2 != 0 || NGPU < 2 || NGPU > 8 || BLOCKS < 1 || REPEATS < 1 || WARMUP < 0 )); then echo "invalid W/NGPU/BLOCKS/REPEATS/WARMUP" >&2; exit 2; fi
if [[ "$MOD" != 4294967291 ]]; then echo "full runtime fast-stack A/B requires MOD=4294967291" >&2; exit 2; fi
if ! command -v nvcc >/dev/null || ! command -v nvidia-smi >/dev/null; then echo "nvcc and nvidia-smi are required" >&2; exit 2; fi
visible="$(nvidia-smi --query-gpu=index --format=csv,noheader | wc -l)"; (( visible >= NGPU )) || { echo "need $NGPU GPUs, visible=$visible" >&2; exit 2; }
PREFIX="${PREFIX:-$ONEESAN_ROOT/work/gridfp_reduced_runtime_stack_ab_w${W}_g${NGPU}_b${BLOCKS}}"; RESULT="${RESULT:-${PREFIX}.tsv}"; SUMMARY="${SUMMARY:-${PREFIX}_summary.tsv}"; LOGDIR="${LOGDIR:-${PREFIX}_logs}"; mkdir -p "$(dirname "$RESULT")" "$LOGDIR"
for proof in edgecache p32m5-mod sharedkey fastdiv64 primitive-rank-setbits broadword-support owner-boundary owner-reciprocal owner-fixed54 owner-fixed52 support-rank-setbits sector-offset-table sector-row-cache outer-group-table bitcompact discovery-validity discovery-shrink-validity discovery-llrr discovery-roundtrip discovery-endpoint-scan reverse-small-step-direct; do bash "$ONEESAN_ROOT/scripts/bench/gridfp-runtime-${proof}-proof.sh" >"$LOGDIR/${proof}-proof.out" 2>"$LOGDIR/${proof}-proof.err"; done
bash "$ONEESAN_ROOT/scripts/bench/gridfp-blocked-exclude-reverse-direct-proof.sh" >"$LOGDIR/blocked-exclude-reverse-direct-proof.out" 2>"$LOGDIR/blocked-exclude-reverse-direct-proof.err"
bash "$ONEESAN_ROOT/scripts/bench/gridfp-include-horizontal-reverse-direct-proof.sh" >"$LOGDIR/include-horizontal-reverse-direct-proof.out" 2>"$LOGDIR/include-horizontal-reverse-direct-proof.err"
bash "$ONEESAN_ROOT/scripts/bench/gridfp-mirror-mate-brev-proof.sh" >"$LOGDIR/mirror-mate-brev-proof.out" 2>"$LOGDIR/mirror-mate-brev-proof.err"
build_one(){ local mode="$1" bin="$2"; local cache fast poll packed fastdiv primitive broadword boundary recip fixed54 fixed52 support sector rowcache outer outside erase discovery endpoint fastmirror reverseinclude reverseblocked reversesmall; if [[ "$mode" == baseline ]]; then cache=0;fast=0;poll=1;packed=0;fastdiv=0;primitive=0;broadword=0;boundary=0;recip=0;fixed54=0;fixed52=0;support=0;sector=0;rowcache=0;outer=0;outside=0;erase=0;discovery=0;endpoint=0;fastmirror=0;reverseinclude=0;reverseblocked=0;reversesmall=0; else cache=1;fast=1;poll=0;packed=1;fastdiv=1;primitive=1;broadword=1;boundary=1;recip=1;fixed54=0;fixed52=1;support=1;sector=1;rowcache=1;outer=1;outside=1;erase=1;discovery=1;endpoint=1;fastmirror=1;reverseinclude=1;reverseblocked=1;reversesmall=1; fi; MODE=two-row-runtime-multigpu RUNTIME_CACHE_EDGES="$cache" RUNTIME_FAST_P32M5_MOD="$fast" RUNTIME_POLL_GLOBAL_ERROR="$poll" RUNTIME_PACK_SHARED_KEYS="$packed" RUNTIME_FAST_DIV64="$fastdiv" RUNTIME_PRIMITIVE_RANK_SETBITS="$primitive" RUNTIME_BROADWORD_SUPPORT="$broadword" RUNTIME_OWNER_FROM_BOUNDARIES="$boundary" RUNTIME_OWNER_RECIPROCAL="$recip" RUNTIME_OWNER_FIXED54="$fixed54" RUNTIME_OWNER_FIXED52="$fixed52" RUNTIME_SUPPORT_RANK_SETBITS="$support" RUNTIME_SECTOR_OFFSET_TABLE="$sector" RUNTIME_CACHE_SECTOR_ROW_BASE="$rowcache" RUNTIME_OUTER_GROUP_TABLE="$outer" RUNTIME_FAST_OUTSIDE_COMPACT="$outside" RUNTIME_FAST_ERASE_TWO_BITS="$erase" RUNTIME_FAST_DISCOVERY_VALIDITY="$discovery" RUNTIME_DISCOVERY_ENDPOINT_SCAN="$endpoint" RUNTIME_FIND_RECENT_FIRST=0 RUNTIME_FAST_MIRROR_MATE="$fastmirror" RUNTIME_FAST_INCLUDE_HORIZONTAL_REVERSE="$reverseinclude" RUNTIME_FAST_BLOCKED_EXCLUDE_REVERSE="$reverseblocked" RUNTIME_DIRECT_REVERSE_SMALL_STEP="$reversesmall" ARCH="$ARCH" PTXAS_VERBOSE="$PTXAS_VERBOSE" OUT="$bin" bash "$ONEESAN_ROOT/scripts/build/gridfp-reduced-component-probe.sh" >"$LOGDIR/${mode}.build.out" 2>"$LOGDIR/${mode}.build.err"; }
BASE="$ONEESAN_BUILD_DIR/gridfp_reduced_runtime_stack_baseline_w${W}_g${NGPU}_b${BLOCKS}"; FAST="$ONEESAN_BUILD_DIR/gridfp_reduced_runtime_stack_fast_w${W}_g${NGPU}_b${BLOCKS}"; build_one baseline "$BASE"; build_one fast "$FAST"
run_one(){ local mode="$1" bin="$2" rep="$3" phase="$4"; local out="$LOGDIR/${mode}_${phase}${rep}.out" err="$LOGDIR/${mode}_${phase}${rep}.err"; "$bin" "$W" "$NGPU" "$BLOCKS" "$MOD" >"$out" 2>"$err"; local line; line="$(grep '^gridfp-reduced-two-row-runtime-multigpu ' "$out" | tail -n1 || true)"; [[ -n "$line" ]] || { cat "$out" >&2 || true; cat "$err" >&2 || true; exit 3; }; grep -Fq ' exact=OK' <<<"$line" || { echo "$line" >&2; exit 4; }; if [[ "$phase" == run ]]; then local wall; wall="$(sed -nE 's/.* wall_ms=([^[:space:]]+).*/\1/p' <<<"$line")"; [[ -n "$wall" ]] || exit 5; printf '%s\t%s\t%s\n' "$mode" "$rep" "$wall" >>"$RESULT"; fi; }
for ((r=1;r<=WARMUP;++r)); do run_one baseline "$BASE" "$r" warmup; run_one fast "$FAST" "$r" warmup; done
printf 'runtime_stack\trepeat\twall_ms\n' >"$RESULT"
for ((r=1;r<=REPEATS;++r)); do if ((r&1)); then order=(baseline fast); else order=(fast baseline); fi; for mode in "${order[@]}"; do [[ "$mode" == baseline ]] && bin="$BASE" || bin="$FAST"; echo "=== runtime stack=$mode run $r/$REPEATS ===" >&2; run_one "$mode" "$bin" "$r" run; done; done
cat "$RESULT"
python3 - "$RESULT" "$SUMMARY" <<'PY'
import csv,statistics,sys
src,dst=sys.argv[1:]; rows=list(csv.DictReader(open(src),delimiter='\t')); out=[]
for mode in ('baseline','fast'):
 xs=[float(r['wall_ms']) for r in rows if r['runtime_stack']==mode]
 if not xs: raise SystemExit(f'missing runtime_stack={mode}')
 out.append({'runtime_stack':mode,'repeats':len(xs),'wall_ms_median':f'{statistics.median(xs):.9f}','wall_ms_min':f'{min(xs):.9f}','wall_ms_max':f'{max(xs):.9f}'})
with open(dst,'w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=('runtime_stack','repeats','wall_ms_median','wall_ms_min','wall_ms_max'),delimiter='\t'); w.writeheader(); w.writerows(out)
q={r['runtime_stack']:r for r in out}; old=float(q['baseline']['wall_ms_median']); new=float(q['fast']['wall_ms_median'])
print(f'runtime_fast_stack_wall_speedup={old/new:.6f}x'); print(f'runtime_fast_stack_wall_delta_pct={(new/old-1)*100:.4f}%')
print('runtime_fast_stack_baseline=edge_cache0,fast_mod0,error_poll1,packed_keys0,fast_div640,primitive_setbits0,broadword_support0,owner_boundaries0,owner_reciprocal0,owner_fixed540,owner_fixed520,support_setbits0,sector_table0,sector_row_cache0,outer_group_table0,outside_compact0,erase_two_bits0,discovery_validity0,endpoint_scan0,fast_mirror0,direct_reverse_include0,direct_reverse_blocked0,direct_reverse_small_step0')
print('runtime_fast_stack_fast=edge_cache1,fast_mod1,error_poll0,packed_keys1,fast_div641,primitive_setbits1,broadword_support1,owner_boundaries1,owner_reciprocal1,owner_fixed540,owner_fixed521,support_setbits1,sector_table1,sector_row_cache1,outer_group_table1,outside_compact1,erase_two_bits1,discovery_validity1,endpoint_scan1,fast_mirror1,direct_reverse_include1,direct_reverse_blocked1,direct_reverse_small_step1')
print('runtime_fast_stack_key_shared_bytes_saved_per_block=10240'); print('runtime_fast_stack_edge_cache_shared_bytes_added_per_block=2560'); print('runtime_fast_stack_net_known_shared_bytes_delta_per_block=-7680'); print('runtime_fast_stack_recomputed_small_steps_in_accumulation=0'); print('runtime_fast_stack_signed_64bit_divisions_at_mod4294967291=0'); print('runtime_fast_stack_dynamic_label_divmod_pairs_remaining=0'); print('runtime_fast_stack_global_error_polls_per_discovered_source=0'); print('runtime_fast_stack_primitive_rank_scan=occupied'); print('runtime_fast_stack_support_extraction=fixed_6_stage_broadword'); print('runtime_fast_stack_owner_lookup=fixed52_midpoint_mul_shift'); print('runtime_fast_stack_owner_shift=52'); print('runtime_fast_stack_owner_mulhi=0'); print('runtime_fast_stack_owner_correction=0'); print('runtime_fast_stack_owner_clamp=0'); print('runtime_fast_stack_owner_boundary_global_loads=0'); print('runtime_fast_stack_support_rank_scan=ones'); print('runtime_fast_stack_sector_offset=constant_lookup'); print('runtime_fast_stack_sector_row_base=once_per_component'); print('runtime_fast_stack_context_bytes=24'); print('runtime_fast_stack_outer_group_context=two_constant_loads'); print('runtime_fast_stack_outside_support_compaction=mask_shift'); print('runtime_fast_stack_blocked_local_compaction=three_segment_mask_shift'); print('runtime_fast_stack_discovery_full_validity_scans=0'); print('runtime_fast_stack_discovery_structural_include_rechecks=0'); print('runtime_fast_stack_discovery_rl_validity=two_popcounts'); print('runtime_fast_stack_discovery_ll_rr_validity=structural'); print('runtime_fast_stack_discovery_balance_scan=endpoints_only'); print('runtime_fast_stack_mirror_mate=device_brevll_shift'); print('runtime_fast_stack_reverse_include=direct_coordinate'); print('runtime_fast_stack_reverse_include_full_mirror_passes=0'); print('runtime_fast_stack_reverse_blocked_exclude=direct_insert'); print('runtime_fast_stack_reverse_blocked_exclude_mirror_passes=0'); print('runtime_fast_stack_reverse_small_step=direct_coordinate'); print('runtime_fast_stack_reverse_small_step_key_mirror_passes=0'); print('runtime_fast_stack_constant_table_bytes_added=6072'); print(f'summary={dst}')
PY
if [[ "$PTXAS_VERBOSE" == 1 ]]; then echo '--- ptxas baseline ---' >&2; grep -E 'Used .* registers|bytes smem|bytes cmem' "$LOGDIR/baseline.build.err" >&2 || true; echo '--- ptxas fast ---' >&2; grep -E 'Used .* registers|bytes smem|bytes cmem' "$LOGDIR/fast.build.err" >&2 || true; fi
echo "gridfp-reduced-runtime-stack-ab OK W=$W ngpu=$NGPU blocks=$BLOCKS repeats=$REPEATS result=$RESULT" >&2
